import * as z from 'zod';
// prettier-ignore
export const AgreementInputSchema = z.object({
    id: z.number().int(),
    sourceId: z.number().int().optional().nullable(),
    publisherId: z.number().int().optional().nullable(),
    clientId: z.number().int().optional().nullable(),
    titleId: z.number().int().optional().nullable(),
    agrDate: z.date(),
    validYY: z.number().int().optional().nullable(),
    pubTermMM: z.number().int().optional().nullable(),
    maxCopies: z.number().int().optional().nullable(),
    minCopies: z.number().int().optional().nullable(),
    copiesToOwner: z.number().int().optional().nullable(),
    copiesToGraal: z.number().int().optional().nullable(),
    currencyCode: z.string().optional().nullable(),
    commission: z.number().optional().nullable(),
    commissionMaterials: z.number().optional().nullable(),
    estimatedCopyPrice: z.number().optional().nullable(),
    graalShare: z.number().optional().nullable(),
    graalRepresent: z.boolean(),
    languageCode: z.string().optional().nullable(),
    countryId: z.number().int().optional().nullable(),
    localTitle: z.string().optional().nullable(),
    localIsbn: z.string().optional().nullable(),
    localPubDate: z.date().optional().nullable(),
    clientReference: z.string().optional().nullable(),
    agrDoc: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    remarks: z.string().optional().nullable(),
    agentId: z.number().int().optional().nullable(),
    dateMod: z.date().optional().nullable(),
    userMod: z.string().optional().nullable(),
    createdAt: z.date(),
    updatedAt: z.date(),
    Publisher: z.unknown().optional().nullable(),
    Client: z.unknown().optional().nullable(),
    Title: z.unknown().optional().nullable(),
    Rights: z.array(z.unknown()),
    Events: z.array(z.unknown()),
    Advances: z.array(z.unknown()),
    RoyRates: z.array(z.unknown())
}).strict();

export type AgreementInputType = z.infer<typeof AgreementInputSchema>;
