import * as z from 'zod';
// prettier-ignore
export const PublisherInputSchema = z.object({
    id: z.number().int(),
    sourceId: z.number().int().optional().nullable(),
    name: z.string(),
    abbreviation: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    phone: z.string().optional().nullable(),
    fax: z.string().optional().nullable(),
    www: z.string().optional().nullable(),
    createdAt: z.date(),
    updatedAt: z.date(),
    address: z.string().optional().nullable(),
    address2: z.string().optional().nullable(),
    city: z.string().optional().nullable(),
    state: z.string().optional().nullable(),
    postalCode: z.string().optional().nullable(),
    country: z.string().optional().nullable(),
    language: z.string().optional().nullable(),
    legalForm: z.string().optional().nullable(),
    nip: z.string().optional().nullable(),
    vatId: z.string().optional().nullable(),
    regon: z.string().optional().nullable(),
    jurisdiction: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    notes: z.string().optional().nullable(),
    bankAccount: z.string().optional().nullable(),
    bankName: z.string().optional().nullable(),
    bankAddress: z.string().optional().nullable(),
    bankRoutingNo: z.string().optional().nullable(),
    bankAccountName: z.string().optional().nullable(),
    commission: z.number().optional().nullable(),
    commissionForeign: z.number().optional().nullable(),
    commissionMaterials: z.number().optional().nullable(),
    repModeId: z.number().int().optional().nullable(),
    parentId: z.number().int().optional().nullable(),
    Parent: z.unknown().optional().nullable(),
    Children: z.array(z.unknown()),
    PublisherContact: z.array(z.unknown()),
    TaxResidenceCert: z.array(z.unknown()),
    TaxResidenceSend: z.array(z.unknown()),
    Title: z.array(z.unknown())
}).strict();

export type PublisherInputType = z.infer<typeof PublisherInputSchema>;
