import * as z from 'zod';
// prettier-ignore
export const tblAgreementsInputSchema = z.object({
    AgrID: z.number().int(),
    CustID: z.number().int().optional().nullable(),
    CountryID: z.number().int().optional().nullable(),
    LangAbbr: z.string().optional().nullable(),
    TitleID: z.number().int().optional().nullable(),
    CurrID: z.string().optional().nullable(),
    AgrDate: z.date(),
    ValidYY: z.number().int().optional().nullable(),
    PubTermMM: z.number().int().optional().nullable(),
    MaxNoOfCopies: z.number().int().optional().nullable(),
    MinNoOfCopies: z.number().int().optional().nullable(),
    Commission: z.number().optional().nullable(),
    ClientReference: z.string().optional().nullable(),
    DateMod: z.date().optional().nullable(),
    UserMod: z.string().optional().nullable(),
    GraalAgentID: z.number().int().optional().nullable(),
    GraalShare: z.number().optional().nullable(),
    EstimatedCopyPrice: z.number().optional().nullable(),
    GraalRepresent: z.boolean().optional().nullable(),
    Remarks: z.string().optional().nullable(),
    AgrDoc: z.string().optional().nullable(),
    Status: z.string().optional().nullable(),
    CopiesToOwner: z.number().int().optional().nullable(),
    CopiesToGraal: z.number().int().optional().nullable(),
    LocalTitle: z.string().optional().nullable(),
    LocalISBN: z.string().optional().nullable(),
    LocalPubDate: z.date().optional().nullable(),
    ClientID: z.number().int().optional().nullable(),
    CommissionMaterials: z.number().optional().nullable(),
    AgentID: z.number().int().optional().nullable(),
    PropID: z.number().int().optional().nullable(),
    tblAdvance: z.array(z.unknown()),
    dictCurrencies: z.unknown().optional().nullable(),
    tblTitles: z.unknown().optional().nullable(),
    dictLanguages: z.unknown().optional().nullable(),
    tblCustomers: z.unknown().optional().nullable(),
    dictCountries_old: z.unknown().optional().nullable(),
    tblAgrEvents: z.array(z.unknown()),
    tblAgrRights: z.array(z.unknown()),
    tblPubLocal: z.array(z.unknown()),
    tblRoyalty: z.array(z.unknown()),
    tblRoyRates: z.array(z.unknown())
}).strict();

export type tblAgreementsInputType = z.infer<typeof tblAgreementsInputSchema>;
