import * as z from 'zod';
// prettier-ignore
export const tblCustomersInputSchema = z.object({
    CustID: z.number().int(),
    CustAbb: z.string().optional().nullable(),
    Account: z.number().int().optional().nullable(),
    CountryID: z.number().int().optional().nullable(),
    Name: z.string().optional().nullable(),
    Address1: z.string().optional().nullable(),
    Address2: z.string().optional().nullable(),
    City: z.string().optional().nullable(),
    Zip: z.string().optional().nullable(),
    StateAbb: z.string().optional().nullable(),
    DefaultPhone: z.string().optional().nullable(),
    DefaultFax: z.string().optional().nullable(),
    DefaultEmail: z.string().optional().nullable(),
    DefaultWWW: z.string().optional().nullable(),
    ParentCustID: z.number().int().optional().nullable(),
    LangAbb: z.string().optional().nullable(),
    Remarks: z.string().optional().nullable(),
    DateMod: z.date().optional().nullable(),
    UserMod: z.string().optional().nullable(),
    TaxID: z.string().optional().nullable(),
    VATID: z.string().optional().nullable(),
    RepModeID: z.number().int().optional().nullable(),
    GraalID: z.number().int().optional().nullable(),
    Commission: z.number().optional().nullable(),
    DefAgrDoc: z.string().optional().nullable(),
    Jurisdiction: z.string().optional().nullable(),
    CommissionForeign: z.number().optional().nullable(),
    CommissionMaterials: z.number().optional().nullable(),
    Status: z.string().optional().nullable(),
    tblAgreements: z.array(z.unknown()),
    tblClients_obsolete: z.unknown().optional().nullable(),
    tblCustBank: z.unknown().optional().nullable(),
    tblCustContacts: z.array(z.unknown()),
    dictLanguages: z.unknown().optional().nullable(),
    dictStates: z.unknown().optional().nullable(),
    tblCustTypes: z.array(z.unknown()),
    tblCustUsers: z.array(z.unknown()),
    tblMailingLists: z.array(z.unknown()),
    tblSeries: z.array(z.unknown()),
    tblSubmissions: z.array(z.unknown()),
    tblTitles: z.array(z.unknown())
}).strict();

export type tblCustomersInputType = z.infer<typeof tblCustomersInputSchema>;
