import * as z from 'zod';
// prettier-ignore
export const tblTitlesInputSchema = z.object({
    TitleID: z.number().int(),
    CustID: z.number().int().optional().nullable(),
    PropID: z.number().int().optional().nullable(),
    Proprietor: z.string().optional().nullable(),
    LangAbb: z.string().optional().nullable(),
    ClassCode: z.string().optional().nullable(),
    CoverFormatID: z.number().int().optional().nullable(),
    Title: z.string(),
    ISBN1: z.string().optional().nullable(),
    ISBN2: z.string().optional().nullable(),
    ISBN3: z.string().optional().nullable(),
    ISBN4: z.string().optional().nullable(),
    SeriesIID: z.number().int().optional().nullable(),
    Edition: z.number().int().optional().nullable(),
    DateOfReceipt: z.date().optional().nullable(),
    NoOfPages: z.number().int().optional().nullable(),
    CopyrightYear: z.string().optional().nullable(),
    CopyrightOwner: z.string().optional().nullable(),
    CopyrightOwnerDesc: z.string().optional().nullable(),
    KeyWords: z.string().optional().nullable(),
    TitleVolume: z.number().int().optional().nullable(),
    NoOfTitleVolumes: z.number().int().optional().nullable(),
    Hit: z.boolean().optional().nullable(),
    Junk: z.boolean().optional().nullable(),
    CD: z.boolean().optional().nullable(),
    Collection: z.boolean().optional().nullable(),
    Remarks: z.string().optional().nullable(),
    UserMod: z.string(),
    DateMod: z.date(),
    ISBN: z.string().optional().nullable(),
    PubID: z.number().int().optional().nullable(),
    ProprietorDesc: z.string().optional().nullable(),
    ISBN0: z.string().optional().nullable(),
    tblAgreements: z.array(z.unknown()),
    tblSubmissions: z.array(z.unknown()),
    tblTitAuthors: z.array(z.unknown()),
    tblTitAux: z.unknown().optional().nullable(),
    tblTitEvents: z.array(z.unknown()),
    dictLanguages: z.unknown().optional().nullable(),
    tblCustomers: z.unknown().optional().nullable(),
    dictTitMainClass: z.unknown().optional().nullable(),
    dictCoverFormat: z.unknown().optional().nullable(),
    tblTitSubClass: z.array(z.unknown())
}).strict();

export type tblTitlesInputType = z.infer<typeof tblTitlesInputSchema>;
