import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblMailingTemplatesOrderByWithRelationInputObjectSchema as tblMailingTemplatesOrderByWithRelationInputObjectSchema } from './objects/tblMailingTemplatesOrderByWithRelationInput.schema';
import { tblMailingTemplatesWhereInputObjectSchema as tblMailingTemplatesWhereInputObjectSchema } from './objects/tblMailingTemplatesWhereInput.schema';
import { tblMailingTemplatesWhereUniqueInputObjectSchema as tblMailingTemplatesWhereUniqueInputObjectSchema } from './objects/tblMailingTemplatesWhereUniqueInput.schema';
import { TblMailingTemplatesCountAggregateInputObjectSchema as TblMailingTemplatesCountAggregateInputObjectSchema } from './objects/TblMailingTemplatesCountAggregateInput.schema';
import { TblMailingTemplatesMinAggregateInputObjectSchema as TblMailingTemplatesMinAggregateInputObjectSchema } from './objects/TblMailingTemplatesMinAggregateInput.schema';
import { TblMailingTemplatesMaxAggregateInputObjectSchema as TblMailingTemplatesMaxAggregateInputObjectSchema } from './objects/TblMailingTemplatesMaxAggregateInput.schema';
import { TblMailingTemplatesAvgAggregateInputObjectSchema as TblMailingTemplatesAvgAggregateInputObjectSchema } from './objects/TblMailingTemplatesAvgAggregateInput.schema';
import { TblMailingTemplatesSumAggregateInputObjectSchema as TblMailingTemplatesSumAggregateInputObjectSchema } from './objects/TblMailingTemplatesSumAggregateInput.schema';

export const tblMailingTemplatesAggregateSchema: z.ZodType<Prisma.tblMailingTemplatesAggregateArgs> = z.object({ orderBy: z.union([tblMailingTemplatesOrderByWithRelationInputObjectSchema, tblMailingTemplatesOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblMailingTemplatesWhereInputObjectSchema.optional(), cursor: tblMailingTemplatesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblMailingTemplatesCountAggregateInputObjectSchema ]).optional(), _min: TblMailingTemplatesMinAggregateInputObjectSchema.optional(), _max: TblMailingTemplatesMaxAggregateInputObjectSchema.optional(), _avg: TblMailingTemplatesAvgAggregateInputObjectSchema.optional(), _sum: TblMailingTemplatesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblMailingTemplatesAggregateArgs>;

export const tblMailingTemplatesAggregateZodSchema = z.object({ orderBy: z.union([tblMailingTemplatesOrderByWithRelationInputObjectSchema, tblMailingTemplatesOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblMailingTemplatesWhereInputObjectSchema.optional(), cursor: tblMailingTemplatesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblMailingTemplatesCountAggregateInputObjectSchema ]).optional(), _min: TblMailingTemplatesMinAggregateInputObjectSchema.optional(), _max: TblMailingTemplatesMaxAggregateInputObjectSchema.optional(), _avg: TblMailingTemplatesAvgAggregateInputObjectSchema.optional(), _sum: TblMailingTemplatesSumAggregateInputObjectSchema.optional() }).strict();