import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictCountries_oldOrderByWithRelationInputObjectSchema as dictCountries_oldOrderByWithRelationInputObjectSchema } from './objects/dictCountries_oldOrderByWithRelationInput.schema';
import { dictCountries_oldWhereInputObjectSchema as dictCountries_oldWhereInputObjectSchema } from './objects/dictCountries_oldWhereInput.schema';
import { dictCountries_oldWhereUniqueInputObjectSchema as dictCountries_oldWhereUniqueInputObjectSchema } from './objects/dictCountries_oldWhereUniqueInput.schema';
import { DictCountries_oldCountAggregateInputObjectSchema as DictCountries_oldCountAggregateInputObjectSchema } from './objects/DictCountries_oldCountAggregateInput.schema';
import { DictCountries_oldMinAggregateInputObjectSchema as DictCountries_oldMinAggregateInputObjectSchema } from './objects/DictCountries_oldMinAggregateInput.schema';
import { DictCountries_oldMaxAggregateInputObjectSchema as DictCountries_oldMaxAggregateInputObjectSchema } from './objects/DictCountries_oldMaxAggregateInput.schema';
import { DictCountries_oldAvgAggregateInputObjectSchema as DictCountries_oldAvgAggregateInputObjectSchema } from './objects/DictCountries_oldAvgAggregateInput.schema';
import { DictCountries_oldSumAggregateInputObjectSchema as DictCountries_oldSumAggregateInputObjectSchema } from './objects/DictCountries_oldSumAggregateInput.schema';

export const dictCountries_oldAggregateSchema: z.ZodType<Prisma.DictCountries_oldAggregateArgs> = z.object({ orderBy: z.union([dictCountries_oldOrderByWithRelationInputObjectSchema, dictCountries_oldOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictCountries_oldWhereInputObjectSchema.optional(), cursor: dictCountries_oldWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictCountries_oldCountAggregateInputObjectSchema ]).optional(), _min: DictCountries_oldMinAggregateInputObjectSchema.optional(), _max: DictCountries_oldMaxAggregateInputObjectSchema.optional(), _avg: DictCountries_oldAvgAggregateInputObjectSchema.optional(), _sum: DictCountries_oldSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.DictCountries_oldAggregateArgs>;

export const dictCountries_oldAggregateZodSchema = z.object({ orderBy: z.union([dictCountries_oldOrderByWithRelationInputObjectSchema, dictCountries_oldOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictCountries_oldWhereInputObjectSchema.optional(), cursor: dictCountries_oldWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictCountries_oldCountAggregateInputObjectSchema ]).optional(), _min: DictCountries_oldMinAggregateInputObjectSchema.optional(), _max: DictCountries_oldMaxAggregateInputObjectSchema.optional(), _avg: DictCountries_oldAvgAggregateInputObjectSchema.optional(), _sum: DictCountries_oldSumAggregateInputObjectSchema.optional() }).strict();