import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { BalanceAdjustmentOrderByWithRelationInputObjectSchema as BalanceAdjustmentOrderByWithRelationInputObjectSchema } from './objects/BalanceAdjustmentOrderByWithRelationInput.schema';
import { BalanceAdjustmentWhereInputObjectSchema as BalanceAdjustmentWhereInputObjectSchema } from './objects/BalanceAdjustmentWhereInput.schema';
import { BalanceAdjustmentWhereUniqueInputObjectSchema as BalanceAdjustmentWhereUniqueInputObjectSchema } from './objects/BalanceAdjustmentWhereUniqueInput.schema';
import { BalanceAdjustmentCountAggregateInputObjectSchema as BalanceAdjustmentCountAggregateInputObjectSchema } from './objects/BalanceAdjustmentCountAggregateInput.schema';
import { BalanceAdjustmentMinAggregateInputObjectSchema as BalanceAdjustmentMinAggregateInputObjectSchema } from './objects/BalanceAdjustmentMinAggregateInput.schema';
import { BalanceAdjustmentMaxAggregateInputObjectSchema as BalanceAdjustmentMaxAggregateInputObjectSchema } from './objects/BalanceAdjustmentMaxAggregateInput.schema';
import { BalanceAdjustmentAvgAggregateInputObjectSchema as BalanceAdjustmentAvgAggregateInputObjectSchema } from './objects/BalanceAdjustmentAvgAggregateInput.schema';
import { BalanceAdjustmentSumAggregateInputObjectSchema as BalanceAdjustmentSumAggregateInputObjectSchema } from './objects/BalanceAdjustmentSumAggregateInput.schema';

export const BalanceAdjustmentAggregateSchema: z.ZodType<Prisma.BalanceAdjustmentAggregateArgs> = z.object({ orderBy: z.union([BalanceAdjustmentOrderByWithRelationInputObjectSchema, BalanceAdjustmentOrderByWithRelationInputObjectSchema.array()]).optional(), where: BalanceAdjustmentWhereInputObjectSchema.optional(), cursor: BalanceAdjustmentWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), BalanceAdjustmentCountAggregateInputObjectSchema ]).optional(), _min: BalanceAdjustmentMinAggregateInputObjectSchema.optional(), _max: BalanceAdjustmentMaxAggregateInputObjectSchema.optional(), _avg: BalanceAdjustmentAvgAggregateInputObjectSchema.optional(), _sum: BalanceAdjustmentSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.BalanceAdjustmentAggregateArgs>;

export const BalanceAdjustmentAggregateZodSchema = z.object({ orderBy: z.union([BalanceAdjustmentOrderByWithRelationInputObjectSchema, BalanceAdjustmentOrderByWithRelationInputObjectSchema.array()]).optional(), where: BalanceAdjustmentWhereInputObjectSchema.optional(), cursor: BalanceAdjustmentWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), BalanceAdjustmentCountAggregateInputObjectSchema ]).optional(), _min: BalanceAdjustmentMinAggregateInputObjectSchema.optional(), _max: BalanceAdjustmentMaxAggregateInputObjectSchema.optional(), _avg: BalanceAdjustmentAvgAggregateInputObjectSchema.optional(), _sum: BalanceAdjustmentSumAggregateInputObjectSchema.optional() }).strict();