import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { LanguageDictionaryOrderByWithRelationInputObjectSchema as LanguageDictionaryOrderByWithRelationInputObjectSchema } from './objects/LanguageDictionaryOrderByWithRelationInput.schema';
import { LanguageDictionaryWhereInputObjectSchema as LanguageDictionaryWhereInputObjectSchema } from './objects/LanguageDictionaryWhereInput.schema';
import { LanguageDictionaryWhereUniqueInputObjectSchema as LanguageDictionaryWhereUniqueInputObjectSchema } from './objects/LanguageDictionaryWhereUniqueInput.schema';
import { LanguageDictionaryCountAggregateInputObjectSchema as LanguageDictionaryCountAggregateInputObjectSchema } from './objects/LanguageDictionaryCountAggregateInput.schema';
import { LanguageDictionaryMinAggregateInputObjectSchema as LanguageDictionaryMinAggregateInputObjectSchema } from './objects/LanguageDictionaryMinAggregateInput.schema';
import { LanguageDictionaryMaxAggregateInputObjectSchema as LanguageDictionaryMaxAggregateInputObjectSchema } from './objects/LanguageDictionaryMaxAggregateInput.schema';
import { LanguageDictionaryAvgAggregateInputObjectSchema as LanguageDictionaryAvgAggregateInputObjectSchema } from './objects/LanguageDictionaryAvgAggregateInput.schema';
import { LanguageDictionarySumAggregateInputObjectSchema as LanguageDictionarySumAggregateInputObjectSchema } from './objects/LanguageDictionarySumAggregateInput.schema';

export const LanguageDictionaryAggregateSchema: z.ZodType<Prisma.LanguageDictionaryAggregateArgs> = z.object({ orderBy: z.union([LanguageDictionaryOrderByWithRelationInputObjectSchema, LanguageDictionaryOrderByWithRelationInputObjectSchema.array()]).optional(), where: LanguageDictionaryWhereInputObjectSchema.optional(), cursor: LanguageDictionaryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), LanguageDictionaryCountAggregateInputObjectSchema ]).optional(), _min: LanguageDictionaryMinAggregateInputObjectSchema.optional(), _max: LanguageDictionaryMaxAggregateInputObjectSchema.optional(), _avg: LanguageDictionaryAvgAggregateInputObjectSchema.optional(), _sum: LanguageDictionarySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.LanguageDictionaryAggregateArgs>;

export const LanguageDictionaryAggregateZodSchema = z.object({ orderBy: z.union([LanguageDictionaryOrderByWithRelationInputObjectSchema, LanguageDictionaryOrderByWithRelationInputObjectSchema.array()]).optional(), where: LanguageDictionaryWhereInputObjectSchema.optional(), cursor: LanguageDictionaryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), LanguageDictionaryCountAggregateInputObjectSchema ]).optional(), _min: LanguageDictionaryMinAggregateInputObjectSchema.optional(), _max: LanguageDictionaryMaxAggregateInputObjectSchema.optional(), _avg: LanguageDictionaryAvgAggregateInputObjectSchema.optional(), _sum: LanguageDictionarySumAggregateInputObjectSchema.optional() }).strict();