import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaxResidenceCertOrderByWithRelationInputObjectSchema as TaxResidenceCertOrderByWithRelationInputObjectSchema } from './objects/TaxResidenceCertOrderByWithRelationInput.schema';
import { TaxResidenceCertWhereInputObjectSchema as TaxResidenceCertWhereInputObjectSchema } from './objects/TaxResidenceCertWhereInput.schema';
import { TaxResidenceCertWhereUniqueInputObjectSchema as TaxResidenceCertWhereUniqueInputObjectSchema } from './objects/TaxResidenceCertWhereUniqueInput.schema';
import { TaxResidenceCertCountAggregateInputObjectSchema as TaxResidenceCertCountAggregateInputObjectSchema } from './objects/TaxResidenceCertCountAggregateInput.schema';
import { TaxResidenceCertMinAggregateInputObjectSchema as TaxResidenceCertMinAggregateInputObjectSchema } from './objects/TaxResidenceCertMinAggregateInput.schema';
import { TaxResidenceCertMaxAggregateInputObjectSchema as TaxResidenceCertMaxAggregateInputObjectSchema } from './objects/TaxResidenceCertMaxAggregateInput.schema';
import { TaxResidenceCertAvgAggregateInputObjectSchema as TaxResidenceCertAvgAggregateInputObjectSchema } from './objects/TaxResidenceCertAvgAggregateInput.schema';
import { TaxResidenceCertSumAggregateInputObjectSchema as TaxResidenceCertSumAggregateInputObjectSchema } from './objects/TaxResidenceCertSumAggregateInput.schema';

export const TaxResidenceCertAggregateSchema: z.ZodType<Prisma.TaxResidenceCertAggregateArgs> = z.object({ orderBy: z.union([TaxResidenceCertOrderByWithRelationInputObjectSchema, TaxResidenceCertOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaxResidenceCertWhereInputObjectSchema.optional(), cursor: TaxResidenceCertWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaxResidenceCertCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceCertMinAggregateInputObjectSchema.optional(), _max: TaxResidenceCertMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceCertAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceCertSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaxResidenceCertAggregateArgs>;

export const TaxResidenceCertAggregateZodSchema = z.object({ orderBy: z.union([TaxResidenceCertOrderByWithRelationInputObjectSchema, TaxResidenceCertOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaxResidenceCertWhereInputObjectSchema.optional(), cursor: TaxResidenceCertWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaxResidenceCertCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceCertMinAggregateInputObjectSchema.optional(), _max: TaxResidenceCertMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceCertAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceCertSumAggregateInputObjectSchema.optional() }).strict();