import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictDistributionTypeOrderByWithRelationInputObjectSchema as dictDistributionTypeOrderByWithRelationInputObjectSchema } from './objects/dictDistributionTypeOrderByWithRelationInput.schema';
import { dictDistributionTypeWhereInputObjectSchema as dictDistributionTypeWhereInputObjectSchema } from './objects/dictDistributionTypeWhereInput.schema';
import { dictDistributionTypeWhereUniqueInputObjectSchema as dictDistributionTypeWhereUniqueInputObjectSchema } from './objects/dictDistributionTypeWhereUniqueInput.schema';
import { DictDistributionTypeCountAggregateInputObjectSchema as DictDistributionTypeCountAggregateInputObjectSchema } from './objects/DictDistributionTypeCountAggregateInput.schema';
import { DictDistributionTypeMinAggregateInputObjectSchema as DictDistributionTypeMinAggregateInputObjectSchema } from './objects/DictDistributionTypeMinAggregateInput.schema';
import { DictDistributionTypeMaxAggregateInputObjectSchema as DictDistributionTypeMaxAggregateInputObjectSchema } from './objects/DictDistributionTypeMaxAggregateInput.schema';
import { DictDistributionTypeAvgAggregateInputObjectSchema as DictDistributionTypeAvgAggregateInputObjectSchema } from './objects/DictDistributionTypeAvgAggregateInput.schema';
import { DictDistributionTypeSumAggregateInputObjectSchema as DictDistributionTypeSumAggregateInputObjectSchema } from './objects/DictDistributionTypeSumAggregateInput.schema';

export const dictDistributionTypeAggregateSchema: z.ZodType<Prisma.dictDistributionTypeAggregateArgs> = z.object({ orderBy: z.union([dictDistributionTypeOrderByWithRelationInputObjectSchema, dictDistributionTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictDistributionTypeWhereInputObjectSchema.optional(), cursor: dictDistributionTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictDistributionTypeCountAggregateInputObjectSchema ]).optional(), _min: DictDistributionTypeMinAggregateInputObjectSchema.optional(), _max: DictDistributionTypeMaxAggregateInputObjectSchema.optional(), _avg: DictDistributionTypeAvgAggregateInputObjectSchema.optional(), _sum: DictDistributionTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictDistributionTypeAggregateArgs>;

export const dictDistributionTypeAggregateZodSchema = z.object({ orderBy: z.union([dictDistributionTypeOrderByWithRelationInputObjectSchema, dictDistributionTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictDistributionTypeWhereInputObjectSchema.optional(), cursor: dictDistributionTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictDistributionTypeCountAggregateInputObjectSchema ]).optional(), _min: DictDistributionTypeMinAggregateInputObjectSchema.optional(), _max: DictDistributionTypeMaxAggregateInputObjectSchema.optional(), _avg: DictDistributionTypeAvgAggregateInputObjectSchema.optional(), _sum: DictDistributionTypeSumAggregateInputObjectSchema.optional() }).strict();