import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema as dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonOrderByWithRelationInput.schema';
import { dictAdvWithoutInvExcludeReasonWhereInputObjectSchema as dictAdvWithoutInvExcludeReasonWhereInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonWhereInput.schema';
import { dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema as dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonWhereUniqueInput.schema';
import { DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonCountAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonMinAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonMaxAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonAvgAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonSumAggregateInput.schema';

export const dictAdvWithoutInvExcludeReasonAggregateSchema: z.ZodType<Prisma.dictAdvWithoutInvExcludeReasonAggregateArgs> = z.object({ orderBy: z.union([dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema, dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictAdvWithoutInvExcludeReasonWhereInputObjectSchema.optional(), cursor: dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictAdvWithoutInvExcludeReasonAggregateArgs>;

export const dictAdvWithoutInvExcludeReasonAggregateZodSchema = z.object({ orderBy: z.union([dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema, dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictAdvWithoutInvExcludeReasonWhereInputObjectSchema.optional(), cursor: dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema.optional() }).strict();