import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AgreementRoyRateOrderByWithRelationInputObjectSchema as AgreementRoyRateOrderByWithRelationInputObjectSchema } from './objects/AgreementRoyRateOrderByWithRelationInput.schema';
import { AgreementRoyRateWhereInputObjectSchema as AgreementRoyRateWhereInputObjectSchema } from './objects/AgreementRoyRateWhereInput.schema';
import { AgreementRoyRateWhereUniqueInputObjectSchema as AgreementRoyRateWhereUniqueInputObjectSchema } from './objects/AgreementRoyRateWhereUniqueInput.schema';
import { AgreementRoyRateCountAggregateInputObjectSchema as AgreementRoyRateCountAggregateInputObjectSchema } from './objects/AgreementRoyRateCountAggregateInput.schema';
import { AgreementRoyRateMinAggregateInputObjectSchema as AgreementRoyRateMinAggregateInputObjectSchema } from './objects/AgreementRoyRateMinAggregateInput.schema';
import { AgreementRoyRateMaxAggregateInputObjectSchema as AgreementRoyRateMaxAggregateInputObjectSchema } from './objects/AgreementRoyRateMaxAggregateInput.schema';
import { AgreementRoyRateAvgAggregateInputObjectSchema as AgreementRoyRateAvgAggregateInputObjectSchema } from './objects/AgreementRoyRateAvgAggregateInput.schema';
import { AgreementRoyRateSumAggregateInputObjectSchema as AgreementRoyRateSumAggregateInputObjectSchema } from './objects/AgreementRoyRateSumAggregateInput.schema';

export const AgreementRoyRateAggregateSchema: z.ZodType<Prisma.AgreementRoyRateAggregateArgs> = z.object({ orderBy: z.union([AgreementRoyRateOrderByWithRelationInputObjectSchema, AgreementRoyRateOrderByWithRelationInputObjectSchema.array()]).optional(), where: AgreementRoyRateWhereInputObjectSchema.optional(), cursor: AgreementRoyRateWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AgreementRoyRateCountAggregateInputObjectSchema ]).optional(), _min: AgreementRoyRateMinAggregateInputObjectSchema.optional(), _max: AgreementRoyRateMaxAggregateInputObjectSchema.optional(), _avg: AgreementRoyRateAvgAggregateInputObjectSchema.optional(), _sum: AgreementRoyRateSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgreementRoyRateAggregateArgs>;

export const AgreementRoyRateAggregateZodSchema = z.object({ orderBy: z.union([AgreementRoyRateOrderByWithRelationInputObjectSchema, AgreementRoyRateOrderByWithRelationInputObjectSchema.array()]).optional(), where: AgreementRoyRateWhereInputObjectSchema.optional(), cursor: AgreementRoyRateWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AgreementRoyRateCountAggregateInputObjectSchema ]).optional(), _min: AgreementRoyRateMinAggregateInputObjectSchema.optional(), _max: AgreementRoyRateMaxAggregateInputObjectSchema.optional(), _avg: AgreementRoyRateAvgAggregateInputObjectSchema.optional(), _sum: AgreementRoyRateSumAggregateInputObjectSchema.optional() }).strict();