import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArTransferDetailOrderByWithRelationInputObjectSchema as ArTransferDetailOrderByWithRelationInputObjectSchema } from './objects/ArTransferDetailOrderByWithRelationInput.schema';
import { ArTransferDetailWhereInputObjectSchema as ArTransferDetailWhereInputObjectSchema } from './objects/ArTransferDetailWhereInput.schema';
import { ArTransferDetailWhereUniqueInputObjectSchema as ArTransferDetailWhereUniqueInputObjectSchema } from './objects/ArTransferDetailWhereUniqueInput.schema';
import { ArTransferDetailCountAggregateInputObjectSchema as ArTransferDetailCountAggregateInputObjectSchema } from './objects/ArTransferDetailCountAggregateInput.schema';
import { ArTransferDetailMinAggregateInputObjectSchema as ArTransferDetailMinAggregateInputObjectSchema } from './objects/ArTransferDetailMinAggregateInput.schema';
import { ArTransferDetailMaxAggregateInputObjectSchema as ArTransferDetailMaxAggregateInputObjectSchema } from './objects/ArTransferDetailMaxAggregateInput.schema';
import { ArTransferDetailAvgAggregateInputObjectSchema as ArTransferDetailAvgAggregateInputObjectSchema } from './objects/ArTransferDetailAvgAggregateInput.schema';
import { ArTransferDetailSumAggregateInputObjectSchema as ArTransferDetailSumAggregateInputObjectSchema } from './objects/ArTransferDetailSumAggregateInput.schema';

export const ArTransferDetailAggregateSchema: z.ZodType<Prisma.ArTransferDetailAggregateArgs> = z.object({ orderBy: z.union([ArTransferDetailOrderByWithRelationInputObjectSchema, ArTransferDetailOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArTransferDetailWhereInputObjectSchema.optional(), cursor: ArTransferDetailWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArTransferDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransferDetailMinAggregateInputObjectSchema.optional(), _max: ArTransferDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransferDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransferDetailSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArTransferDetailAggregateArgs>;

export const ArTransferDetailAggregateZodSchema = z.object({ orderBy: z.union([ArTransferDetailOrderByWithRelationInputObjectSchema, ArTransferDetailOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArTransferDetailWhereInputObjectSchema.optional(), cursor: ArTransferDetailWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArTransferDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransferDetailMinAggregateInputObjectSchema.optional(), _max: ArTransferDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransferDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransferDetailSumAggregateInputObjectSchema.optional() }).strict();