import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblInvoiceDetailsOrderByWithRelationInputObjectSchema as tblInvoiceDetailsOrderByWithRelationInputObjectSchema } from './objects/tblInvoiceDetailsOrderByWithRelationInput.schema';
import { tblInvoiceDetailsWhereInputObjectSchema as tblInvoiceDetailsWhereInputObjectSchema } from './objects/tblInvoiceDetailsWhereInput.schema';
import { tblInvoiceDetailsWhereUniqueInputObjectSchema as tblInvoiceDetailsWhereUniqueInputObjectSchema } from './objects/tblInvoiceDetailsWhereUniqueInput.schema';
import { TblInvoiceDetailsCountAggregateInputObjectSchema as TblInvoiceDetailsCountAggregateInputObjectSchema } from './objects/TblInvoiceDetailsCountAggregateInput.schema';
import { TblInvoiceDetailsMinAggregateInputObjectSchema as TblInvoiceDetailsMinAggregateInputObjectSchema } from './objects/TblInvoiceDetailsMinAggregateInput.schema';
import { TblInvoiceDetailsMaxAggregateInputObjectSchema as TblInvoiceDetailsMaxAggregateInputObjectSchema } from './objects/TblInvoiceDetailsMaxAggregateInput.schema';
import { TblInvoiceDetailsAvgAggregateInputObjectSchema as TblInvoiceDetailsAvgAggregateInputObjectSchema } from './objects/TblInvoiceDetailsAvgAggregateInput.schema';
import { TblInvoiceDetailsSumAggregateInputObjectSchema as TblInvoiceDetailsSumAggregateInputObjectSchema } from './objects/TblInvoiceDetailsSumAggregateInput.schema';

export const tblInvoiceDetailsAggregateSchema: z.ZodType<Prisma.tblInvoiceDetailsAggregateArgs> = z.object({ orderBy: z.union([tblInvoiceDetailsOrderByWithRelationInputObjectSchema, tblInvoiceDetailsOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblInvoiceDetailsWhereInputObjectSchema.optional(), cursor: tblInvoiceDetailsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblInvoiceDetailsCountAggregateInputObjectSchema ]).optional(), _min: TblInvoiceDetailsMinAggregateInputObjectSchema.optional(), _max: TblInvoiceDetailsMaxAggregateInputObjectSchema.optional(), _avg: TblInvoiceDetailsAvgAggregateInputObjectSchema.optional(), _sum: TblInvoiceDetailsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblInvoiceDetailsAggregateArgs>;

export const tblInvoiceDetailsAggregateZodSchema = z.object({ orderBy: z.union([tblInvoiceDetailsOrderByWithRelationInputObjectSchema, tblInvoiceDetailsOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblInvoiceDetailsWhereInputObjectSchema.optional(), cursor: tblInvoiceDetailsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblInvoiceDetailsCountAggregateInputObjectSchema ]).optional(), _min: TblInvoiceDetailsMinAggregateInputObjectSchema.optional(), _max: TblInvoiceDetailsMaxAggregateInputObjectSchema.optional(), _avg: TblInvoiceDetailsAvgAggregateInputObjectSchema.optional(), _sum: TblInvoiceDetailsSumAggregateInputObjectSchema.optional() }).strict();