import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CurrencyDictionaryOrderByWithRelationInputObjectSchema as CurrencyDictionaryOrderByWithRelationInputObjectSchema } from './objects/CurrencyDictionaryOrderByWithRelationInput.schema';
import { CurrencyDictionaryWhereInputObjectSchema as CurrencyDictionaryWhereInputObjectSchema } from './objects/CurrencyDictionaryWhereInput.schema';
import { CurrencyDictionaryWhereUniqueInputObjectSchema as CurrencyDictionaryWhereUniqueInputObjectSchema } from './objects/CurrencyDictionaryWhereUniqueInput.schema';
import { CurrencyDictionaryCountAggregateInputObjectSchema as CurrencyDictionaryCountAggregateInputObjectSchema } from './objects/CurrencyDictionaryCountAggregateInput.schema';
import { CurrencyDictionaryMinAggregateInputObjectSchema as CurrencyDictionaryMinAggregateInputObjectSchema } from './objects/CurrencyDictionaryMinAggregateInput.schema';
import { CurrencyDictionaryMaxAggregateInputObjectSchema as CurrencyDictionaryMaxAggregateInputObjectSchema } from './objects/CurrencyDictionaryMaxAggregateInput.schema';
import { CurrencyDictionaryAvgAggregateInputObjectSchema as CurrencyDictionaryAvgAggregateInputObjectSchema } from './objects/CurrencyDictionaryAvgAggregateInput.schema';
import { CurrencyDictionarySumAggregateInputObjectSchema as CurrencyDictionarySumAggregateInputObjectSchema } from './objects/CurrencyDictionarySumAggregateInput.schema';

export const CurrencyDictionaryAggregateSchema: z.ZodType<Prisma.CurrencyDictionaryAggregateArgs> = z.object({ orderBy: z.union([CurrencyDictionaryOrderByWithRelationInputObjectSchema, CurrencyDictionaryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CurrencyDictionaryWhereInputObjectSchema.optional(), cursor: CurrencyDictionaryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CurrencyDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CurrencyDictionaryMinAggregateInputObjectSchema.optional(), _max: CurrencyDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CurrencyDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CurrencyDictionarySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CurrencyDictionaryAggregateArgs>;

export const CurrencyDictionaryAggregateZodSchema = z.object({ orderBy: z.union([CurrencyDictionaryOrderByWithRelationInputObjectSchema, CurrencyDictionaryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CurrencyDictionaryWhereInputObjectSchema.optional(), cursor: CurrencyDictionaryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CurrencyDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CurrencyDictionaryMinAggregateInputObjectSchema.optional(), _max: CurrencyDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CurrencyDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CurrencyDictionarySumAggregateInputObjectSchema.optional() }).strict();