import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictMissRoyExcludeReasonOrderByWithRelationInputObjectSchema as dictMissRoyExcludeReasonOrderByWithRelationInputObjectSchema } from './objects/dictMissRoyExcludeReasonOrderByWithRelationInput.schema';
import { dictMissRoyExcludeReasonWhereInputObjectSchema as dictMissRoyExcludeReasonWhereInputObjectSchema } from './objects/dictMissRoyExcludeReasonWhereInput.schema';
import { dictMissRoyExcludeReasonWhereUniqueInputObjectSchema as dictMissRoyExcludeReasonWhereUniqueInputObjectSchema } from './objects/dictMissRoyExcludeReasonWhereUniqueInput.schema';
import { DictMissRoyExcludeReasonCountAggregateInputObjectSchema as DictMissRoyExcludeReasonCountAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonCountAggregateInput.schema';
import { DictMissRoyExcludeReasonMinAggregateInputObjectSchema as DictMissRoyExcludeReasonMinAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonMinAggregateInput.schema';
import { DictMissRoyExcludeReasonMaxAggregateInputObjectSchema as DictMissRoyExcludeReasonMaxAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonMaxAggregateInput.schema';
import { DictMissRoyExcludeReasonAvgAggregateInputObjectSchema as DictMissRoyExcludeReasonAvgAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonAvgAggregateInput.schema';
import { DictMissRoyExcludeReasonSumAggregateInputObjectSchema as DictMissRoyExcludeReasonSumAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonSumAggregateInput.schema';

export const dictMissRoyExcludeReasonAggregateSchema: z.ZodType<Prisma.dictMissRoyExcludeReasonAggregateArgs> = z.object({ orderBy: z.union([dictMissRoyExcludeReasonOrderByWithRelationInputObjectSchema, dictMissRoyExcludeReasonOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictMissRoyExcludeReasonWhereInputObjectSchema.optional(), cursor: dictMissRoyExcludeReasonWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictMissRoyExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictMissRoyExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictMissRoyExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictMissRoyExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictMissRoyExcludeReasonSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictMissRoyExcludeReasonAggregateArgs>;

export const dictMissRoyExcludeReasonAggregateZodSchema = z.object({ orderBy: z.union([dictMissRoyExcludeReasonOrderByWithRelationInputObjectSchema, dictMissRoyExcludeReasonOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictMissRoyExcludeReasonWhereInputObjectSchema.optional(), cursor: dictMissRoyExcludeReasonWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictMissRoyExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictMissRoyExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictMissRoyExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictMissRoyExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictMissRoyExcludeReasonSumAggregateInputObjectSchema.optional() }).strict();