import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictRoyAccountIntervalOrderByWithRelationInputObjectSchema as dictRoyAccountIntervalOrderByWithRelationInputObjectSchema } from './objects/dictRoyAccountIntervalOrderByWithRelationInput.schema';
import { dictRoyAccountIntervalWhereInputObjectSchema as dictRoyAccountIntervalWhereInputObjectSchema } from './objects/dictRoyAccountIntervalWhereInput.schema';
import { dictRoyAccountIntervalWhereUniqueInputObjectSchema as dictRoyAccountIntervalWhereUniqueInputObjectSchema } from './objects/dictRoyAccountIntervalWhereUniqueInput.schema';
import { DictRoyAccountIntervalCountAggregateInputObjectSchema as DictRoyAccountIntervalCountAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalCountAggregateInput.schema';
import { DictRoyAccountIntervalMinAggregateInputObjectSchema as DictRoyAccountIntervalMinAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalMinAggregateInput.schema';
import { DictRoyAccountIntervalMaxAggregateInputObjectSchema as DictRoyAccountIntervalMaxAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalMaxAggregateInput.schema';
import { DictRoyAccountIntervalAvgAggregateInputObjectSchema as DictRoyAccountIntervalAvgAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalAvgAggregateInput.schema';
import { DictRoyAccountIntervalSumAggregateInputObjectSchema as DictRoyAccountIntervalSumAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalSumAggregateInput.schema';

export const dictRoyAccountIntervalAggregateSchema: z.ZodType<Prisma.dictRoyAccountIntervalAggregateArgs> = z.object({ orderBy: z.union([dictRoyAccountIntervalOrderByWithRelationInputObjectSchema, dictRoyAccountIntervalOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictRoyAccountIntervalWhereInputObjectSchema.optional(), cursor: dictRoyAccountIntervalWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictRoyAccountIntervalCountAggregateInputObjectSchema ]).optional(), _min: DictRoyAccountIntervalMinAggregateInputObjectSchema.optional(), _max: DictRoyAccountIntervalMaxAggregateInputObjectSchema.optional(), _avg: DictRoyAccountIntervalAvgAggregateInputObjectSchema.optional(), _sum: DictRoyAccountIntervalSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictRoyAccountIntervalAggregateArgs>;

export const dictRoyAccountIntervalAggregateZodSchema = z.object({ orderBy: z.union([dictRoyAccountIntervalOrderByWithRelationInputObjectSchema, dictRoyAccountIntervalOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictRoyAccountIntervalWhereInputObjectSchema.optional(), cursor: dictRoyAccountIntervalWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictRoyAccountIntervalCountAggregateInputObjectSchema ]).optional(), _min: DictRoyAccountIntervalMinAggregateInputObjectSchema.optional(), _max: DictRoyAccountIntervalMaxAggregateInputObjectSchema.optional(), _avg: DictRoyAccountIntervalAvgAggregateInputObjectSchema.optional(), _sum: DictRoyAccountIntervalSumAggregateInputObjectSchema.optional() }).strict();