import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblPersonContractTypeOrderByWithRelationInputObjectSchema as tblPersonContractTypeOrderByWithRelationInputObjectSchema } from './objects/tblPersonContractTypeOrderByWithRelationInput.schema';
import { tblPersonContractTypeWhereInputObjectSchema as tblPersonContractTypeWhereInputObjectSchema } from './objects/tblPersonContractTypeWhereInput.schema';
import { tblPersonContractTypeWhereUniqueInputObjectSchema as tblPersonContractTypeWhereUniqueInputObjectSchema } from './objects/tblPersonContractTypeWhereUniqueInput.schema';
import { TblPersonContractTypeCountAggregateInputObjectSchema as TblPersonContractTypeCountAggregateInputObjectSchema } from './objects/TblPersonContractTypeCountAggregateInput.schema';
import { TblPersonContractTypeMinAggregateInputObjectSchema as TblPersonContractTypeMinAggregateInputObjectSchema } from './objects/TblPersonContractTypeMinAggregateInput.schema';
import { TblPersonContractTypeMaxAggregateInputObjectSchema as TblPersonContractTypeMaxAggregateInputObjectSchema } from './objects/TblPersonContractTypeMaxAggregateInput.schema';
import { TblPersonContractTypeAvgAggregateInputObjectSchema as TblPersonContractTypeAvgAggregateInputObjectSchema } from './objects/TblPersonContractTypeAvgAggregateInput.schema';
import { TblPersonContractTypeSumAggregateInputObjectSchema as TblPersonContractTypeSumAggregateInputObjectSchema } from './objects/TblPersonContractTypeSumAggregateInput.schema';

export const tblPersonContractTypeAggregateSchema: z.ZodType<Prisma.tblPersonContractTypeAggregateArgs> = z.object({ orderBy: z.union([tblPersonContractTypeOrderByWithRelationInputObjectSchema, tblPersonContractTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblPersonContractTypeWhereInputObjectSchema.optional(), cursor: tblPersonContractTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblPersonContractTypeCountAggregateInputObjectSchema ]).optional(), _min: TblPersonContractTypeMinAggregateInputObjectSchema.optional(), _max: TblPersonContractTypeMaxAggregateInputObjectSchema.optional(), _avg: TblPersonContractTypeAvgAggregateInputObjectSchema.optional(), _sum: TblPersonContractTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblPersonContractTypeAggregateArgs>;

export const tblPersonContractTypeAggregateZodSchema = z.object({ orderBy: z.union([tblPersonContractTypeOrderByWithRelationInputObjectSchema, tblPersonContractTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblPersonContractTypeWhereInputObjectSchema.optional(), cursor: tblPersonContractTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblPersonContractTypeCountAggregateInputObjectSchema ]).optional(), _min: TblPersonContractTypeMinAggregateInputObjectSchema.optional(), _max: TblPersonContractTypeMaxAggregateInputObjectSchema.optional(), _avg: TblPersonContractTypeAvgAggregateInputObjectSchema.optional(), _sum: TblPersonContractTypeSumAggregateInputObjectSchema.optional() }).strict();