import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblTaxResidenceCertificateOrderByWithRelationInputObjectSchema as tblTaxResidenceCertificateOrderByWithRelationInputObjectSchema } from './objects/tblTaxResidenceCertificateOrderByWithRelationInput.schema';
import { tblTaxResidenceCertificateWhereInputObjectSchema as tblTaxResidenceCertificateWhereInputObjectSchema } from './objects/tblTaxResidenceCertificateWhereInput.schema';
import { tblTaxResidenceCertificateWhereUniqueInputObjectSchema as tblTaxResidenceCertificateWhereUniqueInputObjectSchema } from './objects/tblTaxResidenceCertificateWhereUniqueInput.schema';
import { TblTaxResidenceCertificateCountAggregateInputObjectSchema as TblTaxResidenceCertificateCountAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateCountAggregateInput.schema';
import { TblTaxResidenceCertificateMinAggregateInputObjectSchema as TblTaxResidenceCertificateMinAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateMinAggregateInput.schema';
import { TblTaxResidenceCertificateMaxAggregateInputObjectSchema as TblTaxResidenceCertificateMaxAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateMaxAggregateInput.schema';
import { TblTaxResidenceCertificateAvgAggregateInputObjectSchema as TblTaxResidenceCertificateAvgAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateAvgAggregateInput.schema';
import { TblTaxResidenceCertificateSumAggregateInputObjectSchema as TblTaxResidenceCertificateSumAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateSumAggregateInput.schema';

export const tblTaxResidenceCertificateAggregateSchema: z.ZodType<Prisma.tblTaxResidenceCertificateAggregateArgs> = z.object({ orderBy: z.union([tblTaxResidenceCertificateOrderByWithRelationInputObjectSchema, tblTaxResidenceCertificateOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblTaxResidenceCertificateWhereInputObjectSchema.optional(), cursor: tblTaxResidenceCertificateWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblTaxResidenceCertificateCountAggregateInputObjectSchema ]).optional(), _min: TblTaxResidenceCertificateMinAggregateInputObjectSchema.optional(), _max: TblTaxResidenceCertificateMaxAggregateInputObjectSchema.optional(), _avg: TblTaxResidenceCertificateAvgAggregateInputObjectSchema.optional(), _sum: TblTaxResidenceCertificateSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblTaxResidenceCertificateAggregateArgs>;

export const tblTaxResidenceCertificateAggregateZodSchema = z.object({ orderBy: z.union([tblTaxResidenceCertificateOrderByWithRelationInputObjectSchema, tblTaxResidenceCertificateOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblTaxResidenceCertificateWhereInputObjectSchema.optional(), cursor: tblTaxResidenceCertificateWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblTaxResidenceCertificateCountAggregateInputObjectSchema ]).optional(), _min: TblTaxResidenceCertificateMinAggregateInputObjectSchema.optional(), _max: TblTaxResidenceCertificateMaxAggregateInputObjectSchema.optional(), _avg: TblTaxResidenceCertificateAvgAggregateInputObjectSchema.optional(), _sum: TblTaxResidenceCertificateSumAggregateInputObjectSchema.optional() }).strict();