import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PublisherContactOrderByWithRelationInputObjectSchema as PublisherContactOrderByWithRelationInputObjectSchema } from './objects/PublisherContactOrderByWithRelationInput.schema';
import { PublisherContactWhereInputObjectSchema as PublisherContactWhereInputObjectSchema } from './objects/PublisherContactWhereInput.schema';
import { PublisherContactWhereUniqueInputObjectSchema as PublisherContactWhereUniqueInputObjectSchema } from './objects/PublisherContactWhereUniqueInput.schema';
import { PublisherContactCountAggregateInputObjectSchema as PublisherContactCountAggregateInputObjectSchema } from './objects/PublisherContactCountAggregateInput.schema';
import { PublisherContactMinAggregateInputObjectSchema as PublisherContactMinAggregateInputObjectSchema } from './objects/PublisherContactMinAggregateInput.schema';
import { PublisherContactMaxAggregateInputObjectSchema as PublisherContactMaxAggregateInputObjectSchema } from './objects/PublisherContactMaxAggregateInput.schema';
import { PublisherContactAvgAggregateInputObjectSchema as PublisherContactAvgAggregateInputObjectSchema } from './objects/PublisherContactAvgAggregateInput.schema';
import { PublisherContactSumAggregateInputObjectSchema as PublisherContactSumAggregateInputObjectSchema } from './objects/PublisherContactSumAggregateInput.schema';

export const PublisherContactAggregateSchema: z.ZodType<Prisma.PublisherContactAggregateArgs> = z.object({ orderBy: z.union([PublisherContactOrderByWithRelationInputObjectSchema, PublisherContactOrderByWithRelationInputObjectSchema.array()]).optional(), where: PublisherContactWhereInputObjectSchema.optional(), cursor: PublisherContactWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PublisherContactCountAggregateInputObjectSchema ]).optional(), _min: PublisherContactMinAggregateInputObjectSchema.optional(), _max: PublisherContactMaxAggregateInputObjectSchema.optional(), _avg: PublisherContactAvgAggregateInputObjectSchema.optional(), _sum: PublisherContactSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PublisherContactAggregateArgs>;

export const PublisherContactAggregateZodSchema = z.object({ orderBy: z.union([PublisherContactOrderByWithRelationInputObjectSchema, PublisherContactOrderByWithRelationInputObjectSchema.array()]).optional(), where: PublisherContactWhereInputObjectSchema.optional(), cursor: PublisherContactWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PublisherContactCountAggregateInputObjectSchema ]).optional(), _min: PublisherContactMinAggregateInputObjectSchema.optional(), _max: PublisherContactMaxAggregateInputObjectSchema.optional(), _avg: PublisherContactAvgAggregateInputObjectSchema.optional(), _sum: PublisherContactSumAggregateInputObjectSchema.optional() }).strict();