import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblAgreementsOrderByWithRelationInputObjectSchema as tblAgreementsOrderByWithRelationInputObjectSchema } from './objects/tblAgreementsOrderByWithRelationInput.schema';
import { tblAgreementsWhereInputObjectSchema as tblAgreementsWhereInputObjectSchema } from './objects/tblAgreementsWhereInput.schema';
import { tblAgreementsWhereUniqueInputObjectSchema as tblAgreementsWhereUniqueInputObjectSchema } from './objects/tblAgreementsWhereUniqueInput.schema';
import { TblAgreementsCountAggregateInputObjectSchema as TblAgreementsCountAggregateInputObjectSchema } from './objects/TblAgreementsCountAggregateInput.schema';
import { TblAgreementsMinAggregateInputObjectSchema as TblAgreementsMinAggregateInputObjectSchema } from './objects/TblAgreementsMinAggregateInput.schema';
import { TblAgreementsMaxAggregateInputObjectSchema as TblAgreementsMaxAggregateInputObjectSchema } from './objects/TblAgreementsMaxAggregateInput.schema';
import { TblAgreementsAvgAggregateInputObjectSchema as TblAgreementsAvgAggregateInputObjectSchema } from './objects/TblAgreementsAvgAggregateInput.schema';
import { TblAgreementsSumAggregateInputObjectSchema as TblAgreementsSumAggregateInputObjectSchema } from './objects/TblAgreementsSumAggregateInput.schema';

export const tblAgreementsAggregateSchema: z.ZodType<Prisma.tblAgreementsAggregateArgs> = z.object({ orderBy: z.union([tblAgreementsOrderByWithRelationInputObjectSchema, tblAgreementsOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblAgreementsWhereInputObjectSchema.optional(), cursor: tblAgreementsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblAgreementsCountAggregateInputObjectSchema ]).optional(), _min: TblAgreementsMinAggregateInputObjectSchema.optional(), _max: TblAgreementsMaxAggregateInputObjectSchema.optional(), _avg: TblAgreementsAvgAggregateInputObjectSchema.optional(), _sum: TblAgreementsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblAgreementsAggregateArgs>;

export const tblAgreementsAggregateZodSchema = z.object({ orderBy: z.union([tblAgreementsOrderByWithRelationInputObjectSchema, tblAgreementsOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblAgreementsWhereInputObjectSchema.optional(), cursor: tblAgreementsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblAgreementsCountAggregateInputObjectSchema ]).optional(), _min: TblAgreementsMinAggregateInputObjectSchema.optional(), _max: TblAgreementsMaxAggregateInputObjectSchema.optional(), _avg: TblAgreementsAvgAggregateInputObjectSchema.optional(), _sum: TblAgreementsSumAggregateInputObjectSchema.optional() }).strict();