import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArDefaultAccountOrderByWithRelationInputObjectSchema as ArDefaultAccountOrderByWithRelationInputObjectSchema } from './objects/ArDefaultAccountOrderByWithRelationInput.schema';
import { ArDefaultAccountWhereInputObjectSchema as ArDefaultAccountWhereInputObjectSchema } from './objects/ArDefaultAccountWhereInput.schema';
import { ArDefaultAccountWhereUniqueInputObjectSchema as ArDefaultAccountWhereUniqueInputObjectSchema } from './objects/ArDefaultAccountWhereUniqueInput.schema';
import { ArDefaultAccountCountAggregateInputObjectSchema as ArDefaultAccountCountAggregateInputObjectSchema } from './objects/ArDefaultAccountCountAggregateInput.schema';
import { ArDefaultAccountMinAggregateInputObjectSchema as ArDefaultAccountMinAggregateInputObjectSchema } from './objects/ArDefaultAccountMinAggregateInput.schema';
import { ArDefaultAccountMaxAggregateInputObjectSchema as ArDefaultAccountMaxAggregateInputObjectSchema } from './objects/ArDefaultAccountMaxAggregateInput.schema';
import { ArDefaultAccountAvgAggregateInputObjectSchema as ArDefaultAccountAvgAggregateInputObjectSchema } from './objects/ArDefaultAccountAvgAggregateInput.schema';
import { ArDefaultAccountSumAggregateInputObjectSchema as ArDefaultAccountSumAggregateInputObjectSchema } from './objects/ArDefaultAccountSumAggregateInput.schema';

export const ArDefaultAccountAggregateSchema: z.ZodType<Prisma.ArDefaultAccountAggregateArgs> = z.object({ orderBy: z.union([ArDefaultAccountOrderByWithRelationInputObjectSchema, ArDefaultAccountOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArDefaultAccountWhereInputObjectSchema.optional(), cursor: ArDefaultAccountWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArDefaultAccountCountAggregateInputObjectSchema ]).optional(), _min: ArDefaultAccountMinAggregateInputObjectSchema.optional(), _max: ArDefaultAccountMaxAggregateInputObjectSchema.optional(), _avg: ArDefaultAccountAvgAggregateInputObjectSchema.optional(), _sum: ArDefaultAccountSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArDefaultAccountAggregateArgs>;

export const ArDefaultAccountAggregateZodSchema = z.object({ orderBy: z.union([ArDefaultAccountOrderByWithRelationInputObjectSchema, ArDefaultAccountOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArDefaultAccountWhereInputObjectSchema.optional(), cursor: ArDefaultAccountWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArDefaultAccountCountAggregateInputObjectSchema ]).optional(), _min: ArDefaultAccountMinAggregateInputObjectSchema.optional(), _max: ArDefaultAccountMaxAggregateInputObjectSchema.optional(), _avg: ArDefaultAccountAvgAggregateInputObjectSchema.optional(), _sum: ArDefaultAccountSumAggregateInputObjectSchema.optional() }).strict();