import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PearsonAdvAndRoyOrderByWithRelationInputObjectSchema as PearsonAdvAndRoyOrderByWithRelationInputObjectSchema } from './objects/PearsonAdvAndRoyOrderByWithRelationInput.schema';
import { PearsonAdvAndRoyWhereInputObjectSchema as PearsonAdvAndRoyWhereInputObjectSchema } from './objects/PearsonAdvAndRoyWhereInput.schema';
import { PearsonAdvAndRoyWhereUniqueInputObjectSchema as PearsonAdvAndRoyWhereUniqueInputObjectSchema } from './objects/PearsonAdvAndRoyWhereUniqueInput.schema';
import { PearsonAdvAndRoyCountAggregateInputObjectSchema as PearsonAdvAndRoyCountAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyCountAggregateInput.schema';
import { PearsonAdvAndRoyMinAggregateInputObjectSchema as PearsonAdvAndRoyMinAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyMinAggregateInput.schema';
import { PearsonAdvAndRoyMaxAggregateInputObjectSchema as PearsonAdvAndRoyMaxAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyMaxAggregateInput.schema';
import { PearsonAdvAndRoyAvgAggregateInputObjectSchema as PearsonAdvAndRoyAvgAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyAvgAggregateInput.schema';
import { PearsonAdvAndRoySumAggregateInputObjectSchema as PearsonAdvAndRoySumAggregateInputObjectSchema } from './objects/PearsonAdvAndRoySumAggregateInput.schema';

export const PearsonAdvAndRoyAggregateSchema: z.ZodType<Prisma.PearsonAdvAndRoyAggregateArgs> = z.object({ orderBy: z.union([PearsonAdvAndRoyOrderByWithRelationInputObjectSchema, PearsonAdvAndRoyOrderByWithRelationInputObjectSchema.array()]).optional(), where: PearsonAdvAndRoyWhereInputObjectSchema.optional(), cursor: PearsonAdvAndRoyWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PearsonAdvAndRoyCountAggregateInputObjectSchema ]).optional(), _min: PearsonAdvAndRoyMinAggregateInputObjectSchema.optional(), _max: PearsonAdvAndRoyMaxAggregateInputObjectSchema.optional(), _avg: PearsonAdvAndRoyAvgAggregateInputObjectSchema.optional(), _sum: PearsonAdvAndRoySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PearsonAdvAndRoyAggregateArgs>;

export const PearsonAdvAndRoyAggregateZodSchema = z.object({ orderBy: z.union([PearsonAdvAndRoyOrderByWithRelationInputObjectSchema, PearsonAdvAndRoyOrderByWithRelationInputObjectSchema.array()]).optional(), where: PearsonAdvAndRoyWhereInputObjectSchema.optional(), cursor: PearsonAdvAndRoyWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PearsonAdvAndRoyCountAggregateInputObjectSchema ]).optional(), _min: PearsonAdvAndRoyMinAggregateInputObjectSchema.optional(), _max: PearsonAdvAndRoyMaxAggregateInputObjectSchema.optional(), _avg: PearsonAdvAndRoyAvgAggregateInputObjectSchema.optional(), _sum: PearsonAdvAndRoySumAggregateInputObjectSchema.optional() }).strict();