import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArTransactionTypeOrderByWithRelationInputObjectSchema as ArTransactionTypeOrderByWithRelationInputObjectSchema } from './objects/ArTransactionTypeOrderByWithRelationInput.schema';
import { ArTransactionTypeWhereInputObjectSchema as ArTransactionTypeWhereInputObjectSchema } from './objects/ArTransactionTypeWhereInput.schema';
import { ArTransactionTypeWhereUniqueInputObjectSchema as ArTransactionTypeWhereUniqueInputObjectSchema } from './objects/ArTransactionTypeWhereUniqueInput.schema';
import { ArTransactionTypeCountAggregateInputObjectSchema as ArTransactionTypeCountAggregateInputObjectSchema } from './objects/ArTransactionTypeCountAggregateInput.schema';
import { ArTransactionTypeMinAggregateInputObjectSchema as ArTransactionTypeMinAggregateInputObjectSchema } from './objects/ArTransactionTypeMinAggregateInput.schema';
import { ArTransactionTypeMaxAggregateInputObjectSchema as ArTransactionTypeMaxAggregateInputObjectSchema } from './objects/ArTransactionTypeMaxAggregateInput.schema';
import { ArTransactionTypeAvgAggregateInputObjectSchema as ArTransactionTypeAvgAggregateInputObjectSchema } from './objects/ArTransactionTypeAvgAggregateInput.schema';
import { ArTransactionTypeSumAggregateInputObjectSchema as ArTransactionTypeSumAggregateInputObjectSchema } from './objects/ArTransactionTypeSumAggregateInput.schema';

export const ArTransactionTypeAggregateSchema: z.ZodType<Prisma.ArTransactionTypeAggregateArgs> = z.object({ orderBy: z.union([ArTransactionTypeOrderByWithRelationInputObjectSchema, ArTransactionTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArTransactionTypeWhereInputObjectSchema.optional(), cursor: ArTransactionTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArTransactionTypeCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionTypeMinAggregateInputObjectSchema.optional(), _max: ArTransactionTypeMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionTypeAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArTransactionTypeAggregateArgs>;

export const ArTransactionTypeAggregateZodSchema = z.object({ orderBy: z.union([ArTransactionTypeOrderByWithRelationInputObjectSchema, ArTransactionTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArTransactionTypeWhereInputObjectSchema.optional(), cursor: ArTransactionTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArTransactionTypeCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionTypeMinAggregateInputObjectSchema.optional(), _max: ArTransactionTypeMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionTypeAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionTypeSumAggregateInputObjectSchema.optional() }).strict();