import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblRoyRatesOrderByWithRelationInputObjectSchema as tblRoyRatesOrderByWithRelationInputObjectSchema } from './objects/tblRoyRatesOrderByWithRelationInput.schema';
import { tblRoyRatesWhereInputObjectSchema as tblRoyRatesWhereInputObjectSchema } from './objects/tblRoyRatesWhereInput.schema';
import { tblRoyRatesWhereUniqueInputObjectSchema as tblRoyRatesWhereUniqueInputObjectSchema } from './objects/tblRoyRatesWhereUniqueInput.schema';
import { TblRoyRatesCountAggregateInputObjectSchema as TblRoyRatesCountAggregateInputObjectSchema } from './objects/TblRoyRatesCountAggregateInput.schema';
import { TblRoyRatesMinAggregateInputObjectSchema as TblRoyRatesMinAggregateInputObjectSchema } from './objects/TblRoyRatesMinAggregateInput.schema';
import { TblRoyRatesMaxAggregateInputObjectSchema as TblRoyRatesMaxAggregateInputObjectSchema } from './objects/TblRoyRatesMaxAggregateInput.schema';
import { TblRoyRatesAvgAggregateInputObjectSchema as TblRoyRatesAvgAggregateInputObjectSchema } from './objects/TblRoyRatesAvgAggregateInput.schema';
import { TblRoyRatesSumAggregateInputObjectSchema as TblRoyRatesSumAggregateInputObjectSchema } from './objects/TblRoyRatesSumAggregateInput.schema';

export const tblRoyRatesAggregateSchema: z.ZodType<Prisma.tblRoyRatesAggregateArgs> = z.object({ orderBy: z.union([tblRoyRatesOrderByWithRelationInputObjectSchema, tblRoyRatesOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblRoyRatesWhereInputObjectSchema.optional(), cursor: tblRoyRatesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblRoyRatesCountAggregateInputObjectSchema ]).optional(), _min: TblRoyRatesMinAggregateInputObjectSchema.optional(), _max: TblRoyRatesMaxAggregateInputObjectSchema.optional(), _avg: TblRoyRatesAvgAggregateInputObjectSchema.optional(), _sum: TblRoyRatesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblRoyRatesAggregateArgs>;

export const tblRoyRatesAggregateZodSchema = z.object({ orderBy: z.union([tblRoyRatesOrderByWithRelationInputObjectSchema, tblRoyRatesOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblRoyRatesWhereInputObjectSchema.optional(), cursor: tblRoyRatesWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblRoyRatesCountAggregateInputObjectSchema ]).optional(), _min: TblRoyRatesMinAggregateInputObjectSchema.optional(), _max: TblRoyRatesMaxAggregateInputObjectSchema.optional(), _avg: TblRoyRatesAvgAggregateInputObjectSchema.optional(), _sum: TblRoyRatesSumAggregateInputObjectSchema.optional() }).strict();