import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CountryDictionaryOrderByWithRelationInputObjectSchema as CountryDictionaryOrderByWithRelationInputObjectSchema } from './objects/CountryDictionaryOrderByWithRelationInput.schema';
import { CountryDictionaryWhereInputObjectSchema as CountryDictionaryWhereInputObjectSchema } from './objects/CountryDictionaryWhereInput.schema';
import { CountryDictionaryWhereUniqueInputObjectSchema as CountryDictionaryWhereUniqueInputObjectSchema } from './objects/CountryDictionaryWhereUniqueInput.schema';
import { CountryDictionaryCountAggregateInputObjectSchema as CountryDictionaryCountAggregateInputObjectSchema } from './objects/CountryDictionaryCountAggregateInput.schema';
import { CountryDictionaryMinAggregateInputObjectSchema as CountryDictionaryMinAggregateInputObjectSchema } from './objects/CountryDictionaryMinAggregateInput.schema';
import { CountryDictionaryMaxAggregateInputObjectSchema as CountryDictionaryMaxAggregateInputObjectSchema } from './objects/CountryDictionaryMaxAggregateInput.schema';
import { CountryDictionaryAvgAggregateInputObjectSchema as CountryDictionaryAvgAggregateInputObjectSchema } from './objects/CountryDictionaryAvgAggregateInput.schema';
import { CountryDictionarySumAggregateInputObjectSchema as CountryDictionarySumAggregateInputObjectSchema } from './objects/CountryDictionarySumAggregateInput.schema';

export const CountryDictionaryAggregateSchema: z.ZodType<Prisma.CountryDictionaryAggregateArgs> = z.object({ orderBy: z.union([CountryDictionaryOrderByWithRelationInputObjectSchema, CountryDictionaryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CountryDictionaryWhereInputObjectSchema.optional(), cursor: CountryDictionaryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CountryDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CountryDictionaryMinAggregateInputObjectSchema.optional(), _max: CountryDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CountryDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CountryDictionarySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CountryDictionaryAggregateArgs>;

export const CountryDictionaryAggregateZodSchema = z.object({ orderBy: z.union([CountryDictionaryOrderByWithRelationInputObjectSchema, CountryDictionaryOrderByWithRelationInputObjectSchema.array()]).optional(), where: CountryDictionaryWhereInputObjectSchema.optional(), cursor: CountryDictionaryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CountryDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CountryDictionaryMinAggregateInputObjectSchema.optional(), _max: CountryDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CountryDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CountryDictionarySumAggregateInputObjectSchema.optional() }).strict();