import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblClients_obsoleteOrderByWithRelationInputObjectSchema as tblClients_obsoleteOrderByWithRelationInputObjectSchema } from './objects/tblClients_obsoleteOrderByWithRelationInput.schema';
import { tblClients_obsoleteWhereInputObjectSchema as tblClients_obsoleteWhereInputObjectSchema } from './objects/tblClients_obsoleteWhereInput.schema';
import { tblClients_obsoleteWhereUniqueInputObjectSchema as tblClients_obsoleteWhereUniqueInputObjectSchema } from './objects/tblClients_obsoleteWhereUniqueInput.schema';
import { TblClients_obsoleteCountAggregateInputObjectSchema as TblClients_obsoleteCountAggregateInputObjectSchema } from './objects/TblClients_obsoleteCountAggregateInput.schema';
import { TblClients_obsoleteMinAggregateInputObjectSchema as TblClients_obsoleteMinAggregateInputObjectSchema } from './objects/TblClients_obsoleteMinAggregateInput.schema';
import { TblClients_obsoleteMaxAggregateInputObjectSchema as TblClients_obsoleteMaxAggregateInputObjectSchema } from './objects/TblClients_obsoleteMaxAggregateInput.schema';
import { TblClients_obsoleteAvgAggregateInputObjectSchema as TblClients_obsoleteAvgAggregateInputObjectSchema } from './objects/TblClients_obsoleteAvgAggregateInput.schema';
import { TblClients_obsoleteSumAggregateInputObjectSchema as TblClients_obsoleteSumAggregateInputObjectSchema } from './objects/TblClients_obsoleteSumAggregateInput.schema';

export const tblClients_obsoleteAggregateSchema: z.ZodType<Prisma.TblClients_obsoleteAggregateArgs> = z.object({ orderBy: z.union([tblClients_obsoleteOrderByWithRelationInputObjectSchema, tblClients_obsoleteOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblClients_obsoleteWhereInputObjectSchema.optional(), cursor: tblClients_obsoleteWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblClients_obsoleteCountAggregateInputObjectSchema ]).optional(), _min: TblClients_obsoleteMinAggregateInputObjectSchema.optional(), _max: TblClients_obsoleteMaxAggregateInputObjectSchema.optional(), _avg: TblClients_obsoleteAvgAggregateInputObjectSchema.optional(), _sum: TblClients_obsoleteSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TblClients_obsoleteAggregateArgs>;

export const tblClients_obsoleteAggregateZodSchema = z.object({ orderBy: z.union([tblClients_obsoleteOrderByWithRelationInputObjectSchema, tblClients_obsoleteOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblClients_obsoleteWhereInputObjectSchema.optional(), cursor: tblClients_obsoleteWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblClients_obsoleteCountAggregateInputObjectSchema ]).optional(), _min: TblClients_obsoleteMinAggregateInputObjectSchema.optional(), _max: TblClients_obsoleteMaxAggregateInputObjectSchema.optional(), _avg: TblClients_obsoleteAvgAggregateInputObjectSchema.optional(), _sum: TblClients_obsoleteSumAggregateInputObjectSchema.optional() }).strict();