import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AgreementAdvanceOrderByWithRelationInputObjectSchema as AgreementAdvanceOrderByWithRelationInputObjectSchema } from './objects/AgreementAdvanceOrderByWithRelationInput.schema';
import { AgreementAdvanceWhereInputObjectSchema as AgreementAdvanceWhereInputObjectSchema } from './objects/AgreementAdvanceWhereInput.schema';
import { AgreementAdvanceWhereUniqueInputObjectSchema as AgreementAdvanceWhereUniqueInputObjectSchema } from './objects/AgreementAdvanceWhereUniqueInput.schema';
import { AgreementAdvanceCountAggregateInputObjectSchema as AgreementAdvanceCountAggregateInputObjectSchema } from './objects/AgreementAdvanceCountAggregateInput.schema';
import { AgreementAdvanceMinAggregateInputObjectSchema as AgreementAdvanceMinAggregateInputObjectSchema } from './objects/AgreementAdvanceMinAggregateInput.schema';
import { AgreementAdvanceMaxAggregateInputObjectSchema as AgreementAdvanceMaxAggregateInputObjectSchema } from './objects/AgreementAdvanceMaxAggregateInput.schema';
import { AgreementAdvanceAvgAggregateInputObjectSchema as AgreementAdvanceAvgAggregateInputObjectSchema } from './objects/AgreementAdvanceAvgAggregateInput.schema';
import { AgreementAdvanceSumAggregateInputObjectSchema as AgreementAdvanceSumAggregateInputObjectSchema } from './objects/AgreementAdvanceSumAggregateInput.schema';

export const AgreementAdvanceAggregateSchema: z.ZodType<Prisma.AgreementAdvanceAggregateArgs> = z.object({ orderBy: z.union([AgreementAdvanceOrderByWithRelationInputObjectSchema, AgreementAdvanceOrderByWithRelationInputObjectSchema.array()]).optional(), where: AgreementAdvanceWhereInputObjectSchema.optional(), cursor: AgreementAdvanceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AgreementAdvanceCountAggregateInputObjectSchema ]).optional(), _min: AgreementAdvanceMinAggregateInputObjectSchema.optional(), _max: AgreementAdvanceMaxAggregateInputObjectSchema.optional(), _avg: AgreementAdvanceAvgAggregateInputObjectSchema.optional(), _sum: AgreementAdvanceSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgreementAdvanceAggregateArgs>;

export const AgreementAdvanceAggregateZodSchema = z.object({ orderBy: z.union([AgreementAdvanceOrderByWithRelationInputObjectSchema, AgreementAdvanceOrderByWithRelationInputObjectSchema.array()]).optional(), where: AgreementAdvanceWhereInputObjectSchema.optional(), cursor: AgreementAdvanceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AgreementAdvanceCountAggregateInputObjectSchema ]).optional(), _min: AgreementAdvanceMinAggregateInputObjectSchema.optional(), _max: AgreementAdvanceMaxAggregateInputObjectSchema.optional(), _avg: AgreementAdvanceAvgAggregateInputObjectSchema.optional(), _sum: AgreementAdvanceSumAggregateInputObjectSchema.optional() }).strict();