import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { lkpPayTypeOrderByWithRelationInputObjectSchema as lkpPayTypeOrderByWithRelationInputObjectSchema } from './objects/lkpPayTypeOrderByWithRelationInput.schema';
import { lkpPayTypeWhereInputObjectSchema as lkpPayTypeWhereInputObjectSchema } from './objects/lkpPayTypeWhereInput.schema';
import { lkpPayTypeWhereUniqueInputObjectSchema as lkpPayTypeWhereUniqueInputObjectSchema } from './objects/lkpPayTypeWhereUniqueInput.schema';
import { LkpPayTypeCountAggregateInputObjectSchema as LkpPayTypeCountAggregateInputObjectSchema } from './objects/LkpPayTypeCountAggregateInput.schema';
import { LkpPayTypeMinAggregateInputObjectSchema as LkpPayTypeMinAggregateInputObjectSchema } from './objects/LkpPayTypeMinAggregateInput.schema';
import { LkpPayTypeMaxAggregateInputObjectSchema as LkpPayTypeMaxAggregateInputObjectSchema } from './objects/LkpPayTypeMaxAggregateInput.schema';
import { LkpPayTypeAvgAggregateInputObjectSchema as LkpPayTypeAvgAggregateInputObjectSchema } from './objects/LkpPayTypeAvgAggregateInput.schema';
import { LkpPayTypeSumAggregateInputObjectSchema as LkpPayTypeSumAggregateInputObjectSchema } from './objects/LkpPayTypeSumAggregateInput.schema';

export const lkpPayTypeAggregateSchema: z.ZodType<Prisma.lkpPayTypeAggregateArgs> = z.object({ orderBy: z.union([lkpPayTypeOrderByWithRelationInputObjectSchema, lkpPayTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: lkpPayTypeWhereInputObjectSchema.optional(), cursor: lkpPayTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), LkpPayTypeCountAggregateInputObjectSchema ]).optional(), _min: LkpPayTypeMinAggregateInputObjectSchema.optional(), _max: LkpPayTypeMaxAggregateInputObjectSchema.optional(), _avg: LkpPayTypeAvgAggregateInputObjectSchema.optional(), _sum: LkpPayTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.lkpPayTypeAggregateArgs>;

export const lkpPayTypeAggregateZodSchema = z.object({ orderBy: z.union([lkpPayTypeOrderByWithRelationInputObjectSchema, lkpPayTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: lkpPayTypeWhereInputObjectSchema.optional(), cursor: lkpPayTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), LkpPayTypeCountAggregateInputObjectSchema ]).optional(), _min: LkpPayTypeMinAggregateInputObjectSchema.optional(), _max: LkpPayTypeMaxAggregateInputObjectSchema.optional(), _avg: LkpPayTypeAvgAggregateInputObjectSchema.optional(), _sum: LkpPayTypeSumAggregateInputObjectSchema.optional() }).strict();