import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictTargetGroupsOrderByWithRelationInputObjectSchema as dictTargetGroupsOrderByWithRelationInputObjectSchema } from './objects/dictTargetGroupsOrderByWithRelationInput.schema';
import { dictTargetGroupsWhereInputObjectSchema as dictTargetGroupsWhereInputObjectSchema } from './objects/dictTargetGroupsWhereInput.schema';
import { dictTargetGroupsWhereUniqueInputObjectSchema as dictTargetGroupsWhereUniqueInputObjectSchema } from './objects/dictTargetGroupsWhereUniqueInput.schema';
import { DictTargetGroupsCountAggregateInputObjectSchema as DictTargetGroupsCountAggregateInputObjectSchema } from './objects/DictTargetGroupsCountAggregateInput.schema';
import { DictTargetGroupsMinAggregateInputObjectSchema as DictTargetGroupsMinAggregateInputObjectSchema } from './objects/DictTargetGroupsMinAggregateInput.schema';
import { DictTargetGroupsMaxAggregateInputObjectSchema as DictTargetGroupsMaxAggregateInputObjectSchema } from './objects/DictTargetGroupsMaxAggregateInput.schema';
import { DictTargetGroupsAvgAggregateInputObjectSchema as DictTargetGroupsAvgAggregateInputObjectSchema } from './objects/DictTargetGroupsAvgAggregateInput.schema';
import { DictTargetGroupsSumAggregateInputObjectSchema as DictTargetGroupsSumAggregateInputObjectSchema } from './objects/DictTargetGroupsSumAggregateInput.schema';

export const dictTargetGroupsAggregateSchema: z.ZodType<Prisma.dictTargetGroupsAggregateArgs> = z.object({ orderBy: z.union([dictTargetGroupsOrderByWithRelationInputObjectSchema, dictTargetGroupsOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictTargetGroupsWhereInputObjectSchema.optional(), cursor: dictTargetGroupsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictTargetGroupsCountAggregateInputObjectSchema ]).optional(), _min: DictTargetGroupsMinAggregateInputObjectSchema.optional(), _max: DictTargetGroupsMaxAggregateInputObjectSchema.optional(), _avg: DictTargetGroupsAvgAggregateInputObjectSchema.optional(), _sum: DictTargetGroupsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictTargetGroupsAggregateArgs>;

export const dictTargetGroupsAggregateZodSchema = z.object({ orderBy: z.union([dictTargetGroupsOrderByWithRelationInputObjectSchema, dictTargetGroupsOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictTargetGroupsWhereInputObjectSchema.optional(), cursor: dictTargetGroupsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictTargetGroupsCountAggregateInputObjectSchema ]).optional(), _min: DictTargetGroupsMinAggregateInputObjectSchema.optional(), _max: DictTargetGroupsMaxAggregateInputObjectSchema.optional(), _avg: DictTargetGroupsAvgAggregateInputObjectSchema.optional(), _sum: DictTargetGroupsSumAggregateInputObjectSchema.optional() }).strict();