import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictRoyPriceTypeOrderByWithRelationInputObjectSchema as dictRoyPriceTypeOrderByWithRelationInputObjectSchema } from './objects/dictRoyPriceTypeOrderByWithRelationInput.schema';
import { dictRoyPriceTypeWhereInputObjectSchema as dictRoyPriceTypeWhereInputObjectSchema } from './objects/dictRoyPriceTypeWhereInput.schema';
import { dictRoyPriceTypeWhereUniqueInputObjectSchema as dictRoyPriceTypeWhereUniqueInputObjectSchema } from './objects/dictRoyPriceTypeWhereUniqueInput.schema';
import { DictRoyPriceTypeCountAggregateInputObjectSchema as DictRoyPriceTypeCountAggregateInputObjectSchema } from './objects/DictRoyPriceTypeCountAggregateInput.schema';
import { DictRoyPriceTypeMinAggregateInputObjectSchema as DictRoyPriceTypeMinAggregateInputObjectSchema } from './objects/DictRoyPriceTypeMinAggregateInput.schema';
import { DictRoyPriceTypeMaxAggregateInputObjectSchema as DictRoyPriceTypeMaxAggregateInputObjectSchema } from './objects/DictRoyPriceTypeMaxAggregateInput.schema';
import { DictRoyPriceTypeAvgAggregateInputObjectSchema as DictRoyPriceTypeAvgAggregateInputObjectSchema } from './objects/DictRoyPriceTypeAvgAggregateInput.schema';
import { DictRoyPriceTypeSumAggregateInputObjectSchema as DictRoyPriceTypeSumAggregateInputObjectSchema } from './objects/DictRoyPriceTypeSumAggregateInput.schema';

export const dictRoyPriceTypeAggregateSchema: z.ZodType<Prisma.dictRoyPriceTypeAggregateArgs> = z.object({ orderBy: z.union([dictRoyPriceTypeOrderByWithRelationInputObjectSchema, dictRoyPriceTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictRoyPriceTypeWhereInputObjectSchema.optional(), cursor: dictRoyPriceTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictRoyPriceTypeCountAggregateInputObjectSchema ]).optional(), _min: DictRoyPriceTypeMinAggregateInputObjectSchema.optional(), _max: DictRoyPriceTypeMaxAggregateInputObjectSchema.optional(), _avg: DictRoyPriceTypeAvgAggregateInputObjectSchema.optional(), _sum: DictRoyPriceTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictRoyPriceTypeAggregateArgs>;

export const dictRoyPriceTypeAggregateZodSchema = z.object({ orderBy: z.union([dictRoyPriceTypeOrderByWithRelationInputObjectSchema, dictRoyPriceTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictRoyPriceTypeWhereInputObjectSchema.optional(), cursor: dictRoyPriceTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictRoyPriceTypeCountAggregateInputObjectSchema ]).optional(), _min: DictRoyPriceTypeMinAggregateInputObjectSchema.optional(), _max: DictRoyPriceTypeMaxAggregateInputObjectSchema.optional(), _avg: DictRoyPriceTypeAvgAggregateInputObjectSchema.optional(), _sum: DictRoyPriceTypeSumAggregateInputObjectSchema.optional() }).strict();