import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblUserAccessOrderByWithRelationInputObjectSchema as tblUserAccessOrderByWithRelationInputObjectSchema } from './objects/tblUserAccessOrderByWithRelationInput.schema';
import { tblUserAccessWhereInputObjectSchema as tblUserAccessWhereInputObjectSchema } from './objects/tblUserAccessWhereInput.schema';
import { tblUserAccessWhereUniqueInputObjectSchema as tblUserAccessWhereUniqueInputObjectSchema } from './objects/tblUserAccessWhereUniqueInput.schema';
import { TblUserAccessCountAggregateInputObjectSchema as TblUserAccessCountAggregateInputObjectSchema } from './objects/TblUserAccessCountAggregateInput.schema';
import { TblUserAccessMinAggregateInputObjectSchema as TblUserAccessMinAggregateInputObjectSchema } from './objects/TblUserAccessMinAggregateInput.schema';
import { TblUserAccessMaxAggregateInputObjectSchema as TblUserAccessMaxAggregateInputObjectSchema } from './objects/TblUserAccessMaxAggregateInput.schema';
import { TblUserAccessAvgAggregateInputObjectSchema as TblUserAccessAvgAggregateInputObjectSchema } from './objects/TblUserAccessAvgAggregateInput.schema';
import { TblUserAccessSumAggregateInputObjectSchema as TblUserAccessSumAggregateInputObjectSchema } from './objects/TblUserAccessSumAggregateInput.schema';

export const tblUserAccessAggregateSchema: z.ZodType<Prisma.tblUserAccessAggregateArgs> = z.object({ orderBy: z.union([tblUserAccessOrderByWithRelationInputObjectSchema, tblUserAccessOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblUserAccessWhereInputObjectSchema.optional(), cursor: tblUserAccessWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblUserAccessCountAggregateInputObjectSchema ]).optional(), _min: TblUserAccessMinAggregateInputObjectSchema.optional(), _max: TblUserAccessMaxAggregateInputObjectSchema.optional(), _avg: TblUserAccessAvgAggregateInputObjectSchema.optional(), _sum: TblUserAccessSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblUserAccessAggregateArgs>;

export const tblUserAccessAggregateZodSchema = z.object({ orderBy: z.union([tblUserAccessOrderByWithRelationInputObjectSchema, tblUserAccessOrderByWithRelationInputObjectSchema.array()]).optional(), where: tblUserAccessWhereInputObjectSchema.optional(), cursor: tblUserAccessWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TblUserAccessCountAggregateInputObjectSchema ]).optional(), _min: TblUserAccessMinAggregateInputObjectSchema.optional(), _max: TblUserAccessMaxAggregateInputObjectSchema.optional(), _avg: TblUserAccessAvgAggregateInputObjectSchema.optional(), _sum: TblUserAccessSumAggregateInputObjectSchema.optional() }).strict();