import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictSubmSentTypeOrderByWithRelationInputObjectSchema as dictSubmSentTypeOrderByWithRelationInputObjectSchema } from './objects/dictSubmSentTypeOrderByWithRelationInput.schema';
import { dictSubmSentTypeWhereInputObjectSchema as dictSubmSentTypeWhereInputObjectSchema } from './objects/dictSubmSentTypeWhereInput.schema';
import { dictSubmSentTypeWhereUniqueInputObjectSchema as dictSubmSentTypeWhereUniqueInputObjectSchema } from './objects/dictSubmSentTypeWhereUniqueInput.schema';
import { DictSubmSentTypeCountAggregateInputObjectSchema as DictSubmSentTypeCountAggregateInputObjectSchema } from './objects/DictSubmSentTypeCountAggregateInput.schema';
import { DictSubmSentTypeMinAggregateInputObjectSchema as DictSubmSentTypeMinAggregateInputObjectSchema } from './objects/DictSubmSentTypeMinAggregateInput.schema';
import { DictSubmSentTypeMaxAggregateInputObjectSchema as DictSubmSentTypeMaxAggregateInputObjectSchema } from './objects/DictSubmSentTypeMaxAggregateInput.schema';
import { DictSubmSentTypeAvgAggregateInputObjectSchema as DictSubmSentTypeAvgAggregateInputObjectSchema } from './objects/DictSubmSentTypeAvgAggregateInput.schema';
import { DictSubmSentTypeSumAggregateInputObjectSchema as DictSubmSentTypeSumAggregateInputObjectSchema } from './objects/DictSubmSentTypeSumAggregateInput.schema';

export const dictSubmSentTypeAggregateSchema: z.ZodType<Prisma.dictSubmSentTypeAggregateArgs> = z.object({ orderBy: z.union([dictSubmSentTypeOrderByWithRelationInputObjectSchema, dictSubmSentTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictSubmSentTypeWhereInputObjectSchema.optional(), cursor: dictSubmSentTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictSubmSentTypeCountAggregateInputObjectSchema ]).optional(), _min: DictSubmSentTypeMinAggregateInputObjectSchema.optional(), _max: DictSubmSentTypeMaxAggregateInputObjectSchema.optional(), _avg: DictSubmSentTypeAvgAggregateInputObjectSchema.optional(), _sum: DictSubmSentTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictSubmSentTypeAggregateArgs>;

export const dictSubmSentTypeAggregateZodSchema = z.object({ orderBy: z.union([dictSubmSentTypeOrderByWithRelationInputObjectSchema, dictSubmSentTypeOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictSubmSentTypeWhereInputObjectSchema.optional(), cursor: dictSubmSentTypeWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DictSubmSentTypeCountAggregateInputObjectSchema ]).optional(), _min: DictSubmSentTypeMinAggregateInputObjectSchema.optional(), _max: DictSubmSentTypeMaxAggregateInputObjectSchema.optional(), _avg: DictSubmSentTypeAvgAggregateInputObjectSchema.optional(), _sum: DictSubmSentTypeSumAggregateInputObjectSchema.optional() }).strict();