import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaxResidenceSendOrderByWithRelationInputObjectSchema as TaxResidenceSendOrderByWithRelationInputObjectSchema } from './objects/TaxResidenceSendOrderByWithRelationInput.schema';
import { TaxResidenceSendWhereInputObjectSchema as TaxResidenceSendWhereInputObjectSchema } from './objects/TaxResidenceSendWhereInput.schema';
import { TaxResidenceSendWhereUniqueInputObjectSchema as TaxResidenceSendWhereUniqueInputObjectSchema } from './objects/TaxResidenceSendWhereUniqueInput.schema';
import { TaxResidenceSendCountAggregateInputObjectSchema as TaxResidenceSendCountAggregateInputObjectSchema } from './objects/TaxResidenceSendCountAggregateInput.schema';
import { TaxResidenceSendMinAggregateInputObjectSchema as TaxResidenceSendMinAggregateInputObjectSchema } from './objects/TaxResidenceSendMinAggregateInput.schema';
import { TaxResidenceSendMaxAggregateInputObjectSchema as TaxResidenceSendMaxAggregateInputObjectSchema } from './objects/TaxResidenceSendMaxAggregateInput.schema';
import { TaxResidenceSendAvgAggregateInputObjectSchema as TaxResidenceSendAvgAggregateInputObjectSchema } from './objects/TaxResidenceSendAvgAggregateInput.schema';
import { TaxResidenceSendSumAggregateInputObjectSchema as TaxResidenceSendSumAggregateInputObjectSchema } from './objects/TaxResidenceSendSumAggregateInput.schema';

export const TaxResidenceSendAggregateSchema: z.ZodType<Prisma.TaxResidenceSendAggregateArgs> = z.object({ orderBy: z.union([TaxResidenceSendOrderByWithRelationInputObjectSchema, TaxResidenceSendOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaxResidenceSendWhereInputObjectSchema.optional(), cursor: TaxResidenceSendWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaxResidenceSendCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceSendMinAggregateInputObjectSchema.optional(), _max: TaxResidenceSendMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceSendAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceSendSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaxResidenceSendAggregateArgs>;

export const TaxResidenceSendAggregateZodSchema = z.object({ orderBy: z.union([TaxResidenceSendOrderByWithRelationInputObjectSchema, TaxResidenceSendOrderByWithRelationInputObjectSchema.array()]).optional(), where: TaxResidenceSendWhereInputObjectSchema.optional(), cursor: TaxResidenceSendWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TaxResidenceSendCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceSendMinAggregateInputObjectSchema.optional(), _max: TaxResidenceSendMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceSendAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceSendSumAggregateInputObjectSchema.optional() }).strict();