import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArTransactionDetailOrderByWithRelationInputObjectSchema as ArTransactionDetailOrderByWithRelationInputObjectSchema } from './objects/ArTransactionDetailOrderByWithRelationInput.schema';
import { ArTransactionDetailWhereInputObjectSchema as ArTransactionDetailWhereInputObjectSchema } from './objects/ArTransactionDetailWhereInput.schema';
import { ArTransactionDetailWhereUniqueInputObjectSchema as ArTransactionDetailWhereUniqueInputObjectSchema } from './objects/ArTransactionDetailWhereUniqueInput.schema';
import { ArTransactionDetailCountAggregateInputObjectSchema as ArTransactionDetailCountAggregateInputObjectSchema } from './objects/ArTransactionDetailCountAggregateInput.schema';
import { ArTransactionDetailMinAggregateInputObjectSchema as ArTransactionDetailMinAggregateInputObjectSchema } from './objects/ArTransactionDetailMinAggregateInput.schema';
import { ArTransactionDetailMaxAggregateInputObjectSchema as ArTransactionDetailMaxAggregateInputObjectSchema } from './objects/ArTransactionDetailMaxAggregateInput.schema';
import { ArTransactionDetailAvgAggregateInputObjectSchema as ArTransactionDetailAvgAggregateInputObjectSchema } from './objects/ArTransactionDetailAvgAggregateInput.schema';
import { ArTransactionDetailSumAggregateInputObjectSchema as ArTransactionDetailSumAggregateInputObjectSchema } from './objects/ArTransactionDetailSumAggregateInput.schema';

export const ArTransactionDetailAggregateSchema: z.ZodType<Prisma.ArTransactionDetailAggregateArgs> = z.object({ orderBy: z.union([ArTransactionDetailOrderByWithRelationInputObjectSchema, ArTransactionDetailOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArTransactionDetailWhereInputObjectSchema.optional(), cursor: ArTransactionDetailWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArTransactionDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionDetailMinAggregateInputObjectSchema.optional(), _max: ArTransactionDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionDetailSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArTransactionDetailAggregateArgs>;

export const ArTransactionDetailAggregateZodSchema = z.object({ orderBy: z.union([ArTransactionDetailOrderByWithRelationInputObjectSchema, ArTransactionDetailOrderByWithRelationInputObjectSchema.array()]).optional(), where: ArTransactionDetailWhereInputObjectSchema.optional(), cursor: ArTransactionDetailWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ArTransactionDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionDetailMinAggregateInputObjectSchema.optional(), _max: ArTransactionDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionDetailSumAggregateInputObjectSchema.optional() }).strict();