import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema as dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonOrderByWithRelationInput.schema';
import { dictAdvWithoutInvExcludeReasonWhereInputObjectSchema as dictAdvWithoutInvExcludeReasonWhereInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonWhereInput.schema';
import { dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema as dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonWhereUniqueInput.schema';
import { DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonCountAggregateInput.schema';

export const dictAdvWithoutInvExcludeReasonCountSchema: z.ZodType<Prisma.dictAdvWithoutInvExcludeReasonCountArgs> = z.object({ orderBy: z.union([dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema, dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictAdvWithoutInvExcludeReasonWhereInputObjectSchema.optional(), cursor: dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.dictAdvWithoutInvExcludeReasonCountArgs>;

export const dictAdvWithoutInvExcludeReasonCountZodSchema = z.object({ orderBy: z.union([dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema, dictAdvWithoutInvExcludeReasonOrderByWithRelationInputObjectSchema.array()]).optional(), where: dictAdvWithoutInvExcludeReasonWhereInputObjectSchema.optional(), cursor: dictAdvWithoutInvExcludeReasonWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema ]).optional() }).strict();