import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PearsonMaterialWhereInputObjectSchema as PearsonMaterialWhereInputObjectSchema } from './objects/PearsonMaterialWhereInput.schema';
import { PearsonMaterialOrderByWithAggregationInputObjectSchema as PearsonMaterialOrderByWithAggregationInputObjectSchema } from './objects/PearsonMaterialOrderByWithAggregationInput.schema';
import { PearsonMaterialScalarWhereWithAggregatesInputObjectSchema as PearsonMaterialScalarWhereWithAggregatesInputObjectSchema } from './objects/PearsonMaterialScalarWhereWithAggregatesInput.schema';
import { PearsonMaterialScalarFieldEnumSchema } from './enums/PearsonMaterialScalarFieldEnum.schema';
import { PearsonMaterialCountAggregateInputObjectSchema as PearsonMaterialCountAggregateInputObjectSchema } from './objects/PearsonMaterialCountAggregateInput.schema';
import { PearsonMaterialMinAggregateInputObjectSchema as PearsonMaterialMinAggregateInputObjectSchema } from './objects/PearsonMaterialMinAggregateInput.schema';
import { PearsonMaterialMaxAggregateInputObjectSchema as PearsonMaterialMaxAggregateInputObjectSchema } from './objects/PearsonMaterialMaxAggregateInput.schema';
import { PearsonMaterialAvgAggregateInputObjectSchema as PearsonMaterialAvgAggregateInputObjectSchema } from './objects/PearsonMaterialAvgAggregateInput.schema';
import { PearsonMaterialSumAggregateInputObjectSchema as PearsonMaterialSumAggregateInputObjectSchema } from './objects/PearsonMaterialSumAggregateInput.schema';

export const PearsonMaterialGroupBySchema: z.ZodType<Prisma.PearsonMaterialGroupByArgs> = z.object({ where: PearsonMaterialWhereInputObjectSchema.optional(), orderBy: z.union([PearsonMaterialOrderByWithAggregationInputObjectSchema, PearsonMaterialOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PearsonMaterialScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PearsonMaterialScalarFieldEnumSchema), _count: z.union([ z.literal(true), PearsonMaterialCountAggregateInputObjectSchema ]).optional(), _min: PearsonMaterialMinAggregateInputObjectSchema.optional(), _max: PearsonMaterialMaxAggregateInputObjectSchema.optional(), _avg: PearsonMaterialAvgAggregateInputObjectSchema.optional(), _sum: PearsonMaterialSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PearsonMaterialGroupByArgs>;

export const PearsonMaterialGroupByZodSchema = z.object({ where: PearsonMaterialWhereInputObjectSchema.optional(), orderBy: z.union([PearsonMaterialOrderByWithAggregationInputObjectSchema, PearsonMaterialOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PearsonMaterialScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PearsonMaterialScalarFieldEnumSchema), _count: z.union([ z.literal(true), PearsonMaterialCountAggregateInputObjectSchema ]).optional(), _min: PearsonMaterialMinAggregateInputObjectSchema.optional(), _max: PearsonMaterialMaxAggregateInputObjectSchema.optional(), _avg: PearsonMaterialAvgAggregateInputObjectSchema.optional(), _sum: PearsonMaterialSumAggregateInputObjectSchema.optional() }).strict();