import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaxResidenceCertWhereInputObjectSchema as TaxResidenceCertWhereInputObjectSchema } from './objects/TaxResidenceCertWhereInput.schema';
import { TaxResidenceCertOrderByWithAggregationInputObjectSchema as TaxResidenceCertOrderByWithAggregationInputObjectSchema } from './objects/TaxResidenceCertOrderByWithAggregationInput.schema';
import { TaxResidenceCertScalarWhereWithAggregatesInputObjectSchema as TaxResidenceCertScalarWhereWithAggregatesInputObjectSchema } from './objects/TaxResidenceCertScalarWhereWithAggregatesInput.schema';
import { TaxResidenceCertScalarFieldEnumSchema } from './enums/TaxResidenceCertScalarFieldEnum.schema';
import { TaxResidenceCertCountAggregateInputObjectSchema as TaxResidenceCertCountAggregateInputObjectSchema } from './objects/TaxResidenceCertCountAggregateInput.schema';
import { TaxResidenceCertMinAggregateInputObjectSchema as TaxResidenceCertMinAggregateInputObjectSchema } from './objects/TaxResidenceCertMinAggregateInput.schema';
import { TaxResidenceCertMaxAggregateInputObjectSchema as TaxResidenceCertMaxAggregateInputObjectSchema } from './objects/TaxResidenceCertMaxAggregateInput.schema';
import { TaxResidenceCertAvgAggregateInputObjectSchema as TaxResidenceCertAvgAggregateInputObjectSchema } from './objects/TaxResidenceCertAvgAggregateInput.schema';
import { TaxResidenceCertSumAggregateInputObjectSchema as TaxResidenceCertSumAggregateInputObjectSchema } from './objects/TaxResidenceCertSumAggregateInput.schema';

export const TaxResidenceCertGroupBySchema: z.ZodType<Prisma.TaxResidenceCertGroupByArgs> = z.object({ where: TaxResidenceCertWhereInputObjectSchema.optional(), orderBy: z.union([TaxResidenceCertOrderByWithAggregationInputObjectSchema, TaxResidenceCertOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaxResidenceCertScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaxResidenceCertScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaxResidenceCertCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceCertMinAggregateInputObjectSchema.optional(), _max: TaxResidenceCertMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceCertAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceCertSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaxResidenceCertGroupByArgs>;

export const TaxResidenceCertGroupByZodSchema = z.object({ where: TaxResidenceCertWhereInputObjectSchema.optional(), orderBy: z.union([TaxResidenceCertOrderByWithAggregationInputObjectSchema, TaxResidenceCertOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaxResidenceCertScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaxResidenceCertScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaxResidenceCertCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceCertMinAggregateInputObjectSchema.optional(), _max: TaxResidenceCertMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceCertAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceCertSumAggregateInputObjectSchema.optional() }).strict();