import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArTransactionDetailWhereInputObjectSchema as ArTransactionDetailWhereInputObjectSchema } from './objects/ArTransactionDetailWhereInput.schema';
import { ArTransactionDetailOrderByWithAggregationInputObjectSchema as ArTransactionDetailOrderByWithAggregationInputObjectSchema } from './objects/ArTransactionDetailOrderByWithAggregationInput.schema';
import { ArTransactionDetailScalarWhereWithAggregatesInputObjectSchema as ArTransactionDetailScalarWhereWithAggregatesInputObjectSchema } from './objects/ArTransactionDetailScalarWhereWithAggregatesInput.schema';
import { ArTransactionDetailScalarFieldEnumSchema } from './enums/ArTransactionDetailScalarFieldEnum.schema';
import { ArTransactionDetailCountAggregateInputObjectSchema as ArTransactionDetailCountAggregateInputObjectSchema } from './objects/ArTransactionDetailCountAggregateInput.schema';
import { ArTransactionDetailMinAggregateInputObjectSchema as ArTransactionDetailMinAggregateInputObjectSchema } from './objects/ArTransactionDetailMinAggregateInput.schema';
import { ArTransactionDetailMaxAggregateInputObjectSchema as ArTransactionDetailMaxAggregateInputObjectSchema } from './objects/ArTransactionDetailMaxAggregateInput.schema';
import { ArTransactionDetailAvgAggregateInputObjectSchema as ArTransactionDetailAvgAggregateInputObjectSchema } from './objects/ArTransactionDetailAvgAggregateInput.schema';
import { ArTransactionDetailSumAggregateInputObjectSchema as ArTransactionDetailSumAggregateInputObjectSchema } from './objects/ArTransactionDetailSumAggregateInput.schema';

export const ArTransactionDetailGroupBySchema: z.ZodType<Prisma.ArTransactionDetailGroupByArgs> = z.object({ where: ArTransactionDetailWhereInputObjectSchema.optional(), orderBy: z.union([ArTransactionDetailOrderByWithAggregationInputObjectSchema, ArTransactionDetailOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArTransactionDetailScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArTransactionDetailScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArTransactionDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionDetailMinAggregateInputObjectSchema.optional(), _max: ArTransactionDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionDetailSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArTransactionDetailGroupByArgs>;

export const ArTransactionDetailGroupByZodSchema = z.object({ where: ArTransactionDetailWhereInputObjectSchema.optional(), orderBy: z.union([ArTransactionDetailOrderByWithAggregationInputObjectSchema, ArTransactionDetailOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArTransactionDetailScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArTransactionDetailScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArTransactionDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionDetailMinAggregateInputObjectSchema.optional(), _max: ArTransactionDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionDetailSumAggregateInputObjectSchema.optional() }).strict();