import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AgreementEventWhereInputObjectSchema as AgreementEventWhereInputObjectSchema } from './objects/AgreementEventWhereInput.schema';
import { AgreementEventOrderByWithAggregationInputObjectSchema as AgreementEventOrderByWithAggregationInputObjectSchema } from './objects/AgreementEventOrderByWithAggregationInput.schema';
import { AgreementEventScalarWhereWithAggregatesInputObjectSchema as AgreementEventScalarWhereWithAggregatesInputObjectSchema } from './objects/AgreementEventScalarWhereWithAggregatesInput.schema';
import { AgreementEventScalarFieldEnumSchema } from './enums/AgreementEventScalarFieldEnum.schema';
import { AgreementEventCountAggregateInputObjectSchema as AgreementEventCountAggregateInputObjectSchema } from './objects/AgreementEventCountAggregateInput.schema';
import { AgreementEventMinAggregateInputObjectSchema as AgreementEventMinAggregateInputObjectSchema } from './objects/AgreementEventMinAggregateInput.schema';
import { AgreementEventMaxAggregateInputObjectSchema as AgreementEventMaxAggregateInputObjectSchema } from './objects/AgreementEventMaxAggregateInput.schema';
import { AgreementEventAvgAggregateInputObjectSchema as AgreementEventAvgAggregateInputObjectSchema } from './objects/AgreementEventAvgAggregateInput.schema';
import { AgreementEventSumAggregateInputObjectSchema as AgreementEventSumAggregateInputObjectSchema } from './objects/AgreementEventSumAggregateInput.schema';

export const AgreementEventGroupBySchema: z.ZodType<Prisma.AgreementEventGroupByArgs> = z.object({ where: AgreementEventWhereInputObjectSchema.optional(), orderBy: z.union([AgreementEventOrderByWithAggregationInputObjectSchema, AgreementEventOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementEventScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementEventScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementEventCountAggregateInputObjectSchema ]).optional(), _min: AgreementEventMinAggregateInputObjectSchema.optional(), _max: AgreementEventMaxAggregateInputObjectSchema.optional(), _avg: AgreementEventAvgAggregateInputObjectSchema.optional(), _sum: AgreementEventSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgreementEventGroupByArgs>;

export const AgreementEventGroupByZodSchema = z.object({ where: AgreementEventWhereInputObjectSchema.optional(), orderBy: z.union([AgreementEventOrderByWithAggregationInputObjectSchema, AgreementEventOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementEventScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementEventScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementEventCountAggregateInputObjectSchema ]).optional(), _min: AgreementEventMinAggregateInputObjectSchema.optional(), _max: AgreementEventMaxAggregateInputObjectSchema.optional(), _avg: AgreementEventAvgAggregateInputObjectSchema.optional(), _sum: AgreementEventSumAggregateInputObjectSchema.optional() }).strict();