import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblTaxResidenceCertificateWhereInputObjectSchema as tblTaxResidenceCertificateWhereInputObjectSchema } from './objects/tblTaxResidenceCertificateWhereInput.schema';
import { tblTaxResidenceCertificateOrderByWithAggregationInputObjectSchema as tblTaxResidenceCertificateOrderByWithAggregationInputObjectSchema } from './objects/tblTaxResidenceCertificateOrderByWithAggregationInput.schema';
import { tblTaxResidenceCertificateScalarWhereWithAggregatesInputObjectSchema as tblTaxResidenceCertificateScalarWhereWithAggregatesInputObjectSchema } from './objects/tblTaxResidenceCertificateScalarWhereWithAggregatesInput.schema';
import { TblTaxResidenceCertificateScalarFieldEnumSchema } from './enums/TblTaxResidenceCertificateScalarFieldEnum.schema';
import { TblTaxResidenceCertificateCountAggregateInputObjectSchema as TblTaxResidenceCertificateCountAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateCountAggregateInput.schema';
import { TblTaxResidenceCertificateMinAggregateInputObjectSchema as TblTaxResidenceCertificateMinAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateMinAggregateInput.schema';
import { TblTaxResidenceCertificateMaxAggregateInputObjectSchema as TblTaxResidenceCertificateMaxAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateMaxAggregateInput.schema';
import { TblTaxResidenceCertificateAvgAggregateInputObjectSchema as TblTaxResidenceCertificateAvgAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateAvgAggregateInput.schema';
import { TblTaxResidenceCertificateSumAggregateInputObjectSchema as TblTaxResidenceCertificateSumAggregateInputObjectSchema } from './objects/TblTaxResidenceCertificateSumAggregateInput.schema';

export const tblTaxResidenceCertificateGroupBySchema: z.ZodType<Prisma.tblTaxResidenceCertificateGroupByArgs> = z.object({ where: tblTaxResidenceCertificateWhereInputObjectSchema.optional(), orderBy: z.union([tblTaxResidenceCertificateOrderByWithAggregationInputObjectSchema, tblTaxResidenceCertificateOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblTaxResidenceCertificateScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblTaxResidenceCertificateScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblTaxResidenceCertificateCountAggregateInputObjectSchema ]).optional(), _min: TblTaxResidenceCertificateMinAggregateInputObjectSchema.optional(), _max: TblTaxResidenceCertificateMaxAggregateInputObjectSchema.optional(), _avg: TblTaxResidenceCertificateAvgAggregateInputObjectSchema.optional(), _sum: TblTaxResidenceCertificateSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblTaxResidenceCertificateGroupByArgs>;

export const tblTaxResidenceCertificateGroupByZodSchema = z.object({ where: tblTaxResidenceCertificateWhereInputObjectSchema.optional(), orderBy: z.union([tblTaxResidenceCertificateOrderByWithAggregationInputObjectSchema, tblTaxResidenceCertificateOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblTaxResidenceCertificateScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblTaxResidenceCertificateScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblTaxResidenceCertificateCountAggregateInputObjectSchema ]).optional(), _min: TblTaxResidenceCertificateMinAggregateInputObjectSchema.optional(), _max: TblTaxResidenceCertificateMaxAggregateInputObjectSchema.optional(), _avg: TblTaxResidenceCertificateAvgAggregateInputObjectSchema.optional(), _sum: TblTaxResidenceCertificateSumAggregateInputObjectSchema.optional() }).strict();