import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblMailingTemplatesWhereInputObjectSchema as tblMailingTemplatesWhereInputObjectSchema } from './objects/tblMailingTemplatesWhereInput.schema';
import { tblMailingTemplatesOrderByWithAggregationInputObjectSchema as tblMailingTemplatesOrderByWithAggregationInputObjectSchema } from './objects/tblMailingTemplatesOrderByWithAggregationInput.schema';
import { tblMailingTemplatesScalarWhereWithAggregatesInputObjectSchema as tblMailingTemplatesScalarWhereWithAggregatesInputObjectSchema } from './objects/tblMailingTemplatesScalarWhereWithAggregatesInput.schema';
import { TblMailingTemplatesScalarFieldEnumSchema } from './enums/TblMailingTemplatesScalarFieldEnum.schema';
import { TblMailingTemplatesCountAggregateInputObjectSchema as TblMailingTemplatesCountAggregateInputObjectSchema } from './objects/TblMailingTemplatesCountAggregateInput.schema';
import { TblMailingTemplatesMinAggregateInputObjectSchema as TblMailingTemplatesMinAggregateInputObjectSchema } from './objects/TblMailingTemplatesMinAggregateInput.schema';
import { TblMailingTemplatesMaxAggregateInputObjectSchema as TblMailingTemplatesMaxAggregateInputObjectSchema } from './objects/TblMailingTemplatesMaxAggregateInput.schema';
import { TblMailingTemplatesAvgAggregateInputObjectSchema as TblMailingTemplatesAvgAggregateInputObjectSchema } from './objects/TblMailingTemplatesAvgAggregateInput.schema';
import { TblMailingTemplatesSumAggregateInputObjectSchema as TblMailingTemplatesSumAggregateInputObjectSchema } from './objects/TblMailingTemplatesSumAggregateInput.schema';

export const tblMailingTemplatesGroupBySchema: z.ZodType<Prisma.tblMailingTemplatesGroupByArgs> = z.object({ where: tblMailingTemplatesWhereInputObjectSchema.optional(), orderBy: z.union([tblMailingTemplatesOrderByWithAggregationInputObjectSchema, tblMailingTemplatesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblMailingTemplatesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblMailingTemplatesScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblMailingTemplatesCountAggregateInputObjectSchema ]).optional(), _min: TblMailingTemplatesMinAggregateInputObjectSchema.optional(), _max: TblMailingTemplatesMaxAggregateInputObjectSchema.optional(), _avg: TblMailingTemplatesAvgAggregateInputObjectSchema.optional(), _sum: TblMailingTemplatesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblMailingTemplatesGroupByArgs>;

export const tblMailingTemplatesGroupByZodSchema = z.object({ where: tblMailingTemplatesWhereInputObjectSchema.optional(), orderBy: z.union([tblMailingTemplatesOrderByWithAggregationInputObjectSchema, tblMailingTemplatesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblMailingTemplatesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblMailingTemplatesScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblMailingTemplatesCountAggregateInputObjectSchema ]).optional(), _min: TblMailingTemplatesMinAggregateInputObjectSchema.optional(), _max: TblMailingTemplatesMaxAggregateInputObjectSchema.optional(), _avg: TblMailingTemplatesAvgAggregateInputObjectSchema.optional(), _sum: TblMailingTemplatesSumAggregateInputObjectSchema.optional() }).strict();