import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblCustContactsWhereInputObjectSchema as tblCustContactsWhereInputObjectSchema } from './objects/tblCustContactsWhereInput.schema';
import { tblCustContactsOrderByWithAggregationInputObjectSchema as tblCustContactsOrderByWithAggregationInputObjectSchema } from './objects/tblCustContactsOrderByWithAggregationInput.schema';
import { tblCustContactsScalarWhereWithAggregatesInputObjectSchema as tblCustContactsScalarWhereWithAggregatesInputObjectSchema } from './objects/tblCustContactsScalarWhereWithAggregatesInput.schema';
import { TblCustContactsScalarFieldEnumSchema } from './enums/TblCustContactsScalarFieldEnum.schema';
import { TblCustContactsCountAggregateInputObjectSchema as TblCustContactsCountAggregateInputObjectSchema } from './objects/TblCustContactsCountAggregateInput.schema';
import { TblCustContactsMinAggregateInputObjectSchema as TblCustContactsMinAggregateInputObjectSchema } from './objects/TblCustContactsMinAggregateInput.schema';
import { TblCustContactsMaxAggregateInputObjectSchema as TblCustContactsMaxAggregateInputObjectSchema } from './objects/TblCustContactsMaxAggregateInput.schema';
import { TblCustContactsAvgAggregateInputObjectSchema as TblCustContactsAvgAggregateInputObjectSchema } from './objects/TblCustContactsAvgAggregateInput.schema';
import { TblCustContactsSumAggregateInputObjectSchema as TblCustContactsSumAggregateInputObjectSchema } from './objects/TblCustContactsSumAggregateInput.schema';

export const tblCustContactsGroupBySchema: z.ZodType<Prisma.tblCustContactsGroupByArgs> = z.object({ where: tblCustContactsWhereInputObjectSchema.optional(), orderBy: z.union([tblCustContactsOrderByWithAggregationInputObjectSchema, tblCustContactsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblCustContactsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblCustContactsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblCustContactsCountAggregateInputObjectSchema ]).optional(), _min: TblCustContactsMinAggregateInputObjectSchema.optional(), _max: TblCustContactsMaxAggregateInputObjectSchema.optional(), _avg: TblCustContactsAvgAggregateInputObjectSchema.optional(), _sum: TblCustContactsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblCustContactsGroupByArgs>;

export const tblCustContactsGroupByZodSchema = z.object({ where: tblCustContactsWhereInputObjectSchema.optional(), orderBy: z.union([tblCustContactsOrderByWithAggregationInputObjectSchema, tblCustContactsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblCustContactsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblCustContactsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblCustContactsCountAggregateInputObjectSchema ]).optional(), _min: TblCustContactsMinAggregateInputObjectSchema.optional(), _max: TblCustContactsMaxAggregateInputObjectSchema.optional(), _avg: TblCustContactsAvgAggregateInputObjectSchema.optional(), _sum: TblCustContactsSumAggregateInputObjectSchema.optional() }).strict();