import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ClientWhereInputObjectSchema as ClientWhereInputObjectSchema } from './objects/ClientWhereInput.schema';
import { ClientOrderByWithAggregationInputObjectSchema as ClientOrderByWithAggregationInputObjectSchema } from './objects/ClientOrderByWithAggregationInput.schema';
import { ClientScalarWhereWithAggregatesInputObjectSchema as ClientScalarWhereWithAggregatesInputObjectSchema } from './objects/ClientScalarWhereWithAggregatesInput.schema';
import { ClientScalarFieldEnumSchema } from './enums/ClientScalarFieldEnum.schema';
import { ClientCountAggregateInputObjectSchema as ClientCountAggregateInputObjectSchema } from './objects/ClientCountAggregateInput.schema';
import { ClientMinAggregateInputObjectSchema as ClientMinAggregateInputObjectSchema } from './objects/ClientMinAggregateInput.schema';
import { ClientMaxAggregateInputObjectSchema as ClientMaxAggregateInputObjectSchema } from './objects/ClientMaxAggregateInput.schema';
import { ClientAvgAggregateInputObjectSchema as ClientAvgAggregateInputObjectSchema } from './objects/ClientAvgAggregateInput.schema';
import { ClientSumAggregateInputObjectSchema as ClientSumAggregateInputObjectSchema } from './objects/ClientSumAggregateInput.schema';

export const ClientGroupBySchema: z.ZodType<Prisma.ClientGroupByArgs> = z.object({ where: ClientWhereInputObjectSchema.optional(), orderBy: z.union([ClientOrderByWithAggregationInputObjectSchema, ClientOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ClientScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClientScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClientCountAggregateInputObjectSchema ]).optional(), _min: ClientMinAggregateInputObjectSchema.optional(), _max: ClientMaxAggregateInputObjectSchema.optional(), _avg: ClientAvgAggregateInputObjectSchema.optional(), _sum: ClientSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ClientGroupByArgs>;

export const ClientGroupByZodSchema = z.object({ where: ClientWhereInputObjectSchema.optional(), orderBy: z.union([ClientOrderByWithAggregationInputObjectSchema, ClientOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ClientScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClientScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClientCountAggregateInputObjectSchema ]).optional(), _min: ClientMinAggregateInputObjectSchema.optional(), _max: ClientMaxAggregateInputObjectSchema.optional(), _avg: ClientAvgAggregateInputObjectSchema.optional(), _sum: ClientSumAggregateInputObjectSchema.optional() }).strict();