import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArTransferDetailWhereInputObjectSchema as ArTransferDetailWhereInputObjectSchema } from './objects/ArTransferDetailWhereInput.schema';
import { ArTransferDetailOrderByWithAggregationInputObjectSchema as ArTransferDetailOrderByWithAggregationInputObjectSchema } from './objects/ArTransferDetailOrderByWithAggregationInput.schema';
import { ArTransferDetailScalarWhereWithAggregatesInputObjectSchema as ArTransferDetailScalarWhereWithAggregatesInputObjectSchema } from './objects/ArTransferDetailScalarWhereWithAggregatesInput.schema';
import { ArTransferDetailScalarFieldEnumSchema } from './enums/ArTransferDetailScalarFieldEnum.schema';
import { ArTransferDetailCountAggregateInputObjectSchema as ArTransferDetailCountAggregateInputObjectSchema } from './objects/ArTransferDetailCountAggregateInput.schema';
import { ArTransferDetailMinAggregateInputObjectSchema as ArTransferDetailMinAggregateInputObjectSchema } from './objects/ArTransferDetailMinAggregateInput.schema';
import { ArTransferDetailMaxAggregateInputObjectSchema as ArTransferDetailMaxAggregateInputObjectSchema } from './objects/ArTransferDetailMaxAggregateInput.schema';
import { ArTransferDetailAvgAggregateInputObjectSchema as ArTransferDetailAvgAggregateInputObjectSchema } from './objects/ArTransferDetailAvgAggregateInput.schema';
import { ArTransferDetailSumAggregateInputObjectSchema as ArTransferDetailSumAggregateInputObjectSchema } from './objects/ArTransferDetailSumAggregateInput.schema';

export const ArTransferDetailGroupBySchema: z.ZodType<Prisma.ArTransferDetailGroupByArgs> = z.object({ where: ArTransferDetailWhereInputObjectSchema.optional(), orderBy: z.union([ArTransferDetailOrderByWithAggregationInputObjectSchema, ArTransferDetailOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArTransferDetailScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArTransferDetailScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArTransferDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransferDetailMinAggregateInputObjectSchema.optional(), _max: ArTransferDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransferDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransferDetailSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArTransferDetailGroupByArgs>;

export const ArTransferDetailGroupByZodSchema = z.object({ where: ArTransferDetailWhereInputObjectSchema.optional(), orderBy: z.union([ArTransferDetailOrderByWithAggregationInputObjectSchema, ArTransferDetailOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArTransferDetailScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArTransferDetailScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArTransferDetailCountAggregateInputObjectSchema ]).optional(), _min: ArTransferDetailMinAggregateInputObjectSchema.optional(), _max: ArTransferDetailMaxAggregateInputObjectSchema.optional(), _avg: ArTransferDetailAvgAggregateInputObjectSchema.optional(), _sum: ArTransferDetailSumAggregateInputObjectSchema.optional() }).strict();