import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AgreementAdvanceWhereInputObjectSchema as AgreementAdvanceWhereInputObjectSchema } from './objects/AgreementAdvanceWhereInput.schema';
import { AgreementAdvanceOrderByWithAggregationInputObjectSchema as AgreementAdvanceOrderByWithAggregationInputObjectSchema } from './objects/AgreementAdvanceOrderByWithAggregationInput.schema';
import { AgreementAdvanceScalarWhereWithAggregatesInputObjectSchema as AgreementAdvanceScalarWhereWithAggregatesInputObjectSchema } from './objects/AgreementAdvanceScalarWhereWithAggregatesInput.schema';
import { AgreementAdvanceScalarFieldEnumSchema } from './enums/AgreementAdvanceScalarFieldEnum.schema';
import { AgreementAdvanceCountAggregateInputObjectSchema as AgreementAdvanceCountAggregateInputObjectSchema } from './objects/AgreementAdvanceCountAggregateInput.schema';
import { AgreementAdvanceMinAggregateInputObjectSchema as AgreementAdvanceMinAggregateInputObjectSchema } from './objects/AgreementAdvanceMinAggregateInput.schema';
import { AgreementAdvanceMaxAggregateInputObjectSchema as AgreementAdvanceMaxAggregateInputObjectSchema } from './objects/AgreementAdvanceMaxAggregateInput.schema';
import { AgreementAdvanceAvgAggregateInputObjectSchema as AgreementAdvanceAvgAggregateInputObjectSchema } from './objects/AgreementAdvanceAvgAggregateInput.schema';
import { AgreementAdvanceSumAggregateInputObjectSchema as AgreementAdvanceSumAggregateInputObjectSchema } from './objects/AgreementAdvanceSumAggregateInput.schema';

export const AgreementAdvanceGroupBySchema: z.ZodType<Prisma.AgreementAdvanceGroupByArgs> = z.object({ where: AgreementAdvanceWhereInputObjectSchema.optional(), orderBy: z.union([AgreementAdvanceOrderByWithAggregationInputObjectSchema, AgreementAdvanceOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementAdvanceScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementAdvanceScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementAdvanceCountAggregateInputObjectSchema ]).optional(), _min: AgreementAdvanceMinAggregateInputObjectSchema.optional(), _max: AgreementAdvanceMaxAggregateInputObjectSchema.optional(), _avg: AgreementAdvanceAvgAggregateInputObjectSchema.optional(), _sum: AgreementAdvanceSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgreementAdvanceGroupByArgs>;

export const AgreementAdvanceGroupByZodSchema = z.object({ where: AgreementAdvanceWhereInputObjectSchema.optional(), orderBy: z.union([AgreementAdvanceOrderByWithAggregationInputObjectSchema, AgreementAdvanceOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementAdvanceScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementAdvanceScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementAdvanceCountAggregateInputObjectSchema ]).optional(), _min: AgreementAdvanceMinAggregateInputObjectSchema.optional(), _max: AgreementAdvanceMaxAggregateInputObjectSchema.optional(), _avg: AgreementAdvanceAvgAggregateInputObjectSchema.optional(), _sum: AgreementAdvanceSumAggregateInputObjectSchema.optional() }).strict();