import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblPersonLoginWhereInputObjectSchema as tblPersonLoginWhereInputObjectSchema } from './objects/tblPersonLoginWhereInput.schema';
import { tblPersonLoginOrderByWithAggregationInputObjectSchema as tblPersonLoginOrderByWithAggregationInputObjectSchema } from './objects/tblPersonLoginOrderByWithAggregationInput.schema';
import { tblPersonLoginScalarWhereWithAggregatesInputObjectSchema as tblPersonLoginScalarWhereWithAggregatesInputObjectSchema } from './objects/tblPersonLoginScalarWhereWithAggregatesInput.schema';
import { TblPersonLoginScalarFieldEnumSchema } from './enums/TblPersonLoginScalarFieldEnum.schema';
import { TblPersonLoginCountAggregateInputObjectSchema as TblPersonLoginCountAggregateInputObjectSchema } from './objects/TblPersonLoginCountAggregateInput.schema';
import { TblPersonLoginMinAggregateInputObjectSchema as TblPersonLoginMinAggregateInputObjectSchema } from './objects/TblPersonLoginMinAggregateInput.schema';
import { TblPersonLoginMaxAggregateInputObjectSchema as TblPersonLoginMaxAggregateInputObjectSchema } from './objects/TblPersonLoginMaxAggregateInput.schema';
import { TblPersonLoginAvgAggregateInputObjectSchema as TblPersonLoginAvgAggregateInputObjectSchema } from './objects/TblPersonLoginAvgAggregateInput.schema';
import { TblPersonLoginSumAggregateInputObjectSchema as TblPersonLoginSumAggregateInputObjectSchema } from './objects/TblPersonLoginSumAggregateInput.schema';

export const tblPersonLoginGroupBySchema: z.ZodType<Prisma.tblPersonLoginGroupByArgs> = z.object({ where: tblPersonLoginWhereInputObjectSchema.optional(), orderBy: z.union([tblPersonLoginOrderByWithAggregationInputObjectSchema, tblPersonLoginOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblPersonLoginScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblPersonLoginScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblPersonLoginCountAggregateInputObjectSchema ]).optional(), _min: TblPersonLoginMinAggregateInputObjectSchema.optional(), _max: TblPersonLoginMaxAggregateInputObjectSchema.optional(), _avg: TblPersonLoginAvgAggregateInputObjectSchema.optional(), _sum: TblPersonLoginSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblPersonLoginGroupByArgs>;

export const tblPersonLoginGroupByZodSchema = z.object({ where: tblPersonLoginWhereInputObjectSchema.optional(), orderBy: z.union([tblPersonLoginOrderByWithAggregationInputObjectSchema, tblPersonLoginOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblPersonLoginScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblPersonLoginScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblPersonLoginCountAggregateInputObjectSchema ]).optional(), _min: TblPersonLoginMinAggregateInputObjectSchema.optional(), _max: TblPersonLoginMaxAggregateInputObjectSchema.optional(), _avg: TblPersonLoginAvgAggregateInputObjectSchema.optional(), _sum: TblPersonLoginSumAggregateInputObjectSchema.optional() }).strict();