import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictXRateExcelNamesWhereInputObjectSchema as dictXRateExcelNamesWhereInputObjectSchema } from './objects/dictXRateExcelNamesWhereInput.schema';
import { dictXRateExcelNamesOrderByWithAggregationInputObjectSchema as dictXRateExcelNamesOrderByWithAggregationInputObjectSchema } from './objects/dictXRateExcelNamesOrderByWithAggregationInput.schema';
import { dictXRateExcelNamesScalarWhereWithAggregatesInputObjectSchema as dictXRateExcelNamesScalarWhereWithAggregatesInputObjectSchema } from './objects/dictXRateExcelNamesScalarWhereWithAggregatesInput.schema';
import { DictXRateExcelNamesScalarFieldEnumSchema } from './enums/DictXRateExcelNamesScalarFieldEnum.schema';
import { DictXRateExcelNamesCountAggregateInputObjectSchema as DictXRateExcelNamesCountAggregateInputObjectSchema } from './objects/DictXRateExcelNamesCountAggregateInput.schema';
import { DictXRateExcelNamesMinAggregateInputObjectSchema as DictXRateExcelNamesMinAggregateInputObjectSchema } from './objects/DictXRateExcelNamesMinAggregateInput.schema';
import { DictXRateExcelNamesMaxAggregateInputObjectSchema as DictXRateExcelNamesMaxAggregateInputObjectSchema } from './objects/DictXRateExcelNamesMaxAggregateInput.schema';

export const dictXRateExcelNamesGroupBySchema: z.ZodType<Prisma.dictXRateExcelNamesGroupByArgs> = z.object({ where: dictXRateExcelNamesWhereInputObjectSchema.optional(), orderBy: z.union([dictXRateExcelNamesOrderByWithAggregationInputObjectSchema, dictXRateExcelNamesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictXRateExcelNamesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictXRateExcelNamesScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictXRateExcelNamesCountAggregateInputObjectSchema ]).optional(), _min: DictXRateExcelNamesMinAggregateInputObjectSchema.optional(), _max: DictXRateExcelNamesMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictXRateExcelNamesGroupByArgs>;

export const dictXRateExcelNamesGroupByZodSchema = z.object({ where: dictXRateExcelNamesWhereInputObjectSchema.optional(), orderBy: z.union([dictXRateExcelNamesOrderByWithAggregationInputObjectSchema, dictXRateExcelNamesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictXRateExcelNamesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictXRateExcelNamesScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictXRateExcelNamesCountAggregateInputObjectSchema ]).optional(), _min: DictXRateExcelNamesMinAggregateInputObjectSchema.optional(), _max: DictXRateExcelNamesMaxAggregateInputObjectSchema.optional() }).strict();