import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AgreementRightWhereInputObjectSchema as AgreementRightWhereInputObjectSchema } from './objects/AgreementRightWhereInput.schema';
import { AgreementRightOrderByWithAggregationInputObjectSchema as AgreementRightOrderByWithAggregationInputObjectSchema } from './objects/AgreementRightOrderByWithAggregationInput.schema';
import { AgreementRightScalarWhereWithAggregatesInputObjectSchema as AgreementRightScalarWhereWithAggregatesInputObjectSchema } from './objects/AgreementRightScalarWhereWithAggregatesInput.schema';
import { AgreementRightScalarFieldEnumSchema } from './enums/AgreementRightScalarFieldEnum.schema';
import { AgreementRightCountAggregateInputObjectSchema as AgreementRightCountAggregateInputObjectSchema } from './objects/AgreementRightCountAggregateInput.schema';
import { AgreementRightMinAggregateInputObjectSchema as AgreementRightMinAggregateInputObjectSchema } from './objects/AgreementRightMinAggregateInput.schema';
import { AgreementRightMaxAggregateInputObjectSchema as AgreementRightMaxAggregateInputObjectSchema } from './objects/AgreementRightMaxAggregateInput.schema';
import { AgreementRightAvgAggregateInputObjectSchema as AgreementRightAvgAggregateInputObjectSchema } from './objects/AgreementRightAvgAggregateInput.schema';
import { AgreementRightSumAggregateInputObjectSchema as AgreementRightSumAggregateInputObjectSchema } from './objects/AgreementRightSumAggregateInput.schema';

export const AgreementRightGroupBySchema: z.ZodType<Prisma.AgreementRightGroupByArgs> = z.object({ where: AgreementRightWhereInputObjectSchema.optional(), orderBy: z.union([AgreementRightOrderByWithAggregationInputObjectSchema, AgreementRightOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementRightScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementRightScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementRightCountAggregateInputObjectSchema ]).optional(), _min: AgreementRightMinAggregateInputObjectSchema.optional(), _max: AgreementRightMaxAggregateInputObjectSchema.optional(), _avg: AgreementRightAvgAggregateInputObjectSchema.optional(), _sum: AgreementRightSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgreementRightGroupByArgs>;

export const AgreementRightGroupByZodSchema = z.object({ where: AgreementRightWhereInputObjectSchema.optional(), orderBy: z.union([AgreementRightOrderByWithAggregationInputObjectSchema, AgreementRightOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementRightScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementRightScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementRightCountAggregateInputObjectSchema ]).optional(), _min: AgreementRightMinAggregateInputObjectSchema.optional(), _max: AgreementRightMaxAggregateInputObjectSchema.optional(), _avg: AgreementRightAvgAggregateInputObjectSchema.optional(), _sum: AgreementRightSumAggregateInputObjectSchema.optional() }).strict();