import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PublisherContactWhereInputObjectSchema as PublisherContactWhereInputObjectSchema } from './objects/PublisherContactWhereInput.schema';
import { PublisherContactOrderByWithAggregationInputObjectSchema as PublisherContactOrderByWithAggregationInputObjectSchema } from './objects/PublisherContactOrderByWithAggregationInput.schema';
import { PublisherContactScalarWhereWithAggregatesInputObjectSchema as PublisherContactScalarWhereWithAggregatesInputObjectSchema } from './objects/PublisherContactScalarWhereWithAggregatesInput.schema';
import { PublisherContactScalarFieldEnumSchema } from './enums/PublisherContactScalarFieldEnum.schema';
import { PublisherContactCountAggregateInputObjectSchema as PublisherContactCountAggregateInputObjectSchema } from './objects/PublisherContactCountAggregateInput.schema';
import { PublisherContactMinAggregateInputObjectSchema as PublisherContactMinAggregateInputObjectSchema } from './objects/PublisherContactMinAggregateInput.schema';
import { PublisherContactMaxAggregateInputObjectSchema as PublisherContactMaxAggregateInputObjectSchema } from './objects/PublisherContactMaxAggregateInput.schema';
import { PublisherContactAvgAggregateInputObjectSchema as PublisherContactAvgAggregateInputObjectSchema } from './objects/PublisherContactAvgAggregateInput.schema';
import { PublisherContactSumAggregateInputObjectSchema as PublisherContactSumAggregateInputObjectSchema } from './objects/PublisherContactSumAggregateInput.schema';

export const PublisherContactGroupBySchema: z.ZodType<Prisma.PublisherContactGroupByArgs> = z.object({ where: PublisherContactWhereInputObjectSchema.optional(), orderBy: z.union([PublisherContactOrderByWithAggregationInputObjectSchema, PublisherContactOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PublisherContactScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PublisherContactScalarFieldEnumSchema), _count: z.union([ z.literal(true), PublisherContactCountAggregateInputObjectSchema ]).optional(), _min: PublisherContactMinAggregateInputObjectSchema.optional(), _max: PublisherContactMaxAggregateInputObjectSchema.optional(), _avg: PublisherContactAvgAggregateInputObjectSchema.optional(), _sum: PublisherContactSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PublisherContactGroupByArgs>;

export const PublisherContactGroupByZodSchema = z.object({ where: PublisherContactWhereInputObjectSchema.optional(), orderBy: z.union([PublisherContactOrderByWithAggregationInputObjectSchema, PublisherContactOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PublisherContactScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PublisherContactScalarFieldEnumSchema), _count: z.union([ z.literal(true), PublisherContactCountAggregateInputObjectSchema ]).optional(), _min: PublisherContactMinAggregateInputObjectSchema.optional(), _max: PublisherContactMaxAggregateInputObjectSchema.optional(), _avg: PublisherContactAvgAggregateInputObjectSchema.optional(), _sum: PublisherContactSumAggregateInputObjectSchema.optional() }).strict();