import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictCoverFormatWhereInputObjectSchema as dictCoverFormatWhereInputObjectSchema } from './objects/dictCoverFormatWhereInput.schema';
import { dictCoverFormatOrderByWithAggregationInputObjectSchema as dictCoverFormatOrderByWithAggregationInputObjectSchema } from './objects/dictCoverFormatOrderByWithAggregationInput.schema';
import { dictCoverFormatScalarWhereWithAggregatesInputObjectSchema as dictCoverFormatScalarWhereWithAggregatesInputObjectSchema } from './objects/dictCoverFormatScalarWhereWithAggregatesInput.schema';
import { DictCoverFormatScalarFieldEnumSchema } from './enums/DictCoverFormatScalarFieldEnum.schema';
import { DictCoverFormatCountAggregateInputObjectSchema as DictCoverFormatCountAggregateInputObjectSchema } from './objects/DictCoverFormatCountAggregateInput.schema';
import { DictCoverFormatMinAggregateInputObjectSchema as DictCoverFormatMinAggregateInputObjectSchema } from './objects/DictCoverFormatMinAggregateInput.schema';
import { DictCoverFormatMaxAggregateInputObjectSchema as DictCoverFormatMaxAggregateInputObjectSchema } from './objects/DictCoverFormatMaxAggregateInput.schema';
import { DictCoverFormatAvgAggregateInputObjectSchema as DictCoverFormatAvgAggregateInputObjectSchema } from './objects/DictCoverFormatAvgAggregateInput.schema';
import { DictCoverFormatSumAggregateInputObjectSchema as DictCoverFormatSumAggregateInputObjectSchema } from './objects/DictCoverFormatSumAggregateInput.schema';

export const dictCoverFormatGroupBySchema: z.ZodType<Prisma.dictCoverFormatGroupByArgs> = z.object({ where: dictCoverFormatWhereInputObjectSchema.optional(), orderBy: z.union([dictCoverFormatOrderByWithAggregationInputObjectSchema, dictCoverFormatOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictCoverFormatScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictCoverFormatScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictCoverFormatCountAggregateInputObjectSchema ]).optional(), _min: DictCoverFormatMinAggregateInputObjectSchema.optional(), _max: DictCoverFormatMaxAggregateInputObjectSchema.optional(), _avg: DictCoverFormatAvgAggregateInputObjectSchema.optional(), _sum: DictCoverFormatSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictCoverFormatGroupByArgs>;

export const dictCoverFormatGroupByZodSchema = z.object({ where: dictCoverFormatWhereInputObjectSchema.optional(), orderBy: z.union([dictCoverFormatOrderByWithAggregationInputObjectSchema, dictCoverFormatOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictCoverFormatScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictCoverFormatScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictCoverFormatCountAggregateInputObjectSchema ]).optional(), _min: DictCoverFormatMinAggregateInputObjectSchema.optional(), _max: DictCoverFormatMaxAggregateInputObjectSchema.optional(), _avg: DictCoverFormatAvgAggregateInputObjectSchema.optional(), _sum: DictCoverFormatSumAggregateInputObjectSchema.optional() }).strict();