import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CurrencyDictionaryWhereInputObjectSchema as CurrencyDictionaryWhereInputObjectSchema } from './objects/CurrencyDictionaryWhereInput.schema';
import { CurrencyDictionaryOrderByWithAggregationInputObjectSchema as CurrencyDictionaryOrderByWithAggregationInputObjectSchema } from './objects/CurrencyDictionaryOrderByWithAggregationInput.schema';
import { CurrencyDictionaryScalarWhereWithAggregatesInputObjectSchema as CurrencyDictionaryScalarWhereWithAggregatesInputObjectSchema } from './objects/CurrencyDictionaryScalarWhereWithAggregatesInput.schema';
import { CurrencyDictionaryScalarFieldEnumSchema } from './enums/CurrencyDictionaryScalarFieldEnum.schema';
import { CurrencyDictionaryCountAggregateInputObjectSchema as CurrencyDictionaryCountAggregateInputObjectSchema } from './objects/CurrencyDictionaryCountAggregateInput.schema';
import { CurrencyDictionaryMinAggregateInputObjectSchema as CurrencyDictionaryMinAggregateInputObjectSchema } from './objects/CurrencyDictionaryMinAggregateInput.schema';
import { CurrencyDictionaryMaxAggregateInputObjectSchema as CurrencyDictionaryMaxAggregateInputObjectSchema } from './objects/CurrencyDictionaryMaxAggregateInput.schema';
import { CurrencyDictionaryAvgAggregateInputObjectSchema as CurrencyDictionaryAvgAggregateInputObjectSchema } from './objects/CurrencyDictionaryAvgAggregateInput.schema';
import { CurrencyDictionarySumAggregateInputObjectSchema as CurrencyDictionarySumAggregateInputObjectSchema } from './objects/CurrencyDictionarySumAggregateInput.schema';

export const CurrencyDictionaryGroupBySchema: z.ZodType<Prisma.CurrencyDictionaryGroupByArgs> = z.object({ where: CurrencyDictionaryWhereInputObjectSchema.optional(), orderBy: z.union([CurrencyDictionaryOrderByWithAggregationInputObjectSchema, CurrencyDictionaryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CurrencyDictionaryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CurrencyDictionaryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CurrencyDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CurrencyDictionaryMinAggregateInputObjectSchema.optional(), _max: CurrencyDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CurrencyDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CurrencyDictionarySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CurrencyDictionaryGroupByArgs>;

export const CurrencyDictionaryGroupByZodSchema = z.object({ where: CurrencyDictionaryWhereInputObjectSchema.optional(), orderBy: z.union([CurrencyDictionaryOrderByWithAggregationInputObjectSchema, CurrencyDictionaryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CurrencyDictionaryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CurrencyDictionaryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CurrencyDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CurrencyDictionaryMinAggregateInputObjectSchema.optional(), _max: CurrencyDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CurrencyDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CurrencyDictionarySumAggregateInputObjectSchema.optional() }).strict();