import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TaxResidenceSendWhereInputObjectSchema as TaxResidenceSendWhereInputObjectSchema } from './objects/TaxResidenceSendWhereInput.schema';
import { TaxResidenceSendOrderByWithAggregationInputObjectSchema as TaxResidenceSendOrderByWithAggregationInputObjectSchema } from './objects/TaxResidenceSendOrderByWithAggregationInput.schema';
import { TaxResidenceSendScalarWhereWithAggregatesInputObjectSchema as TaxResidenceSendScalarWhereWithAggregatesInputObjectSchema } from './objects/TaxResidenceSendScalarWhereWithAggregatesInput.schema';
import { TaxResidenceSendScalarFieldEnumSchema } from './enums/TaxResidenceSendScalarFieldEnum.schema';
import { TaxResidenceSendCountAggregateInputObjectSchema as TaxResidenceSendCountAggregateInputObjectSchema } from './objects/TaxResidenceSendCountAggregateInput.schema';
import { TaxResidenceSendMinAggregateInputObjectSchema as TaxResidenceSendMinAggregateInputObjectSchema } from './objects/TaxResidenceSendMinAggregateInput.schema';
import { TaxResidenceSendMaxAggregateInputObjectSchema as TaxResidenceSendMaxAggregateInputObjectSchema } from './objects/TaxResidenceSendMaxAggregateInput.schema';
import { TaxResidenceSendAvgAggregateInputObjectSchema as TaxResidenceSendAvgAggregateInputObjectSchema } from './objects/TaxResidenceSendAvgAggregateInput.schema';
import { TaxResidenceSendSumAggregateInputObjectSchema as TaxResidenceSendSumAggregateInputObjectSchema } from './objects/TaxResidenceSendSumAggregateInput.schema';

export const TaxResidenceSendGroupBySchema: z.ZodType<Prisma.TaxResidenceSendGroupByArgs> = z.object({ where: TaxResidenceSendWhereInputObjectSchema.optional(), orderBy: z.union([TaxResidenceSendOrderByWithAggregationInputObjectSchema, TaxResidenceSendOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaxResidenceSendScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaxResidenceSendScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaxResidenceSendCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceSendMinAggregateInputObjectSchema.optional(), _max: TaxResidenceSendMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceSendAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceSendSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TaxResidenceSendGroupByArgs>;

export const TaxResidenceSendGroupByZodSchema = z.object({ where: TaxResidenceSendWhereInputObjectSchema.optional(), orderBy: z.union([TaxResidenceSendOrderByWithAggregationInputObjectSchema, TaxResidenceSendOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TaxResidenceSendScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TaxResidenceSendScalarFieldEnumSchema), _count: z.union([ z.literal(true), TaxResidenceSendCountAggregateInputObjectSchema ]).optional(), _min: TaxResidenceSendMinAggregateInputObjectSchema.optional(), _max: TaxResidenceSendMaxAggregateInputObjectSchema.optional(), _avg: TaxResidenceSendAvgAggregateInputObjectSchema.optional(), _sum: TaxResidenceSendSumAggregateInputObjectSchema.optional() }).strict();