import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArTransactionTypeWhereInputObjectSchema as ArTransactionTypeWhereInputObjectSchema } from './objects/ArTransactionTypeWhereInput.schema';
import { ArTransactionTypeOrderByWithAggregationInputObjectSchema as ArTransactionTypeOrderByWithAggregationInputObjectSchema } from './objects/ArTransactionTypeOrderByWithAggregationInput.schema';
import { ArTransactionTypeScalarWhereWithAggregatesInputObjectSchema as ArTransactionTypeScalarWhereWithAggregatesInputObjectSchema } from './objects/ArTransactionTypeScalarWhereWithAggregatesInput.schema';
import { ArTransactionTypeScalarFieldEnumSchema } from './enums/ArTransactionTypeScalarFieldEnum.schema';
import { ArTransactionTypeCountAggregateInputObjectSchema as ArTransactionTypeCountAggregateInputObjectSchema } from './objects/ArTransactionTypeCountAggregateInput.schema';
import { ArTransactionTypeMinAggregateInputObjectSchema as ArTransactionTypeMinAggregateInputObjectSchema } from './objects/ArTransactionTypeMinAggregateInput.schema';
import { ArTransactionTypeMaxAggregateInputObjectSchema as ArTransactionTypeMaxAggregateInputObjectSchema } from './objects/ArTransactionTypeMaxAggregateInput.schema';
import { ArTransactionTypeAvgAggregateInputObjectSchema as ArTransactionTypeAvgAggregateInputObjectSchema } from './objects/ArTransactionTypeAvgAggregateInput.schema';
import { ArTransactionTypeSumAggregateInputObjectSchema as ArTransactionTypeSumAggregateInputObjectSchema } from './objects/ArTransactionTypeSumAggregateInput.schema';

export const ArTransactionTypeGroupBySchema: z.ZodType<Prisma.ArTransactionTypeGroupByArgs> = z.object({ where: ArTransactionTypeWhereInputObjectSchema.optional(), orderBy: z.union([ArTransactionTypeOrderByWithAggregationInputObjectSchema, ArTransactionTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArTransactionTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArTransactionTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArTransactionTypeCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionTypeMinAggregateInputObjectSchema.optional(), _max: ArTransactionTypeMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionTypeAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArTransactionTypeGroupByArgs>;

export const ArTransactionTypeGroupByZodSchema = z.object({ where: ArTransactionTypeWhereInputObjectSchema.optional(), orderBy: z.union([ArTransactionTypeOrderByWithAggregationInputObjectSchema, ArTransactionTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArTransactionTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArTransactionTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArTransactionTypeCountAggregateInputObjectSchema ]).optional(), _min: ArTransactionTypeMinAggregateInputObjectSchema.optional(), _max: ArTransactionTypeMaxAggregateInputObjectSchema.optional(), _avg: ArTransactionTypeAvgAggregateInputObjectSchema.optional(), _sum: ArTransactionTypeSumAggregateInputObjectSchema.optional() }).strict();