import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AgreementRoyRateWhereInputObjectSchema as AgreementRoyRateWhereInputObjectSchema } from './objects/AgreementRoyRateWhereInput.schema';
import { AgreementRoyRateOrderByWithAggregationInputObjectSchema as AgreementRoyRateOrderByWithAggregationInputObjectSchema } from './objects/AgreementRoyRateOrderByWithAggregationInput.schema';
import { AgreementRoyRateScalarWhereWithAggregatesInputObjectSchema as AgreementRoyRateScalarWhereWithAggregatesInputObjectSchema } from './objects/AgreementRoyRateScalarWhereWithAggregatesInput.schema';
import { AgreementRoyRateScalarFieldEnumSchema } from './enums/AgreementRoyRateScalarFieldEnum.schema';
import { AgreementRoyRateCountAggregateInputObjectSchema as AgreementRoyRateCountAggregateInputObjectSchema } from './objects/AgreementRoyRateCountAggregateInput.schema';
import { AgreementRoyRateMinAggregateInputObjectSchema as AgreementRoyRateMinAggregateInputObjectSchema } from './objects/AgreementRoyRateMinAggregateInput.schema';
import { AgreementRoyRateMaxAggregateInputObjectSchema as AgreementRoyRateMaxAggregateInputObjectSchema } from './objects/AgreementRoyRateMaxAggregateInput.schema';
import { AgreementRoyRateAvgAggregateInputObjectSchema as AgreementRoyRateAvgAggregateInputObjectSchema } from './objects/AgreementRoyRateAvgAggregateInput.schema';
import { AgreementRoyRateSumAggregateInputObjectSchema as AgreementRoyRateSumAggregateInputObjectSchema } from './objects/AgreementRoyRateSumAggregateInput.schema';

export const AgreementRoyRateGroupBySchema: z.ZodType<Prisma.AgreementRoyRateGroupByArgs> = z.object({ where: AgreementRoyRateWhereInputObjectSchema.optional(), orderBy: z.union([AgreementRoyRateOrderByWithAggregationInputObjectSchema, AgreementRoyRateOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementRoyRateScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementRoyRateScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementRoyRateCountAggregateInputObjectSchema ]).optional(), _min: AgreementRoyRateMinAggregateInputObjectSchema.optional(), _max: AgreementRoyRateMaxAggregateInputObjectSchema.optional(), _avg: AgreementRoyRateAvgAggregateInputObjectSchema.optional(), _sum: AgreementRoyRateSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgreementRoyRateGroupByArgs>;

export const AgreementRoyRateGroupByZodSchema = z.object({ where: AgreementRoyRateWhereInputObjectSchema.optional(), orderBy: z.union([AgreementRoyRateOrderByWithAggregationInputObjectSchema, AgreementRoyRateOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgreementRoyRateScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgreementRoyRateScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgreementRoyRateCountAggregateInputObjectSchema ]).optional(), _min: AgreementRoyRateMinAggregateInputObjectSchema.optional(), _max: AgreementRoyRateMaxAggregateInputObjectSchema.optional(), _avg: AgreementRoyRateAvgAggregateInputObjectSchema.optional(), _sum: AgreementRoyRateSumAggregateInputObjectSchema.optional() }).strict();