import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { BalanceAdjustmentWhereInputObjectSchema as BalanceAdjustmentWhereInputObjectSchema } from './objects/BalanceAdjustmentWhereInput.schema';
import { BalanceAdjustmentOrderByWithAggregationInputObjectSchema as BalanceAdjustmentOrderByWithAggregationInputObjectSchema } from './objects/BalanceAdjustmentOrderByWithAggregationInput.schema';
import { BalanceAdjustmentScalarWhereWithAggregatesInputObjectSchema as BalanceAdjustmentScalarWhereWithAggregatesInputObjectSchema } from './objects/BalanceAdjustmentScalarWhereWithAggregatesInput.schema';
import { BalanceAdjustmentScalarFieldEnumSchema } from './enums/BalanceAdjustmentScalarFieldEnum.schema';
import { BalanceAdjustmentCountAggregateInputObjectSchema as BalanceAdjustmentCountAggregateInputObjectSchema } from './objects/BalanceAdjustmentCountAggregateInput.schema';
import { BalanceAdjustmentMinAggregateInputObjectSchema as BalanceAdjustmentMinAggregateInputObjectSchema } from './objects/BalanceAdjustmentMinAggregateInput.schema';
import { BalanceAdjustmentMaxAggregateInputObjectSchema as BalanceAdjustmentMaxAggregateInputObjectSchema } from './objects/BalanceAdjustmentMaxAggregateInput.schema';
import { BalanceAdjustmentAvgAggregateInputObjectSchema as BalanceAdjustmentAvgAggregateInputObjectSchema } from './objects/BalanceAdjustmentAvgAggregateInput.schema';
import { BalanceAdjustmentSumAggregateInputObjectSchema as BalanceAdjustmentSumAggregateInputObjectSchema } from './objects/BalanceAdjustmentSumAggregateInput.schema';

export const BalanceAdjustmentGroupBySchema: z.ZodType<Prisma.BalanceAdjustmentGroupByArgs> = z.object({ where: BalanceAdjustmentWhereInputObjectSchema.optional(), orderBy: z.union([BalanceAdjustmentOrderByWithAggregationInputObjectSchema, BalanceAdjustmentOrderByWithAggregationInputObjectSchema.array()]).optional(), having: BalanceAdjustmentScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(BalanceAdjustmentScalarFieldEnumSchema), _count: z.union([ z.literal(true), BalanceAdjustmentCountAggregateInputObjectSchema ]).optional(), _min: BalanceAdjustmentMinAggregateInputObjectSchema.optional(), _max: BalanceAdjustmentMaxAggregateInputObjectSchema.optional(), _avg: BalanceAdjustmentAvgAggregateInputObjectSchema.optional(), _sum: BalanceAdjustmentSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.BalanceAdjustmentGroupByArgs>;

export const BalanceAdjustmentGroupByZodSchema = z.object({ where: BalanceAdjustmentWhereInputObjectSchema.optional(), orderBy: z.union([BalanceAdjustmentOrderByWithAggregationInputObjectSchema, BalanceAdjustmentOrderByWithAggregationInputObjectSchema.array()]).optional(), having: BalanceAdjustmentScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(BalanceAdjustmentScalarFieldEnumSchema), _count: z.union([ z.literal(true), BalanceAdjustmentCountAggregateInputObjectSchema ]).optional(), _min: BalanceAdjustmentMinAggregateInputObjectSchema.optional(), _max: BalanceAdjustmentMaxAggregateInputObjectSchema.optional(), _avg: BalanceAdjustmentAvgAggregateInputObjectSchema.optional(), _sum: BalanceAdjustmentSumAggregateInputObjectSchema.optional() }).strict();