import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tmpKursyXMLWhereInputObjectSchema as tmpKursyXMLWhereInputObjectSchema } from './objects/tmpKursyXMLWhereInput.schema';
import { tmpKursyXMLOrderByWithAggregationInputObjectSchema as tmpKursyXMLOrderByWithAggregationInputObjectSchema } from './objects/tmpKursyXMLOrderByWithAggregationInput.schema';
import { tmpKursyXMLScalarWhereWithAggregatesInputObjectSchema as tmpKursyXMLScalarWhereWithAggregatesInputObjectSchema } from './objects/tmpKursyXMLScalarWhereWithAggregatesInput.schema';
import { TmpKursyXMLScalarFieldEnumSchema } from './enums/TmpKursyXMLScalarFieldEnum.schema';
import { TmpKursyXMLCountAggregateInputObjectSchema as TmpKursyXMLCountAggregateInputObjectSchema } from './objects/TmpKursyXMLCountAggregateInput.schema';
import { TmpKursyXMLMinAggregateInputObjectSchema as TmpKursyXMLMinAggregateInputObjectSchema } from './objects/TmpKursyXMLMinAggregateInput.schema';
import { TmpKursyXMLMaxAggregateInputObjectSchema as TmpKursyXMLMaxAggregateInputObjectSchema } from './objects/TmpKursyXMLMaxAggregateInput.schema';
import { TmpKursyXMLAvgAggregateInputObjectSchema as TmpKursyXMLAvgAggregateInputObjectSchema } from './objects/TmpKursyXMLAvgAggregateInput.schema';
import { TmpKursyXMLSumAggregateInputObjectSchema as TmpKursyXMLSumAggregateInputObjectSchema } from './objects/TmpKursyXMLSumAggregateInput.schema';

export const tmpKursyXMLGroupBySchema: z.ZodType<Prisma.tmpKursyXMLGroupByArgs> = z.object({ where: tmpKursyXMLWhereInputObjectSchema.optional(), orderBy: z.union([tmpKursyXMLOrderByWithAggregationInputObjectSchema, tmpKursyXMLOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tmpKursyXMLScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TmpKursyXMLScalarFieldEnumSchema), _count: z.union([ z.literal(true), TmpKursyXMLCountAggregateInputObjectSchema ]).optional(), _min: TmpKursyXMLMinAggregateInputObjectSchema.optional(), _max: TmpKursyXMLMaxAggregateInputObjectSchema.optional(), _avg: TmpKursyXMLAvgAggregateInputObjectSchema.optional(), _sum: TmpKursyXMLSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tmpKursyXMLGroupByArgs>;

export const tmpKursyXMLGroupByZodSchema = z.object({ where: tmpKursyXMLWhereInputObjectSchema.optional(), orderBy: z.union([tmpKursyXMLOrderByWithAggregationInputObjectSchema, tmpKursyXMLOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tmpKursyXMLScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TmpKursyXMLScalarFieldEnumSchema), _count: z.union([ z.literal(true), TmpKursyXMLCountAggregateInputObjectSchema ]).optional(), _min: TmpKursyXMLMinAggregateInputObjectSchema.optional(), _max: TmpKursyXMLMaxAggregateInputObjectSchema.optional(), _avg: TmpKursyXMLAvgAggregateInputObjectSchema.optional(), _sum: TmpKursyXMLSumAggregateInputObjectSchema.optional() }).strict();