import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblTitSubClassWhereInputObjectSchema as tblTitSubClassWhereInputObjectSchema } from './objects/tblTitSubClassWhereInput.schema';
import { tblTitSubClassOrderByWithAggregationInputObjectSchema as tblTitSubClassOrderByWithAggregationInputObjectSchema } from './objects/tblTitSubClassOrderByWithAggregationInput.schema';
import { tblTitSubClassScalarWhereWithAggregatesInputObjectSchema as tblTitSubClassScalarWhereWithAggregatesInputObjectSchema } from './objects/tblTitSubClassScalarWhereWithAggregatesInput.schema';
import { TblTitSubClassScalarFieldEnumSchema } from './enums/TblTitSubClassScalarFieldEnum.schema';
import { TblTitSubClassCountAggregateInputObjectSchema as TblTitSubClassCountAggregateInputObjectSchema } from './objects/TblTitSubClassCountAggregateInput.schema';
import { TblTitSubClassMinAggregateInputObjectSchema as TblTitSubClassMinAggregateInputObjectSchema } from './objects/TblTitSubClassMinAggregateInput.schema';
import { TblTitSubClassMaxAggregateInputObjectSchema as TblTitSubClassMaxAggregateInputObjectSchema } from './objects/TblTitSubClassMaxAggregateInput.schema';
import { TblTitSubClassAvgAggregateInputObjectSchema as TblTitSubClassAvgAggregateInputObjectSchema } from './objects/TblTitSubClassAvgAggregateInput.schema';
import { TblTitSubClassSumAggregateInputObjectSchema as TblTitSubClassSumAggregateInputObjectSchema } from './objects/TblTitSubClassSumAggregateInput.schema';

export const tblTitSubClassGroupBySchema: z.ZodType<Prisma.tblTitSubClassGroupByArgs> = z.object({ where: tblTitSubClassWhereInputObjectSchema.optional(), orderBy: z.union([tblTitSubClassOrderByWithAggregationInputObjectSchema, tblTitSubClassOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblTitSubClassScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblTitSubClassScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblTitSubClassCountAggregateInputObjectSchema ]).optional(), _min: TblTitSubClassMinAggregateInputObjectSchema.optional(), _max: TblTitSubClassMaxAggregateInputObjectSchema.optional(), _avg: TblTitSubClassAvgAggregateInputObjectSchema.optional(), _sum: TblTitSubClassSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblTitSubClassGroupByArgs>;

export const tblTitSubClassGroupByZodSchema = z.object({ where: tblTitSubClassWhereInputObjectSchema.optional(), orderBy: z.union([tblTitSubClassOrderByWithAggregationInputObjectSchema, tblTitSubClassOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblTitSubClassScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblTitSubClassScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblTitSubClassCountAggregateInputObjectSchema ]).optional(), _min: TblTitSubClassMinAggregateInputObjectSchema.optional(), _max: TblTitSubClassMaxAggregateInputObjectSchema.optional(), _avg: TblTitSubClassAvgAggregateInputObjectSchema.optional(), _sum: TblTitSubClassSumAggregateInputObjectSchema.optional() }).strict();