import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictRoyPriceTypeWhereInputObjectSchema as dictRoyPriceTypeWhereInputObjectSchema } from './objects/dictRoyPriceTypeWhereInput.schema';
import { dictRoyPriceTypeOrderByWithAggregationInputObjectSchema as dictRoyPriceTypeOrderByWithAggregationInputObjectSchema } from './objects/dictRoyPriceTypeOrderByWithAggregationInput.schema';
import { dictRoyPriceTypeScalarWhereWithAggregatesInputObjectSchema as dictRoyPriceTypeScalarWhereWithAggregatesInputObjectSchema } from './objects/dictRoyPriceTypeScalarWhereWithAggregatesInput.schema';
import { DictRoyPriceTypeScalarFieldEnumSchema } from './enums/DictRoyPriceTypeScalarFieldEnum.schema';
import { DictRoyPriceTypeCountAggregateInputObjectSchema as DictRoyPriceTypeCountAggregateInputObjectSchema } from './objects/DictRoyPriceTypeCountAggregateInput.schema';
import { DictRoyPriceTypeMinAggregateInputObjectSchema as DictRoyPriceTypeMinAggregateInputObjectSchema } from './objects/DictRoyPriceTypeMinAggregateInput.schema';
import { DictRoyPriceTypeMaxAggregateInputObjectSchema as DictRoyPriceTypeMaxAggregateInputObjectSchema } from './objects/DictRoyPriceTypeMaxAggregateInput.schema';
import { DictRoyPriceTypeAvgAggregateInputObjectSchema as DictRoyPriceTypeAvgAggregateInputObjectSchema } from './objects/DictRoyPriceTypeAvgAggregateInput.schema';
import { DictRoyPriceTypeSumAggregateInputObjectSchema as DictRoyPriceTypeSumAggregateInputObjectSchema } from './objects/DictRoyPriceTypeSumAggregateInput.schema';

export const dictRoyPriceTypeGroupBySchema: z.ZodType<Prisma.dictRoyPriceTypeGroupByArgs> = z.object({ where: dictRoyPriceTypeWhereInputObjectSchema.optional(), orderBy: z.union([dictRoyPriceTypeOrderByWithAggregationInputObjectSchema, dictRoyPriceTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictRoyPriceTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictRoyPriceTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictRoyPriceTypeCountAggregateInputObjectSchema ]).optional(), _min: DictRoyPriceTypeMinAggregateInputObjectSchema.optional(), _max: DictRoyPriceTypeMaxAggregateInputObjectSchema.optional(), _avg: DictRoyPriceTypeAvgAggregateInputObjectSchema.optional(), _sum: DictRoyPriceTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictRoyPriceTypeGroupByArgs>;

export const dictRoyPriceTypeGroupByZodSchema = z.object({ where: dictRoyPriceTypeWhereInputObjectSchema.optional(), orderBy: z.union([dictRoyPriceTypeOrderByWithAggregationInputObjectSchema, dictRoyPriceTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictRoyPriceTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictRoyPriceTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictRoyPriceTypeCountAggregateInputObjectSchema ]).optional(), _min: DictRoyPriceTypeMinAggregateInputObjectSchema.optional(), _max: DictRoyPriceTypeMaxAggregateInputObjectSchema.optional(), _avg: DictRoyPriceTypeAvgAggregateInputObjectSchema.optional(), _sum: DictRoyPriceTypeSumAggregateInputObjectSchema.optional() }).strict();