import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictRoyAccountIntervalWhereInputObjectSchema as dictRoyAccountIntervalWhereInputObjectSchema } from './objects/dictRoyAccountIntervalWhereInput.schema';
import { dictRoyAccountIntervalOrderByWithAggregationInputObjectSchema as dictRoyAccountIntervalOrderByWithAggregationInputObjectSchema } from './objects/dictRoyAccountIntervalOrderByWithAggregationInput.schema';
import { dictRoyAccountIntervalScalarWhereWithAggregatesInputObjectSchema as dictRoyAccountIntervalScalarWhereWithAggregatesInputObjectSchema } from './objects/dictRoyAccountIntervalScalarWhereWithAggregatesInput.schema';
import { DictRoyAccountIntervalScalarFieldEnumSchema } from './enums/DictRoyAccountIntervalScalarFieldEnum.schema';
import { DictRoyAccountIntervalCountAggregateInputObjectSchema as DictRoyAccountIntervalCountAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalCountAggregateInput.schema';
import { DictRoyAccountIntervalMinAggregateInputObjectSchema as DictRoyAccountIntervalMinAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalMinAggregateInput.schema';
import { DictRoyAccountIntervalMaxAggregateInputObjectSchema as DictRoyAccountIntervalMaxAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalMaxAggregateInput.schema';
import { DictRoyAccountIntervalAvgAggregateInputObjectSchema as DictRoyAccountIntervalAvgAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalAvgAggregateInput.schema';
import { DictRoyAccountIntervalSumAggregateInputObjectSchema as DictRoyAccountIntervalSumAggregateInputObjectSchema } from './objects/DictRoyAccountIntervalSumAggregateInput.schema';

export const dictRoyAccountIntervalGroupBySchema: z.ZodType<Prisma.dictRoyAccountIntervalGroupByArgs> = z.object({ where: dictRoyAccountIntervalWhereInputObjectSchema.optional(), orderBy: z.union([dictRoyAccountIntervalOrderByWithAggregationInputObjectSchema, dictRoyAccountIntervalOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictRoyAccountIntervalScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictRoyAccountIntervalScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictRoyAccountIntervalCountAggregateInputObjectSchema ]).optional(), _min: DictRoyAccountIntervalMinAggregateInputObjectSchema.optional(), _max: DictRoyAccountIntervalMaxAggregateInputObjectSchema.optional(), _avg: DictRoyAccountIntervalAvgAggregateInputObjectSchema.optional(), _sum: DictRoyAccountIntervalSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictRoyAccountIntervalGroupByArgs>;

export const dictRoyAccountIntervalGroupByZodSchema = z.object({ where: dictRoyAccountIntervalWhereInputObjectSchema.optional(), orderBy: z.union([dictRoyAccountIntervalOrderByWithAggregationInputObjectSchema, dictRoyAccountIntervalOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictRoyAccountIntervalScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictRoyAccountIntervalScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictRoyAccountIntervalCountAggregateInputObjectSchema ]).optional(), _min: DictRoyAccountIntervalMinAggregateInputObjectSchema.optional(), _max: DictRoyAccountIntervalMaxAggregateInputObjectSchema.optional(), _avg: DictRoyAccountIntervalAvgAggregateInputObjectSchema.optional(), _sum: DictRoyAccountIntervalSumAggregateInputObjectSchema.optional() }).strict();