import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictMissRoyExcludeReasonWhereInputObjectSchema as dictMissRoyExcludeReasonWhereInputObjectSchema } from './objects/dictMissRoyExcludeReasonWhereInput.schema';
import { dictMissRoyExcludeReasonOrderByWithAggregationInputObjectSchema as dictMissRoyExcludeReasonOrderByWithAggregationInputObjectSchema } from './objects/dictMissRoyExcludeReasonOrderByWithAggregationInput.schema';
import { dictMissRoyExcludeReasonScalarWhereWithAggregatesInputObjectSchema as dictMissRoyExcludeReasonScalarWhereWithAggregatesInputObjectSchema } from './objects/dictMissRoyExcludeReasonScalarWhereWithAggregatesInput.schema';
import { DictMissRoyExcludeReasonScalarFieldEnumSchema } from './enums/DictMissRoyExcludeReasonScalarFieldEnum.schema';
import { DictMissRoyExcludeReasonCountAggregateInputObjectSchema as DictMissRoyExcludeReasonCountAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonCountAggregateInput.schema';
import { DictMissRoyExcludeReasonMinAggregateInputObjectSchema as DictMissRoyExcludeReasonMinAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonMinAggregateInput.schema';
import { DictMissRoyExcludeReasonMaxAggregateInputObjectSchema as DictMissRoyExcludeReasonMaxAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonMaxAggregateInput.schema';
import { DictMissRoyExcludeReasonAvgAggregateInputObjectSchema as DictMissRoyExcludeReasonAvgAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonAvgAggregateInput.schema';
import { DictMissRoyExcludeReasonSumAggregateInputObjectSchema as DictMissRoyExcludeReasonSumAggregateInputObjectSchema } from './objects/DictMissRoyExcludeReasonSumAggregateInput.schema';

export const dictMissRoyExcludeReasonGroupBySchema: z.ZodType<Prisma.dictMissRoyExcludeReasonGroupByArgs> = z.object({ where: dictMissRoyExcludeReasonWhereInputObjectSchema.optional(), orderBy: z.union([dictMissRoyExcludeReasonOrderByWithAggregationInputObjectSchema, dictMissRoyExcludeReasonOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictMissRoyExcludeReasonScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictMissRoyExcludeReasonScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictMissRoyExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictMissRoyExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictMissRoyExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictMissRoyExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictMissRoyExcludeReasonSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictMissRoyExcludeReasonGroupByArgs>;

export const dictMissRoyExcludeReasonGroupByZodSchema = z.object({ where: dictMissRoyExcludeReasonWhereInputObjectSchema.optional(), orderBy: z.union([dictMissRoyExcludeReasonOrderByWithAggregationInputObjectSchema, dictMissRoyExcludeReasonOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictMissRoyExcludeReasonScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictMissRoyExcludeReasonScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictMissRoyExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictMissRoyExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictMissRoyExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictMissRoyExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictMissRoyExcludeReasonSumAggregateInputObjectSchema.optional() }).strict();