import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblRoyRatesWhereInputObjectSchema as tblRoyRatesWhereInputObjectSchema } from './objects/tblRoyRatesWhereInput.schema';
import { tblRoyRatesOrderByWithAggregationInputObjectSchema as tblRoyRatesOrderByWithAggregationInputObjectSchema } from './objects/tblRoyRatesOrderByWithAggregationInput.schema';
import { tblRoyRatesScalarWhereWithAggregatesInputObjectSchema as tblRoyRatesScalarWhereWithAggregatesInputObjectSchema } from './objects/tblRoyRatesScalarWhereWithAggregatesInput.schema';
import { TblRoyRatesScalarFieldEnumSchema } from './enums/TblRoyRatesScalarFieldEnum.schema';
import { TblRoyRatesCountAggregateInputObjectSchema as TblRoyRatesCountAggregateInputObjectSchema } from './objects/TblRoyRatesCountAggregateInput.schema';
import { TblRoyRatesMinAggregateInputObjectSchema as TblRoyRatesMinAggregateInputObjectSchema } from './objects/TblRoyRatesMinAggregateInput.schema';
import { TblRoyRatesMaxAggregateInputObjectSchema as TblRoyRatesMaxAggregateInputObjectSchema } from './objects/TblRoyRatesMaxAggregateInput.schema';
import { TblRoyRatesAvgAggregateInputObjectSchema as TblRoyRatesAvgAggregateInputObjectSchema } from './objects/TblRoyRatesAvgAggregateInput.schema';
import { TblRoyRatesSumAggregateInputObjectSchema as TblRoyRatesSumAggregateInputObjectSchema } from './objects/TblRoyRatesSumAggregateInput.schema';

export const tblRoyRatesGroupBySchema: z.ZodType<Prisma.tblRoyRatesGroupByArgs> = z.object({ where: tblRoyRatesWhereInputObjectSchema.optional(), orderBy: z.union([tblRoyRatesOrderByWithAggregationInputObjectSchema, tblRoyRatesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblRoyRatesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblRoyRatesScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblRoyRatesCountAggregateInputObjectSchema ]).optional(), _min: TblRoyRatesMinAggregateInputObjectSchema.optional(), _max: TblRoyRatesMaxAggregateInputObjectSchema.optional(), _avg: TblRoyRatesAvgAggregateInputObjectSchema.optional(), _sum: TblRoyRatesSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblRoyRatesGroupByArgs>;

export const tblRoyRatesGroupByZodSchema = z.object({ where: tblRoyRatesWhereInputObjectSchema.optional(), orderBy: z.union([tblRoyRatesOrderByWithAggregationInputObjectSchema, tblRoyRatesOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblRoyRatesScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblRoyRatesScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblRoyRatesCountAggregateInputObjectSchema ]).optional(), _min: TblRoyRatesMinAggregateInputObjectSchema.optional(), _max: TblRoyRatesMaxAggregateInputObjectSchema.optional(), _avg: TblRoyRatesAvgAggregateInputObjectSchema.optional(), _sum: TblRoyRatesSumAggregateInputObjectSchema.optional() }).strict();