import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictCountries_oldWhereInputObjectSchema as dictCountries_oldWhereInputObjectSchema } from './objects/dictCountries_oldWhereInput.schema';
import { dictCountries_oldOrderByWithAggregationInputObjectSchema as dictCountries_oldOrderByWithAggregationInputObjectSchema } from './objects/dictCountries_oldOrderByWithAggregationInput.schema';
import { dictCountries_oldScalarWhereWithAggregatesInputObjectSchema as dictCountries_oldScalarWhereWithAggregatesInputObjectSchema } from './objects/dictCountries_oldScalarWhereWithAggregatesInput.schema';
import { DictCountriesOldScalarFieldEnumSchema } from './enums/DictCountriesOldScalarFieldEnum.schema';
import { DictCountries_oldCountAggregateInputObjectSchema as DictCountries_oldCountAggregateInputObjectSchema } from './objects/DictCountries_oldCountAggregateInput.schema';
import { DictCountries_oldMinAggregateInputObjectSchema as DictCountries_oldMinAggregateInputObjectSchema } from './objects/DictCountries_oldMinAggregateInput.schema';
import { DictCountries_oldMaxAggregateInputObjectSchema as DictCountries_oldMaxAggregateInputObjectSchema } from './objects/DictCountries_oldMaxAggregateInput.schema';
import { DictCountries_oldAvgAggregateInputObjectSchema as DictCountries_oldAvgAggregateInputObjectSchema } from './objects/DictCountries_oldAvgAggregateInput.schema';
import { DictCountries_oldSumAggregateInputObjectSchema as DictCountries_oldSumAggregateInputObjectSchema } from './objects/DictCountries_oldSumAggregateInput.schema';

export const dictCountries_oldGroupBySchema: z.ZodType<Prisma.dictCountries_oldGroupByArgs> = z.object({ where: dictCountries_oldWhereInputObjectSchema.optional(), orderBy: z.union([dictCountries_oldOrderByWithAggregationInputObjectSchema, dictCountries_oldOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictCountries_oldScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictCountriesOldScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictCountries_oldCountAggregateInputObjectSchema ]).optional(), _min: DictCountries_oldMinAggregateInputObjectSchema.optional(), _max: DictCountries_oldMaxAggregateInputObjectSchema.optional(), _avg: DictCountries_oldAvgAggregateInputObjectSchema.optional(), _sum: DictCountries_oldSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictCountries_oldGroupByArgs>;

export const dictCountries_oldGroupByZodSchema = z.object({ where: dictCountries_oldWhereInputObjectSchema.optional(), orderBy: z.union([dictCountries_oldOrderByWithAggregationInputObjectSchema, dictCountries_oldOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictCountries_oldScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictCountriesOldScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictCountries_oldCountAggregateInputObjectSchema ]).optional(), _min: DictCountries_oldMinAggregateInputObjectSchema.optional(), _max: DictCountries_oldMaxAggregateInputObjectSchema.optional(), _avg: DictCountries_oldAvgAggregateInputObjectSchema.optional(), _sum: DictCountries_oldSumAggregateInputObjectSchema.optional() }).strict();