import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { SubmissionEventWhereInputObjectSchema as SubmissionEventWhereInputObjectSchema } from './objects/SubmissionEventWhereInput.schema';
import { SubmissionEventOrderByWithAggregationInputObjectSchema as SubmissionEventOrderByWithAggregationInputObjectSchema } from './objects/SubmissionEventOrderByWithAggregationInput.schema';
import { SubmissionEventScalarWhereWithAggregatesInputObjectSchema as SubmissionEventScalarWhereWithAggregatesInputObjectSchema } from './objects/SubmissionEventScalarWhereWithAggregatesInput.schema';
import { SubmissionEventScalarFieldEnumSchema } from './enums/SubmissionEventScalarFieldEnum.schema';
import { SubmissionEventCountAggregateInputObjectSchema as SubmissionEventCountAggregateInputObjectSchema } from './objects/SubmissionEventCountAggregateInput.schema';
import { SubmissionEventMinAggregateInputObjectSchema as SubmissionEventMinAggregateInputObjectSchema } from './objects/SubmissionEventMinAggregateInput.schema';
import { SubmissionEventMaxAggregateInputObjectSchema as SubmissionEventMaxAggregateInputObjectSchema } from './objects/SubmissionEventMaxAggregateInput.schema';
import { SubmissionEventAvgAggregateInputObjectSchema as SubmissionEventAvgAggregateInputObjectSchema } from './objects/SubmissionEventAvgAggregateInput.schema';
import { SubmissionEventSumAggregateInputObjectSchema as SubmissionEventSumAggregateInputObjectSchema } from './objects/SubmissionEventSumAggregateInput.schema';

export const SubmissionEventGroupBySchema: z.ZodType<Prisma.SubmissionEventGroupByArgs> = z.object({ where: SubmissionEventWhereInputObjectSchema.optional(), orderBy: z.union([SubmissionEventOrderByWithAggregationInputObjectSchema, SubmissionEventOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SubmissionEventScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SubmissionEventScalarFieldEnumSchema), _count: z.union([ z.literal(true), SubmissionEventCountAggregateInputObjectSchema ]).optional(), _min: SubmissionEventMinAggregateInputObjectSchema.optional(), _max: SubmissionEventMaxAggregateInputObjectSchema.optional(), _avg: SubmissionEventAvgAggregateInputObjectSchema.optional(), _sum: SubmissionEventSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SubmissionEventGroupByArgs>;

export const SubmissionEventGroupByZodSchema = z.object({ where: SubmissionEventWhereInputObjectSchema.optional(), orderBy: z.union([SubmissionEventOrderByWithAggregationInputObjectSchema, SubmissionEventOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SubmissionEventScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SubmissionEventScalarFieldEnumSchema), _count: z.union([ z.literal(true), SubmissionEventCountAggregateInputObjectSchema ]).optional(), _min: SubmissionEventMinAggregateInputObjectSchema.optional(), _max: SubmissionEventMaxAggregateInputObjectSchema.optional(), _avg: SubmissionEventAvgAggregateInputObjectSchema.optional(), _sum: SubmissionEventSumAggregateInputObjectSchema.optional() }).strict();