import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblPersonContractTypeWhereInputObjectSchema as tblPersonContractTypeWhereInputObjectSchema } from './objects/tblPersonContractTypeWhereInput.schema';
import { tblPersonContractTypeOrderByWithAggregationInputObjectSchema as tblPersonContractTypeOrderByWithAggregationInputObjectSchema } from './objects/tblPersonContractTypeOrderByWithAggregationInput.schema';
import { tblPersonContractTypeScalarWhereWithAggregatesInputObjectSchema as tblPersonContractTypeScalarWhereWithAggregatesInputObjectSchema } from './objects/tblPersonContractTypeScalarWhereWithAggregatesInput.schema';
import { TblPersonContractTypeScalarFieldEnumSchema } from './enums/TblPersonContractTypeScalarFieldEnum.schema';
import { TblPersonContractTypeCountAggregateInputObjectSchema as TblPersonContractTypeCountAggregateInputObjectSchema } from './objects/TblPersonContractTypeCountAggregateInput.schema';
import { TblPersonContractTypeMinAggregateInputObjectSchema as TblPersonContractTypeMinAggregateInputObjectSchema } from './objects/TblPersonContractTypeMinAggregateInput.schema';
import { TblPersonContractTypeMaxAggregateInputObjectSchema as TblPersonContractTypeMaxAggregateInputObjectSchema } from './objects/TblPersonContractTypeMaxAggregateInput.schema';
import { TblPersonContractTypeAvgAggregateInputObjectSchema as TblPersonContractTypeAvgAggregateInputObjectSchema } from './objects/TblPersonContractTypeAvgAggregateInput.schema';
import { TblPersonContractTypeSumAggregateInputObjectSchema as TblPersonContractTypeSumAggregateInputObjectSchema } from './objects/TblPersonContractTypeSumAggregateInput.schema';

export const tblPersonContractTypeGroupBySchema: z.ZodType<Prisma.tblPersonContractTypeGroupByArgs> = z.object({ where: tblPersonContractTypeWhereInputObjectSchema.optional(), orderBy: z.union([tblPersonContractTypeOrderByWithAggregationInputObjectSchema, tblPersonContractTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblPersonContractTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblPersonContractTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblPersonContractTypeCountAggregateInputObjectSchema ]).optional(), _min: TblPersonContractTypeMinAggregateInputObjectSchema.optional(), _max: TblPersonContractTypeMaxAggregateInputObjectSchema.optional(), _avg: TblPersonContractTypeAvgAggregateInputObjectSchema.optional(), _sum: TblPersonContractTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblPersonContractTypeGroupByArgs>;

export const tblPersonContractTypeGroupByZodSchema = z.object({ where: tblPersonContractTypeWhereInputObjectSchema.optional(), orderBy: z.union([tblPersonContractTypeOrderByWithAggregationInputObjectSchema, tblPersonContractTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblPersonContractTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblPersonContractTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblPersonContractTypeCountAggregateInputObjectSchema ]).optional(), _min: TblPersonContractTypeMinAggregateInputObjectSchema.optional(), _max: TblPersonContractTypeMaxAggregateInputObjectSchema.optional(), _avg: TblPersonContractTypeAvgAggregateInputObjectSchema.optional(), _sum: TblPersonContractTypeSumAggregateInputObjectSchema.optional() }).strict();