import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblMailingListsWhereInputObjectSchema as tblMailingListsWhereInputObjectSchema } from './objects/tblMailingListsWhereInput.schema';
import { tblMailingListsOrderByWithAggregationInputObjectSchema as tblMailingListsOrderByWithAggregationInputObjectSchema } from './objects/tblMailingListsOrderByWithAggregationInput.schema';
import { tblMailingListsScalarWhereWithAggregatesInputObjectSchema as tblMailingListsScalarWhereWithAggregatesInputObjectSchema } from './objects/tblMailingListsScalarWhereWithAggregatesInput.schema';
import { TblMailingListsScalarFieldEnumSchema } from './enums/TblMailingListsScalarFieldEnum.schema';
import { TblMailingListsCountAggregateInputObjectSchema as TblMailingListsCountAggregateInputObjectSchema } from './objects/TblMailingListsCountAggregateInput.schema';
import { TblMailingListsMinAggregateInputObjectSchema as TblMailingListsMinAggregateInputObjectSchema } from './objects/TblMailingListsMinAggregateInput.schema';
import { TblMailingListsMaxAggregateInputObjectSchema as TblMailingListsMaxAggregateInputObjectSchema } from './objects/TblMailingListsMaxAggregateInput.schema';
import { TblMailingListsAvgAggregateInputObjectSchema as TblMailingListsAvgAggregateInputObjectSchema } from './objects/TblMailingListsAvgAggregateInput.schema';
import { TblMailingListsSumAggregateInputObjectSchema as TblMailingListsSumAggregateInputObjectSchema } from './objects/TblMailingListsSumAggregateInput.schema';

export const tblMailingListsGroupBySchema: z.ZodType<Prisma.tblMailingListsGroupByArgs> = z.object({ where: tblMailingListsWhereInputObjectSchema.optional(), orderBy: z.union([tblMailingListsOrderByWithAggregationInputObjectSchema, tblMailingListsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblMailingListsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblMailingListsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblMailingListsCountAggregateInputObjectSchema ]).optional(), _min: TblMailingListsMinAggregateInputObjectSchema.optional(), _max: TblMailingListsMaxAggregateInputObjectSchema.optional(), _avg: TblMailingListsAvgAggregateInputObjectSchema.optional(), _sum: TblMailingListsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblMailingListsGroupByArgs>;

export const tblMailingListsGroupByZodSchema = z.object({ where: tblMailingListsWhereInputObjectSchema.optional(), orderBy: z.union([tblMailingListsOrderByWithAggregationInputObjectSchema, tblMailingListsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblMailingListsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblMailingListsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblMailingListsCountAggregateInputObjectSchema ]).optional(), _min: TblMailingListsMinAggregateInputObjectSchema.optional(), _max: TblMailingListsMaxAggregateInputObjectSchema.optional(), _avg: TblMailingListsAvgAggregateInputObjectSchema.optional(), _sum: TblMailingListsSumAggregateInputObjectSchema.optional() }).strict();