import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblInvoiceDetailsWhereInputObjectSchema as tblInvoiceDetailsWhereInputObjectSchema } from './objects/tblInvoiceDetailsWhereInput.schema';
import { tblInvoiceDetailsOrderByWithAggregationInputObjectSchema as tblInvoiceDetailsOrderByWithAggregationInputObjectSchema } from './objects/tblInvoiceDetailsOrderByWithAggregationInput.schema';
import { tblInvoiceDetailsScalarWhereWithAggregatesInputObjectSchema as tblInvoiceDetailsScalarWhereWithAggregatesInputObjectSchema } from './objects/tblInvoiceDetailsScalarWhereWithAggregatesInput.schema';
import { TblInvoiceDetailsScalarFieldEnumSchema } from './enums/TblInvoiceDetailsScalarFieldEnum.schema';
import { TblInvoiceDetailsCountAggregateInputObjectSchema as TblInvoiceDetailsCountAggregateInputObjectSchema } from './objects/TblInvoiceDetailsCountAggregateInput.schema';
import { TblInvoiceDetailsMinAggregateInputObjectSchema as TblInvoiceDetailsMinAggregateInputObjectSchema } from './objects/TblInvoiceDetailsMinAggregateInput.schema';
import { TblInvoiceDetailsMaxAggregateInputObjectSchema as TblInvoiceDetailsMaxAggregateInputObjectSchema } from './objects/TblInvoiceDetailsMaxAggregateInput.schema';
import { TblInvoiceDetailsAvgAggregateInputObjectSchema as TblInvoiceDetailsAvgAggregateInputObjectSchema } from './objects/TblInvoiceDetailsAvgAggregateInput.schema';
import { TblInvoiceDetailsSumAggregateInputObjectSchema as TblInvoiceDetailsSumAggregateInputObjectSchema } from './objects/TblInvoiceDetailsSumAggregateInput.schema';

export const tblInvoiceDetailsGroupBySchema: z.ZodType<Prisma.tblInvoiceDetailsGroupByArgs> = z.object({ where: tblInvoiceDetailsWhereInputObjectSchema.optional(), orderBy: z.union([tblInvoiceDetailsOrderByWithAggregationInputObjectSchema, tblInvoiceDetailsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblInvoiceDetailsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblInvoiceDetailsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblInvoiceDetailsCountAggregateInputObjectSchema ]).optional(), _min: TblInvoiceDetailsMinAggregateInputObjectSchema.optional(), _max: TblInvoiceDetailsMaxAggregateInputObjectSchema.optional(), _avg: TblInvoiceDetailsAvgAggregateInputObjectSchema.optional(), _sum: TblInvoiceDetailsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblInvoiceDetailsGroupByArgs>;

export const tblInvoiceDetailsGroupByZodSchema = z.object({ where: tblInvoiceDetailsWhereInputObjectSchema.optional(), orderBy: z.union([tblInvoiceDetailsOrderByWithAggregationInputObjectSchema, tblInvoiceDetailsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblInvoiceDetailsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblInvoiceDetailsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblInvoiceDetailsCountAggregateInputObjectSchema ]).optional(), _min: TblInvoiceDetailsMinAggregateInputObjectSchema.optional(), _max: TblInvoiceDetailsMaxAggregateInputObjectSchema.optional(), _avg: TblInvoiceDetailsAvgAggregateInputObjectSchema.optional(), _sum: TblInvoiceDetailsSumAggregateInputObjectSchema.optional() }).strict();