import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictAdvWithoutInvExcludeReasonWhereInputObjectSchema as dictAdvWithoutInvExcludeReasonWhereInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonWhereInput.schema';
import { dictAdvWithoutInvExcludeReasonOrderByWithAggregationInputObjectSchema as dictAdvWithoutInvExcludeReasonOrderByWithAggregationInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonOrderByWithAggregationInput.schema';
import { dictAdvWithoutInvExcludeReasonScalarWhereWithAggregatesInputObjectSchema as dictAdvWithoutInvExcludeReasonScalarWhereWithAggregatesInputObjectSchema } from './objects/dictAdvWithoutInvExcludeReasonScalarWhereWithAggregatesInput.schema';
import { DictAdvWithoutInvExcludeReasonScalarFieldEnumSchema } from './enums/DictAdvWithoutInvExcludeReasonScalarFieldEnum.schema';
import { DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonCountAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonMinAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonMaxAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonAvgAggregateInput.schema';
import { DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema as DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema } from './objects/DictAdvWithoutInvExcludeReasonSumAggregateInput.schema';

export const dictAdvWithoutInvExcludeReasonGroupBySchema: z.ZodType<Prisma.dictAdvWithoutInvExcludeReasonGroupByArgs> = z.object({ where: dictAdvWithoutInvExcludeReasonWhereInputObjectSchema.optional(), orderBy: z.union([dictAdvWithoutInvExcludeReasonOrderByWithAggregationInputObjectSchema, dictAdvWithoutInvExcludeReasonOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictAdvWithoutInvExcludeReasonScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictAdvWithoutInvExcludeReasonScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictAdvWithoutInvExcludeReasonGroupByArgs>;

export const dictAdvWithoutInvExcludeReasonGroupByZodSchema = z.object({ where: dictAdvWithoutInvExcludeReasonWhereInputObjectSchema.optional(), orderBy: z.union([dictAdvWithoutInvExcludeReasonOrderByWithAggregationInputObjectSchema, dictAdvWithoutInvExcludeReasonOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictAdvWithoutInvExcludeReasonScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictAdvWithoutInvExcludeReasonScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictAdvWithoutInvExcludeReasonCountAggregateInputObjectSchema ]).optional(), _min: DictAdvWithoutInvExcludeReasonMinAggregateInputObjectSchema.optional(), _max: DictAdvWithoutInvExcludeReasonMaxAggregateInputObjectSchema.optional(), _avg: DictAdvWithoutInvExcludeReasonAvgAggregateInputObjectSchema.optional(), _sum: DictAdvWithoutInvExcludeReasonSumAggregateInputObjectSchema.optional() }).strict();