import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictSubmSentTypeWhereInputObjectSchema as dictSubmSentTypeWhereInputObjectSchema } from './objects/dictSubmSentTypeWhereInput.schema';
import { dictSubmSentTypeOrderByWithAggregationInputObjectSchema as dictSubmSentTypeOrderByWithAggregationInputObjectSchema } from './objects/dictSubmSentTypeOrderByWithAggregationInput.schema';
import { dictSubmSentTypeScalarWhereWithAggregatesInputObjectSchema as dictSubmSentTypeScalarWhereWithAggregatesInputObjectSchema } from './objects/dictSubmSentTypeScalarWhereWithAggregatesInput.schema';
import { DictSubmSentTypeScalarFieldEnumSchema } from './enums/DictSubmSentTypeScalarFieldEnum.schema';
import { DictSubmSentTypeCountAggregateInputObjectSchema as DictSubmSentTypeCountAggregateInputObjectSchema } from './objects/DictSubmSentTypeCountAggregateInput.schema';
import { DictSubmSentTypeMinAggregateInputObjectSchema as DictSubmSentTypeMinAggregateInputObjectSchema } from './objects/DictSubmSentTypeMinAggregateInput.schema';
import { DictSubmSentTypeMaxAggregateInputObjectSchema as DictSubmSentTypeMaxAggregateInputObjectSchema } from './objects/DictSubmSentTypeMaxAggregateInput.schema';
import { DictSubmSentTypeAvgAggregateInputObjectSchema as DictSubmSentTypeAvgAggregateInputObjectSchema } from './objects/DictSubmSentTypeAvgAggregateInput.schema';
import { DictSubmSentTypeSumAggregateInputObjectSchema as DictSubmSentTypeSumAggregateInputObjectSchema } from './objects/DictSubmSentTypeSumAggregateInput.schema';

export const dictSubmSentTypeGroupBySchema: z.ZodType<Prisma.dictSubmSentTypeGroupByArgs> = z.object({ where: dictSubmSentTypeWhereInputObjectSchema.optional(), orderBy: z.union([dictSubmSentTypeOrderByWithAggregationInputObjectSchema, dictSubmSentTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictSubmSentTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictSubmSentTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictSubmSentTypeCountAggregateInputObjectSchema ]).optional(), _min: DictSubmSentTypeMinAggregateInputObjectSchema.optional(), _max: DictSubmSentTypeMaxAggregateInputObjectSchema.optional(), _avg: DictSubmSentTypeAvgAggregateInputObjectSchema.optional(), _sum: DictSubmSentTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictSubmSentTypeGroupByArgs>;

export const dictSubmSentTypeGroupByZodSchema = z.object({ where: dictSubmSentTypeWhereInputObjectSchema.optional(), orderBy: z.union([dictSubmSentTypeOrderByWithAggregationInputObjectSchema, dictSubmSentTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictSubmSentTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictSubmSentTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictSubmSentTypeCountAggregateInputObjectSchema ]).optional(), _min: DictSubmSentTypeMinAggregateInputObjectSchema.optional(), _max: DictSubmSentTypeMaxAggregateInputObjectSchema.optional(), _avg: DictSubmSentTypeAvgAggregateInputObjectSchema.optional(), _sum: DictSubmSentTypeSumAggregateInputObjectSchema.optional() }).strict();