import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictTargetGroupsWhereInputObjectSchema as dictTargetGroupsWhereInputObjectSchema } from './objects/dictTargetGroupsWhereInput.schema';
import { dictTargetGroupsOrderByWithAggregationInputObjectSchema as dictTargetGroupsOrderByWithAggregationInputObjectSchema } from './objects/dictTargetGroupsOrderByWithAggregationInput.schema';
import { dictTargetGroupsScalarWhereWithAggregatesInputObjectSchema as dictTargetGroupsScalarWhereWithAggregatesInputObjectSchema } from './objects/dictTargetGroupsScalarWhereWithAggregatesInput.schema';
import { DictTargetGroupsScalarFieldEnumSchema } from './enums/DictTargetGroupsScalarFieldEnum.schema';
import { DictTargetGroupsCountAggregateInputObjectSchema as DictTargetGroupsCountAggregateInputObjectSchema } from './objects/DictTargetGroupsCountAggregateInput.schema';
import { DictTargetGroupsMinAggregateInputObjectSchema as DictTargetGroupsMinAggregateInputObjectSchema } from './objects/DictTargetGroupsMinAggregateInput.schema';
import { DictTargetGroupsMaxAggregateInputObjectSchema as DictTargetGroupsMaxAggregateInputObjectSchema } from './objects/DictTargetGroupsMaxAggregateInput.schema';
import { DictTargetGroupsAvgAggregateInputObjectSchema as DictTargetGroupsAvgAggregateInputObjectSchema } from './objects/DictTargetGroupsAvgAggregateInput.schema';
import { DictTargetGroupsSumAggregateInputObjectSchema as DictTargetGroupsSumAggregateInputObjectSchema } from './objects/DictTargetGroupsSumAggregateInput.schema';

export const dictTargetGroupsGroupBySchema: z.ZodType<Prisma.dictTargetGroupsGroupByArgs> = z.object({ where: dictTargetGroupsWhereInputObjectSchema.optional(), orderBy: z.union([dictTargetGroupsOrderByWithAggregationInputObjectSchema, dictTargetGroupsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictTargetGroupsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictTargetGroupsScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictTargetGroupsCountAggregateInputObjectSchema ]).optional(), _min: DictTargetGroupsMinAggregateInputObjectSchema.optional(), _max: DictTargetGroupsMaxAggregateInputObjectSchema.optional(), _avg: DictTargetGroupsAvgAggregateInputObjectSchema.optional(), _sum: DictTargetGroupsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictTargetGroupsGroupByArgs>;

export const dictTargetGroupsGroupByZodSchema = z.object({ where: dictTargetGroupsWhereInputObjectSchema.optional(), orderBy: z.union([dictTargetGroupsOrderByWithAggregationInputObjectSchema, dictTargetGroupsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictTargetGroupsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictTargetGroupsScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictTargetGroupsCountAggregateInputObjectSchema ]).optional(), _min: DictTargetGroupsMinAggregateInputObjectSchema.optional(), _max: DictTargetGroupsMaxAggregateInputObjectSchema.optional(), _avg: DictTargetGroupsAvgAggregateInputObjectSchema.optional(), _sum: DictTargetGroupsSumAggregateInputObjectSchema.optional() }).strict();