import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PearsonAdvAndRoyWhereInputObjectSchema as PearsonAdvAndRoyWhereInputObjectSchema } from './objects/PearsonAdvAndRoyWhereInput.schema';
import { PearsonAdvAndRoyOrderByWithAggregationInputObjectSchema as PearsonAdvAndRoyOrderByWithAggregationInputObjectSchema } from './objects/PearsonAdvAndRoyOrderByWithAggregationInput.schema';
import { PearsonAdvAndRoyScalarWhereWithAggregatesInputObjectSchema as PearsonAdvAndRoyScalarWhereWithAggregatesInputObjectSchema } from './objects/PearsonAdvAndRoyScalarWhereWithAggregatesInput.schema';
import { PearsonAdvAndRoyScalarFieldEnumSchema } from './enums/PearsonAdvAndRoyScalarFieldEnum.schema';
import { PearsonAdvAndRoyCountAggregateInputObjectSchema as PearsonAdvAndRoyCountAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyCountAggregateInput.schema';
import { PearsonAdvAndRoyMinAggregateInputObjectSchema as PearsonAdvAndRoyMinAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyMinAggregateInput.schema';
import { PearsonAdvAndRoyMaxAggregateInputObjectSchema as PearsonAdvAndRoyMaxAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyMaxAggregateInput.schema';
import { PearsonAdvAndRoyAvgAggregateInputObjectSchema as PearsonAdvAndRoyAvgAggregateInputObjectSchema } from './objects/PearsonAdvAndRoyAvgAggregateInput.schema';
import { PearsonAdvAndRoySumAggregateInputObjectSchema as PearsonAdvAndRoySumAggregateInputObjectSchema } from './objects/PearsonAdvAndRoySumAggregateInput.schema';

export const PearsonAdvAndRoyGroupBySchema: z.ZodType<Prisma.PearsonAdvAndRoyGroupByArgs> = z.object({ where: PearsonAdvAndRoyWhereInputObjectSchema.optional(), orderBy: z.union([PearsonAdvAndRoyOrderByWithAggregationInputObjectSchema, PearsonAdvAndRoyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PearsonAdvAndRoyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PearsonAdvAndRoyScalarFieldEnumSchema), _count: z.union([ z.literal(true), PearsonAdvAndRoyCountAggregateInputObjectSchema ]).optional(), _min: PearsonAdvAndRoyMinAggregateInputObjectSchema.optional(), _max: PearsonAdvAndRoyMaxAggregateInputObjectSchema.optional(), _avg: PearsonAdvAndRoyAvgAggregateInputObjectSchema.optional(), _sum: PearsonAdvAndRoySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PearsonAdvAndRoyGroupByArgs>;

export const PearsonAdvAndRoyGroupByZodSchema = z.object({ where: PearsonAdvAndRoyWhereInputObjectSchema.optional(), orderBy: z.union([PearsonAdvAndRoyOrderByWithAggregationInputObjectSchema, PearsonAdvAndRoyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PearsonAdvAndRoyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PearsonAdvAndRoyScalarFieldEnumSchema), _count: z.union([ z.literal(true), PearsonAdvAndRoyCountAggregateInputObjectSchema ]).optional(), _min: PearsonAdvAndRoyMinAggregateInputObjectSchema.optional(), _max: PearsonAdvAndRoyMaxAggregateInputObjectSchema.optional(), _avg: PearsonAdvAndRoyAvgAggregateInputObjectSchema.optional(), _sum: PearsonAdvAndRoySumAggregateInputObjectSchema.optional() }).strict();