import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblClients_obsoleteWhereInputObjectSchema as tblClients_obsoleteWhereInputObjectSchema } from './objects/tblClients_obsoleteWhereInput.schema';
import { tblClients_obsoleteOrderByWithAggregationInputObjectSchema as tblClients_obsoleteOrderByWithAggregationInputObjectSchema } from './objects/tblClients_obsoleteOrderByWithAggregationInput.schema';
import { tblClients_obsoleteScalarWhereWithAggregatesInputObjectSchema as tblClients_obsoleteScalarWhereWithAggregatesInputObjectSchema } from './objects/tblClients_obsoleteScalarWhereWithAggregatesInput.schema';
import { TblClientsObsoleteScalarFieldEnumSchema } from './enums/TblClientsObsoleteScalarFieldEnum.schema';
import { TblClients_obsoleteCountAggregateInputObjectSchema as TblClients_obsoleteCountAggregateInputObjectSchema } from './objects/TblClients_obsoleteCountAggregateInput.schema';
import { TblClients_obsoleteMinAggregateInputObjectSchema as TblClients_obsoleteMinAggregateInputObjectSchema } from './objects/TblClients_obsoleteMinAggregateInput.schema';
import { TblClients_obsoleteMaxAggregateInputObjectSchema as TblClients_obsoleteMaxAggregateInputObjectSchema } from './objects/TblClients_obsoleteMaxAggregateInput.schema';
import { TblClients_obsoleteAvgAggregateInputObjectSchema as TblClients_obsoleteAvgAggregateInputObjectSchema } from './objects/TblClients_obsoleteAvgAggregateInput.schema';
import { TblClients_obsoleteSumAggregateInputObjectSchema as TblClients_obsoleteSumAggregateInputObjectSchema } from './objects/TblClients_obsoleteSumAggregateInput.schema';

export const tblClients_obsoleteGroupBySchema: z.ZodType<Prisma.tblClients_obsoleteGroupByArgs> = z.object({ where: tblClients_obsoleteWhereInputObjectSchema.optional(), orderBy: z.union([tblClients_obsoleteOrderByWithAggregationInputObjectSchema, tblClients_obsoleteOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblClients_obsoleteScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblClientsObsoleteScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblClients_obsoleteCountAggregateInputObjectSchema ]).optional(), _min: TblClients_obsoleteMinAggregateInputObjectSchema.optional(), _max: TblClients_obsoleteMaxAggregateInputObjectSchema.optional(), _avg: TblClients_obsoleteAvgAggregateInputObjectSchema.optional(), _sum: TblClients_obsoleteSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblClients_obsoleteGroupByArgs>;

export const tblClients_obsoleteGroupByZodSchema = z.object({ where: tblClients_obsoleteWhereInputObjectSchema.optional(), orderBy: z.union([tblClients_obsoleteOrderByWithAggregationInputObjectSchema, tblClients_obsoleteOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblClients_obsoleteScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblClientsObsoleteScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblClients_obsoleteCountAggregateInputObjectSchema ]).optional(), _min: TblClients_obsoleteMinAggregateInputObjectSchema.optional(), _max: TblClients_obsoleteMaxAggregateInputObjectSchema.optional(), _avg: TblClients_obsoleteAvgAggregateInputObjectSchema.optional(), _sum: TblClients_obsoleteSumAggregateInputObjectSchema.optional() }).strict();