import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CountryDictionaryWhereInputObjectSchema as CountryDictionaryWhereInputObjectSchema } from './objects/CountryDictionaryWhereInput.schema';
import { CountryDictionaryOrderByWithAggregationInputObjectSchema as CountryDictionaryOrderByWithAggregationInputObjectSchema } from './objects/CountryDictionaryOrderByWithAggregationInput.schema';
import { CountryDictionaryScalarWhereWithAggregatesInputObjectSchema as CountryDictionaryScalarWhereWithAggregatesInputObjectSchema } from './objects/CountryDictionaryScalarWhereWithAggregatesInput.schema';
import { CountryDictionaryScalarFieldEnumSchema } from './enums/CountryDictionaryScalarFieldEnum.schema';
import { CountryDictionaryCountAggregateInputObjectSchema as CountryDictionaryCountAggregateInputObjectSchema } from './objects/CountryDictionaryCountAggregateInput.schema';
import { CountryDictionaryMinAggregateInputObjectSchema as CountryDictionaryMinAggregateInputObjectSchema } from './objects/CountryDictionaryMinAggregateInput.schema';
import { CountryDictionaryMaxAggregateInputObjectSchema as CountryDictionaryMaxAggregateInputObjectSchema } from './objects/CountryDictionaryMaxAggregateInput.schema';
import { CountryDictionaryAvgAggregateInputObjectSchema as CountryDictionaryAvgAggregateInputObjectSchema } from './objects/CountryDictionaryAvgAggregateInput.schema';
import { CountryDictionarySumAggregateInputObjectSchema as CountryDictionarySumAggregateInputObjectSchema } from './objects/CountryDictionarySumAggregateInput.schema';

export const CountryDictionaryGroupBySchema: z.ZodType<Prisma.CountryDictionaryGroupByArgs> = z.object({ where: CountryDictionaryWhereInputObjectSchema.optional(), orderBy: z.union([CountryDictionaryOrderByWithAggregationInputObjectSchema, CountryDictionaryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CountryDictionaryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CountryDictionaryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CountryDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CountryDictionaryMinAggregateInputObjectSchema.optional(), _max: CountryDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CountryDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CountryDictionarySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CountryDictionaryGroupByArgs>;

export const CountryDictionaryGroupByZodSchema = z.object({ where: CountryDictionaryWhereInputObjectSchema.optional(), orderBy: z.union([CountryDictionaryOrderByWithAggregationInputObjectSchema, CountryDictionaryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CountryDictionaryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CountryDictionaryScalarFieldEnumSchema), _count: z.union([ z.literal(true), CountryDictionaryCountAggregateInputObjectSchema ]).optional(), _min: CountryDictionaryMinAggregateInputObjectSchema.optional(), _max: CountryDictionaryMaxAggregateInputObjectSchema.optional(), _avg: CountryDictionaryAvgAggregateInputObjectSchema.optional(), _sum: CountryDictionarySumAggregateInputObjectSchema.optional() }).strict();