import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { tblSubmissionsWhereInputObjectSchema as tblSubmissionsWhereInputObjectSchema } from './objects/tblSubmissionsWhereInput.schema';
import { tblSubmissionsOrderByWithAggregationInputObjectSchema as tblSubmissionsOrderByWithAggregationInputObjectSchema } from './objects/tblSubmissionsOrderByWithAggregationInput.schema';
import { tblSubmissionsScalarWhereWithAggregatesInputObjectSchema as tblSubmissionsScalarWhereWithAggregatesInputObjectSchema } from './objects/tblSubmissionsScalarWhereWithAggregatesInput.schema';
import { TblSubmissionsScalarFieldEnumSchema } from './enums/TblSubmissionsScalarFieldEnum.schema';
import { TblSubmissionsCountAggregateInputObjectSchema as TblSubmissionsCountAggregateInputObjectSchema } from './objects/TblSubmissionsCountAggregateInput.schema';
import { TblSubmissionsMinAggregateInputObjectSchema as TblSubmissionsMinAggregateInputObjectSchema } from './objects/TblSubmissionsMinAggregateInput.schema';
import { TblSubmissionsMaxAggregateInputObjectSchema as TblSubmissionsMaxAggregateInputObjectSchema } from './objects/TblSubmissionsMaxAggregateInput.schema';
import { TblSubmissionsAvgAggregateInputObjectSchema as TblSubmissionsAvgAggregateInputObjectSchema } from './objects/TblSubmissionsAvgAggregateInput.schema';
import { TblSubmissionsSumAggregateInputObjectSchema as TblSubmissionsSumAggregateInputObjectSchema } from './objects/TblSubmissionsSumAggregateInput.schema';

export const tblSubmissionsGroupBySchema: z.ZodType<Prisma.tblSubmissionsGroupByArgs> = z.object({ where: tblSubmissionsWhereInputObjectSchema.optional(), orderBy: z.union([tblSubmissionsOrderByWithAggregationInputObjectSchema, tblSubmissionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblSubmissionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblSubmissionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblSubmissionsCountAggregateInputObjectSchema ]).optional(), _min: TblSubmissionsMinAggregateInputObjectSchema.optional(), _max: TblSubmissionsMaxAggregateInputObjectSchema.optional(), _avg: TblSubmissionsAvgAggregateInputObjectSchema.optional(), _sum: TblSubmissionsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.tblSubmissionsGroupByArgs>;

export const tblSubmissionsGroupByZodSchema = z.object({ where: tblSubmissionsWhereInputObjectSchema.optional(), orderBy: z.union([tblSubmissionsOrderByWithAggregationInputObjectSchema, tblSubmissionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: tblSubmissionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TblSubmissionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TblSubmissionsCountAggregateInputObjectSchema ]).optional(), _min: TblSubmissionsMinAggregateInputObjectSchema.optional(), _max: TblSubmissionsMaxAggregateInputObjectSchema.optional(), _avg: TblSubmissionsAvgAggregateInputObjectSchema.optional(), _sum: TblSubmissionsSumAggregateInputObjectSchema.optional() }).strict();