import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictRightsFormWhereInputObjectSchema as dictRightsFormWhereInputObjectSchema } from './objects/dictRightsFormWhereInput.schema';
import { dictRightsFormOrderByWithAggregationInputObjectSchema as dictRightsFormOrderByWithAggregationInputObjectSchema } from './objects/dictRightsFormOrderByWithAggregationInput.schema';
import { dictRightsFormScalarWhereWithAggregatesInputObjectSchema as dictRightsFormScalarWhereWithAggregatesInputObjectSchema } from './objects/dictRightsFormScalarWhereWithAggregatesInput.schema';
import { DictRightsFormScalarFieldEnumSchema } from './enums/DictRightsFormScalarFieldEnum.schema';
import { DictRightsFormCountAggregateInputObjectSchema as DictRightsFormCountAggregateInputObjectSchema } from './objects/DictRightsFormCountAggregateInput.schema';
import { DictRightsFormMinAggregateInputObjectSchema as DictRightsFormMinAggregateInputObjectSchema } from './objects/DictRightsFormMinAggregateInput.schema';
import { DictRightsFormMaxAggregateInputObjectSchema as DictRightsFormMaxAggregateInputObjectSchema } from './objects/DictRightsFormMaxAggregateInput.schema';
import { DictRightsFormAvgAggregateInputObjectSchema as DictRightsFormAvgAggregateInputObjectSchema } from './objects/DictRightsFormAvgAggregateInput.schema';
import { DictRightsFormSumAggregateInputObjectSchema as DictRightsFormSumAggregateInputObjectSchema } from './objects/DictRightsFormSumAggregateInput.schema';

export const dictRightsFormGroupBySchema: z.ZodType<Prisma.dictRightsFormGroupByArgs> = z.object({ where: dictRightsFormWhereInputObjectSchema.optional(), orderBy: z.union([dictRightsFormOrderByWithAggregationInputObjectSchema, dictRightsFormOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictRightsFormScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictRightsFormScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictRightsFormCountAggregateInputObjectSchema ]).optional(), _min: DictRightsFormMinAggregateInputObjectSchema.optional(), _max: DictRightsFormMaxAggregateInputObjectSchema.optional(), _avg: DictRightsFormAvgAggregateInputObjectSchema.optional(), _sum: DictRightsFormSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictRightsFormGroupByArgs>;

export const dictRightsFormGroupByZodSchema = z.object({ where: dictRightsFormWhereInputObjectSchema.optional(), orderBy: z.union([dictRightsFormOrderByWithAggregationInputObjectSchema, dictRightsFormOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictRightsFormScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictRightsFormScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictRightsFormCountAggregateInputObjectSchema ]).optional(), _min: DictRightsFormMinAggregateInputObjectSchema.optional(), _max: DictRightsFormMaxAggregateInputObjectSchema.optional(), _avg: DictRightsFormAvgAggregateInputObjectSchema.optional(), _sum: DictRightsFormSumAggregateInputObjectSchema.optional() }).strict();