import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ArDefaultAccountWhereInputObjectSchema as ArDefaultAccountWhereInputObjectSchema } from './objects/ArDefaultAccountWhereInput.schema';
import { ArDefaultAccountOrderByWithAggregationInputObjectSchema as ArDefaultAccountOrderByWithAggregationInputObjectSchema } from './objects/ArDefaultAccountOrderByWithAggregationInput.schema';
import { ArDefaultAccountScalarWhereWithAggregatesInputObjectSchema as ArDefaultAccountScalarWhereWithAggregatesInputObjectSchema } from './objects/ArDefaultAccountScalarWhereWithAggregatesInput.schema';
import { ArDefaultAccountScalarFieldEnumSchema } from './enums/ArDefaultAccountScalarFieldEnum.schema';
import { ArDefaultAccountCountAggregateInputObjectSchema as ArDefaultAccountCountAggregateInputObjectSchema } from './objects/ArDefaultAccountCountAggregateInput.schema';
import { ArDefaultAccountMinAggregateInputObjectSchema as ArDefaultAccountMinAggregateInputObjectSchema } from './objects/ArDefaultAccountMinAggregateInput.schema';
import { ArDefaultAccountMaxAggregateInputObjectSchema as ArDefaultAccountMaxAggregateInputObjectSchema } from './objects/ArDefaultAccountMaxAggregateInput.schema';
import { ArDefaultAccountAvgAggregateInputObjectSchema as ArDefaultAccountAvgAggregateInputObjectSchema } from './objects/ArDefaultAccountAvgAggregateInput.schema';
import { ArDefaultAccountSumAggregateInputObjectSchema as ArDefaultAccountSumAggregateInputObjectSchema } from './objects/ArDefaultAccountSumAggregateInput.schema';

export const ArDefaultAccountGroupBySchema: z.ZodType<Prisma.ArDefaultAccountGroupByArgs> = z.object({ where: ArDefaultAccountWhereInputObjectSchema.optional(), orderBy: z.union([ArDefaultAccountOrderByWithAggregationInputObjectSchema, ArDefaultAccountOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArDefaultAccountScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArDefaultAccountScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArDefaultAccountCountAggregateInputObjectSchema ]).optional(), _min: ArDefaultAccountMinAggregateInputObjectSchema.optional(), _max: ArDefaultAccountMaxAggregateInputObjectSchema.optional(), _avg: ArDefaultAccountAvgAggregateInputObjectSchema.optional(), _sum: ArDefaultAccountSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ArDefaultAccountGroupByArgs>;

export const ArDefaultAccountGroupByZodSchema = z.object({ where: ArDefaultAccountWhereInputObjectSchema.optional(), orderBy: z.union([ArDefaultAccountOrderByWithAggregationInputObjectSchema, ArDefaultAccountOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ArDefaultAccountScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ArDefaultAccountScalarFieldEnumSchema), _count: z.union([ z.literal(true), ArDefaultAccountCountAggregateInputObjectSchema ]).optional(), _min: ArDefaultAccountMinAggregateInputObjectSchema.optional(), _max: ArDefaultAccountMaxAggregateInputObjectSchema.optional(), _avg: ArDefaultAccountAvgAggregateInputObjectSchema.optional(), _sum: ArDefaultAccountSumAggregateInputObjectSchema.optional() }).strict();