import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { LanguageDictionaryWhereInputObjectSchema as LanguageDictionaryWhereInputObjectSchema } from './objects/LanguageDictionaryWhereInput.schema';
import { LanguageDictionaryOrderByWithAggregationInputObjectSchema as LanguageDictionaryOrderByWithAggregationInputObjectSchema } from './objects/LanguageDictionaryOrderByWithAggregationInput.schema';
import { LanguageDictionaryScalarWhereWithAggregatesInputObjectSchema as LanguageDictionaryScalarWhereWithAggregatesInputObjectSchema } from './objects/LanguageDictionaryScalarWhereWithAggregatesInput.schema';
import { LanguageDictionaryScalarFieldEnumSchema } from './enums/LanguageDictionaryScalarFieldEnum.schema';
import { LanguageDictionaryCountAggregateInputObjectSchema as LanguageDictionaryCountAggregateInputObjectSchema } from './objects/LanguageDictionaryCountAggregateInput.schema';
import { LanguageDictionaryMinAggregateInputObjectSchema as LanguageDictionaryMinAggregateInputObjectSchema } from './objects/LanguageDictionaryMinAggregateInput.schema';
import { LanguageDictionaryMaxAggregateInputObjectSchema as LanguageDictionaryMaxAggregateInputObjectSchema } from './objects/LanguageDictionaryMaxAggregateInput.schema';
import { LanguageDictionaryAvgAggregateInputObjectSchema as LanguageDictionaryAvgAggregateInputObjectSchema } from './objects/LanguageDictionaryAvgAggregateInput.schema';
import { LanguageDictionarySumAggregateInputObjectSchema as LanguageDictionarySumAggregateInputObjectSchema } from './objects/LanguageDictionarySumAggregateInput.schema';

export const LanguageDictionaryGroupBySchema: z.ZodType<Prisma.LanguageDictionaryGroupByArgs> = z.object({ where: LanguageDictionaryWhereInputObjectSchema.optional(), orderBy: z.union([LanguageDictionaryOrderByWithAggregationInputObjectSchema, LanguageDictionaryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: LanguageDictionaryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(LanguageDictionaryScalarFieldEnumSchema), _count: z.union([ z.literal(true), LanguageDictionaryCountAggregateInputObjectSchema ]).optional(), _min: LanguageDictionaryMinAggregateInputObjectSchema.optional(), _max: LanguageDictionaryMaxAggregateInputObjectSchema.optional(), _avg: LanguageDictionaryAvgAggregateInputObjectSchema.optional(), _sum: LanguageDictionarySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.LanguageDictionaryGroupByArgs>;

export const LanguageDictionaryGroupByZodSchema = z.object({ where: LanguageDictionaryWhereInputObjectSchema.optional(), orderBy: z.union([LanguageDictionaryOrderByWithAggregationInputObjectSchema, LanguageDictionaryOrderByWithAggregationInputObjectSchema.array()]).optional(), having: LanguageDictionaryScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(LanguageDictionaryScalarFieldEnumSchema), _count: z.union([ z.literal(true), LanguageDictionaryCountAggregateInputObjectSchema ]).optional(), _min: LanguageDictionaryMinAggregateInputObjectSchema.optional(), _max: LanguageDictionaryMaxAggregateInputObjectSchema.optional(), _avg: LanguageDictionaryAvgAggregateInputObjectSchema.optional(), _sum: LanguageDictionarySumAggregateInputObjectSchema.optional() }).strict();