import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { dictDistributionTypeWhereInputObjectSchema as dictDistributionTypeWhereInputObjectSchema } from './objects/dictDistributionTypeWhereInput.schema';
import { dictDistributionTypeOrderByWithAggregationInputObjectSchema as dictDistributionTypeOrderByWithAggregationInputObjectSchema } from './objects/dictDistributionTypeOrderByWithAggregationInput.schema';
import { dictDistributionTypeScalarWhereWithAggregatesInputObjectSchema as dictDistributionTypeScalarWhereWithAggregatesInputObjectSchema } from './objects/dictDistributionTypeScalarWhereWithAggregatesInput.schema';
import { DictDistributionTypeScalarFieldEnumSchema } from './enums/DictDistributionTypeScalarFieldEnum.schema';
import { DictDistributionTypeCountAggregateInputObjectSchema as DictDistributionTypeCountAggregateInputObjectSchema } from './objects/DictDistributionTypeCountAggregateInput.schema';
import { DictDistributionTypeMinAggregateInputObjectSchema as DictDistributionTypeMinAggregateInputObjectSchema } from './objects/DictDistributionTypeMinAggregateInput.schema';
import { DictDistributionTypeMaxAggregateInputObjectSchema as DictDistributionTypeMaxAggregateInputObjectSchema } from './objects/DictDistributionTypeMaxAggregateInput.schema';
import { DictDistributionTypeAvgAggregateInputObjectSchema as DictDistributionTypeAvgAggregateInputObjectSchema } from './objects/DictDistributionTypeAvgAggregateInput.schema';
import { DictDistributionTypeSumAggregateInputObjectSchema as DictDistributionTypeSumAggregateInputObjectSchema } from './objects/DictDistributionTypeSumAggregateInput.schema';

export const dictDistributionTypeGroupBySchema: z.ZodType<Prisma.dictDistributionTypeGroupByArgs> = z.object({ where: dictDistributionTypeWhereInputObjectSchema.optional(), orderBy: z.union([dictDistributionTypeOrderByWithAggregationInputObjectSchema, dictDistributionTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictDistributionTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictDistributionTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictDistributionTypeCountAggregateInputObjectSchema ]).optional(), _min: DictDistributionTypeMinAggregateInputObjectSchema.optional(), _max: DictDistributionTypeMaxAggregateInputObjectSchema.optional(), _avg: DictDistributionTypeAvgAggregateInputObjectSchema.optional(), _sum: DictDistributionTypeSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.dictDistributionTypeGroupByArgs>;

export const dictDistributionTypeGroupByZodSchema = z.object({ where: dictDistributionTypeWhereInputObjectSchema.optional(), orderBy: z.union([dictDistributionTypeOrderByWithAggregationInputObjectSchema, dictDistributionTypeOrderByWithAggregationInputObjectSchema.array()]).optional(), having: dictDistributionTypeScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(DictDistributionTypeScalarFieldEnumSchema), _count: z.union([ z.literal(true), DictDistributionTypeCountAggregateInputObjectSchema ]).optional(), _min: DictDistributionTypeMinAggregateInputObjectSchema.optional(), _max: DictDistributionTypeMaxAggregateInputObjectSchema.optional(), _avg: DictDistributionTypeAvgAggregateInputObjectSchema.optional(), _sum: DictDistributionTypeSumAggregateInputObjectSchema.optional() }).strict();