ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "sourceId" INTEGER UNIQUE;
ALTER TABLE "Publisher" ADD COLUMN IF NOT EXISTS "sourceId" INTEGER UNIQUE;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "publisherId" INTEGER REFERENCES "Publisher"(id) ON DELETE SET NULL;
