CREATE TABLE "ArAccount" (     "AccountID" INT NOT NULL,     "AccountDescription" VARCHAR(40) NOT NULL);
CREATE TABLE "ArApply" (     "ApplyID" INT NOT NULL,     "DebitID" INT NOT NULL,     "CreditID" INT NOT NULL,     "TaxPerc" NUMERIC(19,4) NULL,     "TaxAmt" NUMERIC(19,4) NULL,     "AmtApplied" NUMERIC(19,4) NULL,     "GraalPerc" NUMERIC(19,4) NULL,     "GraalAmt" NUMERIC(19,4) NULL,     "Notes" TEXT NULL,     "ApplyDate" DATE NULL,     "TaxSet" BOOLEAN NULL);
CREATE TABLE "ArDefaultAccount" (     "TransactionType" SMALLINT NOT NULL,     "DefaultDebitAccount" INT NOT NULL,     "DefaultCreditAccount" INT NOT NULL);
CREATE TABLE "ArTransaction" (     "TransactionID" INT NOT NULL,     "DefaultDocRef" VARCHAR(50) NULL,     "InvNr" INT NULL,     "TransactionDate" TIMESTAMP NULL,     "TransactionType" SMALLINT NULL,     "Currency" CHAR(3) NULL,     "TransactionAmt" NUMERIC(19,4) NULL,     "RCustID" INT NULL,     "PCustID" INT NULL,     "RBalance" NUMERIC(19,4) NULL,     "PBalance" NUMERIC(19,4) NULL,     "IFTBalance" NUMERIC(19,4) NULL,     "GraalBalance" NUMERIC(19,4) NULL,     "ClientReference" VARCHAR(50) NULL,     "OurBankTransRef" VARCHAR(50) NULL,     "NetDate" TIMESTAMP NULL,     "IsChargeInterest" BOOLEAN NULL,     "Notes" TEXT NULL,     "ReversalTransID" INT NULL,     "OriginTransID" INT NULL,     "EntryDate" TIMESTAMP NULL,     "OriginUserID" VARCHAR(50) NULL,     "ErrorID" SMALLINT NULL,     "Status" CHAR(1) NULL,     "CreditID" INT NULL,     "ApplyID" INT NULL,     "TaxCode" CHAR(1) NULL,     "TaxValue" NUMERIC(19,4) NULL);
CREATE TABLE "ArTransactionDetail" (     "ItemID" INT NOT NULL,     "TransactionID" INT NULL,     "AccountID" INT NULL,     "Amount" NUMERIC(19,4) NULL);
CREATE TABLE "ArTransactionType" (     "ArType" SMALLINT NOT NULL,     "ArTypeDescription" VARCHAR(40) NULL,     "ArTypeDescriptionPL" VARCHAR(50) NULL);
CREATE TABLE "ArTransferDetail" (     "TransferID" INT NOT NULL,     "DebitID" INT NOT NULL,     "AmtWired" NUMERIC(19,4) NULL,     "Notes" TEXT NULL);
CREATE TABLE "ArType" (     "ArType" CHAR(3) NOT NULL,     "ArTypeDescription" VARCHAR(40) NULL,     "ArTypeDescriptionPL" VARCHAR(50) NULL);
CREATE TABLE "ArVat" (     "VatCode" VARCHAR(2) NOT NULL,     "Description" VARCHAR(50) NOT NULL,     "VatRate" DOUBLE PRECISION NOT NULL,     "DescriptionPL" VARCHAR(50) NOT NULL);
CREATE TABLE "dictAdvTerm" (     "AdvTermId" SMALLINT NOT NULL,     "AdvTermDesc" VARCHAR(50) NULL,     "AdvTermPL" VARCHAR(50) NULL);
CREATE TABLE "dictAdvType" (     "AdvTypeId" SMALLINT NOT NULL,     "AdvTypeDesc" VARCHAR(50) NULL,     "AdvTypeDescPL" VARCHAR(50) NULL);
CREATE TABLE "dictAdvWithoutInvExcludeReason" (     "ExcludeReasonID" INT NOT NULL,     "ExcludeReasonCode" VARCHAR(3) NULL,     "ExcludeReasonDesc" VARCHAR(50) NULL);
CREATE TABLE "dictAgrEvents" (     "AgrEventCode" INT NOT NULL,     "AgrEventDesc" CHAR(255) NOT NULL,     "Status" CHAR(1) NULL);
CREATE TABLE "dictAgrTemplates" (     "Name" VARCHAR(30) NOT NULL,     "FileName" VARCHAR(255) NOT NULL);
CREATE TABLE "dictArticles" (     "Article" CHAR(10) NOT NULL,     "LangAbb" CHAR(3) NULL);
CREATE TABLE "dictCopyType" (     "CopyTypeID" SMALLINT NOT NULL,     "CopyType" CHAR(30) NULL);
CREATE TABLE "dictCountries" (     "CountryID" INT NOT NULL,     "CountryDesc" TEXT NULL,     "CountryPL" TEXT NULL,     "Tax" NUMERIC(19,4) NULL,     "Code" VARCHAR(255) NULL,     "EU" CHAR(10) NULL);
CREATE TABLE "dictCoverFormat" (     "CoverFormatID" INT NOT NULL,     "CoverFormatDesc" CHAR(30) NOT NULL);
CREATE TABLE "dictCurrencies" (     "CurrID" CHAR(3) NOT NULL,     "CurrDesc" VARCHAR(50) NOT NULL);
CREATE TABLE "dictCustTypes" (     "CustTypeID" INT NOT NULL,     "CustTypeName" VARCHAR(50) NOT NULL,     "CustTypeDesc" VARCHAR(250) NULL);
CREATE TABLE "dictDictionaries" (     "Name" CHAR(30) NULL);
CREATE TABLE "dictDistributionType" (     "DistID" SMALLINT NOT NULL,     "DistDesc" CHAR(30) NOT NULL);
CREATE TABLE "dictEvents" (     "EventCode" INT NOT NULL,     "EventDesc" CHAR(50) NOT NULL);
CREATE TABLE "dictISBN" (     "GRUPA" VARCHAR(255) NULL,     "MIN" VARCHAR(255) NULL,     "MAX" VARCHAR(255) NULL);
CREATE TABLE "dictLanguages" (     "LangAbb" CHAR(3) NOT NULL,     "LangDesc" VARCHAR(30) NOT NULL,     "LangPL" VARCHAR(30) NOT NULL);
CREATE TABLE "dictMatType" (     "MatTypeID" SMALLINT NOT NULL,     "MatTypeDesc" CHAR(50) NOT NULL,     "MatTypeDescPL" CHAR(50) NULL);
CREATE TABLE "dictMissRoyExcludeReason" (     "ExcludeReasonID" INT NOT NULL,     "ExcludeReasonCode" VARCHAR(3) NULL,     "ExcludeReasonDesc" VARCHAR(50) NULL);
CREATE TABLE "dictPriceType" (     "PriceTypeID" SMALLINT NOT NULL,     "PriceTypeDesc" VARCHAR(50) NULL,     "PriceTypePL" VARCHAR(50) NULL);
CREATE TABLE "dictPrintType" (     "PrintType" VARCHAR(1) NULL,     "PrintDesc" VARCHAR(50) NULL);
CREATE TABLE "dictRepModes" (     "RepModeID" SMALLINT NOT NULL,     "RepModeDesc" CHAR(30) NOT NULL);
CREATE TABLE "dictRightsForm" (     "RightFormID" SMALLINT NOT NULL,     "RightFormDesc" VARCHAR(50) NOT NULL,     "RightFormPL" VARCHAR(100) NULL,     "RightFormAbbPL" VARCHAR(10) NULL,     "RightFormAbbEN" VARCHAR(10) NULL);
CREATE TABLE "dictRoyAccountInterval" (     "RoyAccountIntervalID" SMALLINT NOT NULL,     "RoyAccountIntervalDesc" CHAR(50) NOT NULL,     "IntervalAbb" CHAR(8) NULL);
CREATE TABLE "dictRoyPriceType" (     "RoyPriceTypeID" SMALLINT NOT NULL,     "RoyPriceTypeDesc" VARCHAR(50) NOT NULL,     "RoyPriceTypePL" VARCHAR(50) NULL);
CREATE TABLE "dictRoyType" (     "RoyTypeID" NUMERIC(18,0) NOT NULL,     "AgrRightID" INT NULL,     "RoyTypeDesc" CHAR(30) NOT NULL);
CREATE TABLE "dictStates" (     "StateID" SMALLINT NOT NULL,     "CountryID" INT NULL,     "StateAbb" CHAR(2) NOT NULL,     "StateName" VARCHAR(30) NOT NULL);
CREATE TABLE "dictSubmSentType" (     "SubmSentTypeID" SMALLINT NOT NULL,     "SubmSentType" CHAR(30) NOT NULL);
CREATE TABLE "dictTargetGroups" (     "TargetGroupID" NUMERIC(18,0) NOT NULL,     "TargetGroupDesc" CHAR(50) NULL);
CREATE TABLE "dictTitMainClass" (     "ClassCode" VARCHAR(10) NOT NULL,     "ClassDesc" VARCHAR(50) NULL);
CREATE TABLE "dictTitSubClass" (     "SubClassCode" CHAR(5) NOT NULL,     "ClassCode" VARCHAR(10) NULL,     "SubClassDesc" VARCHAR(50) NULL);
CREATE TABLE "dictXRateExcelNames" (     "CurrID" CHAR(3) NOT NULL,     "Name" CHAR(50) NOT NULL);
CREATE TABLE "dictXRates" (     "CurrDate" TIMESTAMP NOT NULL,     "CurrID" CHAR(3) NOT NULL,     "XRate" NUMERIC(19,4) NOT NULL);
CREATE TABLE "dtproperties" (     "id" INT NOT NULL,     "objectid" INT NULL,     "property" VARCHAR(64) NOT NULL,     "value" VARCHAR(255) NULL,     "uvalue" VARCHAR(255) NULL,     "lvalue" BYTEA NULL,     "version" INT NOT NULL);
CREATE TABLE "HelionLocal" (     "ISBNORG" VARCHAR(13) NOT NULL,     "ISBNHELION" VARCHAR(13) NOT NULL,     "TYTULORG" VARCHAR(120) NULL,     "TYTULHELION" VARCHAR(120) NULL);
CREATE TABLE "lkpPayType" (     "PayTypeID" INT NOT NULL,     "Description" CHAR(100) NULL,     "DescriptionPL" CHAR(100) NULL);
CREATE TABLE "Numery" (     "licznik" INT NOT NULL,     "data" TIMESTAMP NOT NULL,     "numer" INT NOT NULL);
CREATE TABLE "PearsonAdvAndRoy" (     "ContractID" DOUBLE PRECISION NOT NULL,     "ISBN" VARCHAR(13) NOT NULL,     "ContractDate" TIMESTAMP NULL,     "PublisherName" VARCHAR(255) NULL,     "TermDate" TIMESTAMP NULL,     "Status" VARCHAR(255) NULL,     "Title" VARCHAR(255) NULL,     "AuthorNames" VARCHAR(255) NULL,     "Edition" DOUBLE PRECISION NULL,     "BBD" TIMESTAMP NULL,     "CopyrightYear" DOUBLE PRECISION NULL,     "SeriesName" VARCHAR(255) NULL,     "FISBN" DOUBLE PRECISION NULL,     "IsPublished" VARCHAR(255) NULL,     "SamplesReceivedDate" TIMESTAMP NULL,     "PubDate" VARCHAR(255) NULL,     "RequiredToPublish" TIMESTAMP NULL,     "IsPaid" VARCHAR(255) NULL,     "TotalAdvances" DOUBLE PRECISION NULL,     "TotalRoyalties" DOUBLE PRECISION NULL,     "Last Royalty Period Reported" VARCHAR(255) NULL,     "Date Royalty Paid" TIMESTAMP NULL);
CREATE TABLE "PearsonMaterial" (     "MyNumber" INT NOT NULL,     "ContractID" INT NOT NULL,     "InvoiceNumber" VARCHAR(255) NULL,     "InvoiceDate" TIMESTAMP NULL,     "Publisher" VARCHAR(255) NULL,     "Title" VARCHAR(255) NULL,     "ISBN" VARCHAR(255) NULL,     "Amount" DOUBLE PRECISION NULL);
CREATE TABLE "tblAdvance" (     "AdvID" INT NOT NULL,     "Inst" SMALLINT NOT NULL,     "AgrID" INT NOT NULL,     "AdvTermId" SMALLINT NULL,     "AdvTypeId" SMALLINT NULL,     "Amount" NUMERIC(19,4) NULL,     "AdvTermDate" TIMESTAMP NULL,     "RoyID" INT NULL);
CREATE TABLE "tblAdvanceBonus" (     "AdvBonusID" INT NOT NULL,     "AgrId" INT NOT NULL,     "Amount" NUMERIC(19,4) NOT NULL,     "Condition" CHAR(1000) NULL,     "DateMod" TIMESTAMP NOT NULL);
CREATE TABLE "tblAdvWithoutInvExcl" (     "AdvID" INT NOT NULL,     "ExcludeReasonID" INT NULL,     "ExcludeReasonCode" VARCHAR(3) NULL,     "ExcludeReasonDesc" VARCHAR(200) NULL,     "EnterDate" DATE NULL);
CREATE TABLE "tblAgreements" (     "AgrID" INT NOT NULL,     "CustID" INT NULL,     "CountryID" INT NULL,     "LangAbbr" CHAR(3) NULL,     "TitleID" INT NULL,     "CurrID" CHAR(3) NULL,     "AgrDate" TIMESTAMP NOT NULL,     "ValidYY" SMALLINT NULL,     "PubTermMM" SMALLINT NULL,     "MaxNoOfCopies" INT NULL,     "MinNoOfCopies" INT NULL,     "Commission" DECIMAL(18,2) NULL,     "ClientReference" VARCHAR(50) NULL,     "DateMod" TIMESTAMP NULL,     "UserMod" CHAR(30) NULL,     "GraalAgentID" INT NULL,     "GraalShare" DECIMAL(5,2) NULL,     "EstimatedCopyPrice" NUMERIC(19,4) NULL,     "GraalRepresent" BOOLEAN NULL,     "Remarks" VARCHAR(1000) NULL,     "AgrDoc" CHAR(250) NULL,     "Status" CHAR(1) NULL,     "CopiesToOwner" SMALLINT NULL,     "CopiesToGraal" SMALLINT NULL,     "LocalTitle" VARCHAR(150) NULL,     "LocalISBN" VARCHAR(16) NULL,     "LocalPubDate" TIMESTAMP NULL,     "ClientID" INT NULL,     "CommissionMaterials" DECIMAL(18,2) NULL,     "AgentID" INT NULL,     "PropID" INT NULL);
CREATE TABLE "tblAgrEvents" (     "AgrEventID" NUMERIC(18,0) NOT NULL,     "AgrID" INT NULL,     "AgrEventCode" INT NULL,     "EventDate" TIMESTAMP NULL,     "NoOfCopies" INT NULL,     "EndDate" TIMESTAMP NULL,     "DateMod" TIMESTAMP NULL,     "UserMod" CHAR(30) NULL);
CREATE TABLE "tblAgrRights" (     "AgrRightID" INT NOT NULL,     "AgrID" INT NULL,     "RightID" SMALLINT NULL,     "PriceTypeID" SMALLINT NULL,     "RoyPriceTypeID" SMALLINT NULL,     "RoyAccountIntervalID" SMALLINT NULL,     "DistID" SMALLINT NULL);
CREATE TABLE "tblAuthors" (     "AuthorID" INT NOT NULL,     "FullName" VARCHAR(150) NULL,     "FirstName" VARCHAR(150) NULL,     "MiddleName" VARCHAR(100) NULL,     "LastName" VARCHAR(150) NULL,     "Suffix" VARCHAR(50) NULL,     "PenName" VARCHAR(150) NULL,     "UserMod" CHAR(30) NOT NULL,     "DateMod" TIMESTAMP NOT NULL,     "Remarks" VARCHAR(1000) NULL);
CREATE TABLE "tblCertPub" (     "ClientID" INT NOT NULL,     "Year" INT NOT NULL,     "PubID" INT NOT NULL,     "DateSent" TIMESTAMP NULL,     "Original" BOOLEAN NULL);
CREATE TABLE "tblClients_obsolete" (     "CustID" INT NOT NULL,     "RepModeID" SMALLINT NULL,     "GraalID" INT NULL,     "Commission" DECIMAL(18,2) NULL,     "DefAgrDoc" VARCHAR(30) NULL,     "Jurisdiction" VARCHAR(200) NULL);
CREATE TABLE "tblContacts" (     "ContactID" INT NOT NULL,     "PhoneNumber" VARCHAR(20) NULL,     "FirstName" VARCHAR(30) NULL,     "MiddleName" VARCHAR(30) NULL,     "LastName" VARCHAR(50) NULL,     "Informal" INT NOT NULL,     "Fax" VARCHAR(20) NULL,     "Email" VARCHAR(50) NULL,     "UserMod" VARCHAR(30) NOT NULL,     "DateMod" TIMESTAMP NOT NULL,     "ContactPosition" VARCHAR(50) NULL,     "Accountant" INT NULL);
CREATE TABLE "tblCustBank" (     "CustID" INT NOT NULL,     "BankName" VARCHAR(150) NOT NULL,     "BankAddress" VARCHAR(150) NULL,     "AccountNo" VARCHAR(50) NULL,     "RoutingNo" VARCHAR(50) NULL,     "AccountName" VARCHAR(250) NULL);
CREATE TABLE "tblCustContacts" (     "ContactID" INT NOT NULL,     "CustID" INT NOT NULL,     "DefaultContact" INT NOT NULL,     "TypeOfContact" INT NOT NULL,     "Phone" VARCHAR(20) NULL,     "CellPhone" VARCHAR(20) NULL,     "Fax" VARCHAR(20) NULL,     "Email" VARCHAR(50) NULL,     "IsSameAsClient" BOOLEAN NULL);
CREATE TABLE "tblCustomers" (     "CustID" INT NOT NULL,     "CustAbb" VARCHAR(10) NULL,     "Account" INT NULL,     "CountryID" INT NULL,     "Name" VARCHAR(250) NULL,     "Address1" VARCHAR(150) NULL,     "Address2" VARCHAR(150) NULL,     "City" VARCHAR(50) NULL,     "Zip" VARCHAR(50) NULL,     "StateAbb" CHAR(2) NULL,     "DefaultPhone" VARCHAR(20) NULL,     "DefaultFax" VARCHAR(50) NULL,     "DefaultEmail" VARCHAR(50) NULL,     "DefaultWWW" VARCHAR(100) NULL,     "ParentCustID" INT NULL,     "LangAbb" CHAR(3) NULL,     "Remarks" VARCHAR(250) NULL,     "DateMod" TIMESTAMP NULL,     "UserMod" CHAR(30) NULL,     "TaxID" VARCHAR(50) NULL,     "VATID" VARCHAR(50) NULL,     "RepModeID" SMALLINT NULL,     "GraalID" INT NULL,     "Commission" DECIMAL(18,2) NULL,     "DefAgrDoc" VARCHAR(30) NULL,     "Jurisdiction" VARCHAR(200) NULL,     "CommissionForeign" DECIMAL(18,2) NULL,     "CommissionMaterials" DECIMAL(18,2) NULL,     "Status" CHAR(1) NULL);
CREATE TABLE "tblCustTypes" (     "CustID" INT NOT NULL,     "CustTypeID" INT NOT NULL);
CREATE TABLE "tblCustUsers" (     "CustID" INT NOT NULL,     "Login" VARCHAR(30) NOT NULL);
CREATE TABLE "tblDtgUserColumns" (     "Login" VARCHAR(30) NOT NULL,     "dtgName" VARCHAR(30) NOT NULL,     "ColName" VARCHAR(30) NOT NULL,     "State" INT NOT NULL);
CREATE TABLE "tblEvents" (     "TitleID" INT NULL,     "EventCode" INT NULL,     "ID" INT NULL,     "DateMod" TIMESTAMP NULL,     "UserMod" CHAR(30) NULL);
CREATE TABLE "tblFraVAT_KSEF" (     "FVNr" INT NOT NULL,     "UPODate" DATE NOT NULL,     "UPOFile" VARCHAR(500) NOT NULL,     "ksefNumber" CHAR(200) NULL);
CREATE TABLE "tblFraVAT_New" (     "FVNr" INT NOT NULL,     "FVDate" TIMESTAMP NOT NULL,     "FVDateIssued" TIMESTAMP NULL,     "FVType" SMALLINT NULL,     "CustID" INT NULL,     "OrigCurrency" VARCHAR(3) NULL,     "FVCurrency" VARCHAR(3) NULL,     "GraalPerc" NUMERIC(19,4) NULL,     "VATCode" VARCHAR(10) NULL,     "VatPerc" NUMERIC(19,4) NULL,     "NetAmt" NUMERIC(19,4) NULL,     "NetAmtCurr" NUMERIC(19,4) NULL,     "VatAmt" NUMERIC(19,4) NULL,     "XRate" NUMERIC(19,4) NULL,     "VatAmtCurr" NUMERIC(19,4) NULL,     "GrossAmt" NUMERIC(19,4) NULL,     "InvNr" INT NULL,     "InvAmt" NUMERIC(19,4) NULL,     "Title" VARCHAR(200) NULL,     "ISBNNr" VARCHAR(50) NULL,     "PayType" VARCHAR(255) NULL,     "InvType" VARCHAR(1) NULL,     "FVDescription" VARCHAR(100) NULL,     "BilNr" INT NULL,     "OrigFVNr" INT NULL,     "CorrectFVNr" INT NULL,     "CreditID" INT NULL,     "ApplyID" INT NULL,     "PayDate" DATE NULL,     "EnterDate" TIMESTAMP NULL,     "EnterEmployee" CHAR(100) NULL,     "Status" CHAR(10) NULL);
CREATE TABLE "tblInvoice" (     "InvNum" INT NOT NULL,     "InvType" CHAR(1) NOT NULL,     "InvDate" TIMESTAMP NULL,     "BillToId" INT NOT NULL,     "ClientId" INT NULL,     "ShipToId" INT NULL,     "CurrId" CHAR(3) NULL,     "TotalInvNET" NUMERIC(19,4) NULL,     "VATPerc" INT NULL,     "TermDD" INT NULL,     "Remarks" VARCHAR(255) NULL,     "Status" CHAR(1) NULL,     "SumInWords" VARCHAR(500) NULL,     "Balance" NUMERIC(19,4) NULL,     "CliRef" VARCHAR(50) NULL,     "Descr" VARCHAR(200) NULL,     "DateDue" TIMESTAMP NULL,     "UserName" VARCHAR(50) NULL,     "AgentID" INT NULL,     "TaxCode" CHAR(1) NULL,     "TaxValue" NUMERIC(19,4) NULL,     "TaxInfo" CHAR(1) NULL,     "PropID" INT NULL);
ALTER TABLE "ArTransaction" ADD CONSTRAINT "PK_ArTransaction" PRIMARY KEY ("TransactionID");
ALTER TABLE "ArTransactionDetail" ADD CONSTRAINT "PK_ArTransactionDetail" PRIMARY KEY ("ItemID");
CREATE TABLE "tblNotificationsDetails" (     "NotificationID" INT NOT NULL,     "TransactionID" INT NOT NULL,     "NotifyDate" TIMESTAMP NOT NULL);
CREATE TABLE "tblParams" (     "Name" VARCHAR(255) NULL,     "Value" VARCHAR(255) NULL);
CREATE TABLE "tblInvoiceCorrect" (     "InvNumOrig" INT NULL,     "InvNumCorrect" INT NULL);
CREATE TABLE "tblInvoiceDetails" (     "InvNum" INT NOT NULL,     "InvDetKey" INT NOT NULL,     "InvType" CHAR(1) NOT NULL,     "AgID" INT NULL,     "OrdNr" INT NULL,     "NrItems" INT NULL,     "Amount" NUMERIC(19,4) NULL,     "RptTitle" VARCHAR(150) NULL,     "RptISBN" VARCHAR(50) NULL,     "RptAuthor" VARCHAR(150) NULL,     "RoyDate" TIMESTAMP NULL,     "RoyRight" CHAR(15) NULL,     "RoyCopies" INT NULL,     "RoyPrice" NUMERIC(19,4) NULL,     "RoyRate" NUMERIC(19,4) NULL,     "RoyXRate" NUMERIC(19,4) NULL,     "RoyThisRoy" NUMERIC(19,4) NULL,     "RoyAdvLeft" NUMERIC(19,4) NULL,     "RoyRoyDue" NUMERIC(19,4) NULL);
ALTER TABLE "ArTransactionType" ADD CONSTRAINT "PK_ArType" PRIMARY KEY ("ArType");
ALTER TABLE "ArTransferDetail" ADD CONSTRAINT "PK_ArTransferDetail" PRIMARY KEY ("DebitID","TransferID");
ALTER TABLE "ArType" ADD CONSTRAINT "PK_ArType_1" PRIMARY KEY ("ArType");
ALTER TABLE "ArVat" ADD CONSTRAINT "PK_ArVat" PRIMARY KEY ("VatCode");
ALTER TABLE "dictAdvTerm" ADD CONSTRAINT "PK_dictAdvTerm" PRIMARY KEY ("AdvTermId");
CREATE TABLE "tblInvoicePDF" (     "InvNum" INT NULL,     "PDFName" CHAR(256) NULL);
CREATE TABLE "tblMailingLists" (     "ClassCode" VARCHAR(10) NOT NULL,     "SubClassCode" CHAR(5) NOT NULL,     "CustID" INT NOT NULL);
CREATE TABLE "tblMailingTemplates" (     "TempID" INT NOT NULL,     "TempName" VARCHAR(50) NOT NULL,     "TempPath" VARCHAR(255) NOT NULL,     "TempSubject" VARCHAR(255) NOT NULL);
CREATE TABLE "tblMaterial" (     "MatID" INT NOT NULL,     "AgrID" INT NOT NULL,     "MatTypeID" INT NOT NULL,     "Amount" NUMERIC(19,4) NOT NULL,     "Currency" CHAR(3) NULL,     "Remarks" VARCHAR(255) NULL,     "RequestDate" TIMESTAMP NULL,     "ReceiveDate" TIMESTAMP NULL);
CREATE TABLE "tblMergedLog" (     "MergeID" INT NOT NULL,     "MergeDate" DATE NOT NULL,     "PrimaryClientID" INT NOT NULL,     "MergedClientID" INT NOT NULL);
CREATE TABLE "tblMergedLogDetails" (     "MergeID" INT NOT NULL,     "TableName" CHAR(25) NOT NULL,     "FieldName" CHAR(25) NOT NULL,     "TableRecordID" INT NOT NULL);
CREATE TABLE "tblMessages" (     "MsgID" INT NOT NULL,     "Msg" VARCHAR(2000) NOT NULL);
CREATE TABLE "tblMissRoyExcl" (     "AgrRightID" INT NOT NULL,     "ExcludeReasonID" INT NULL,     "ExcludeReasonCode" VARCHAR(3) NULL,     "ExcludeReasonDesc" VARCHAR(200) NULL,     "EnterDate" DATE NULL,     "RoyDate" DATE NULL);
CREATE TABLE "tblNotifications" (     "NotificationID" INT NOT NULL,     "CustAbb" VARCHAR(10) NOT NULL,     "NotifyDate" TIMESTAMP NOT NULL);
CREATE TABLE "tblPerson" (     "PersonID" SMALLINT NOT NULL,     "LastName" VARCHAR(50) NOT NULL,     "FirstName" VARCHAR(50) NOT NULL,     "MiddleName" VARCHAR(50) NULL,     "BirthDate" DATE NULL,     "PESEL" CHAR(11) NULL,     "Status" CHAR(1) NULL,     "Address1" VARCHAR(50) NULL,     "Address2" VARCHAR(50) NULL,     "Zip" VARCHAR(20) NULL,     "City" VARCHAR(50) NULL,     "Country" VARCHAR(50) NULL,     "MobileGRAAL" VARCHAR(50) NULL,     "MobilePrivate" VARCHAR(50) NULL,     "ExtGRAAL" CHAR(2) NULL,     "emailGraal" CHAR(50) NULL,     "emailPriv" CHAR(50) NULL);
CREATE TABLE "tblPersonBonus" (     "PersonID" SMALLINT NULL,     "DateBegin" DATE NULL,     "ContractType" SMALLINT NULL,     "PayUnit" CHAR(1) NULL,     "PayAmt" NUMERIC(19,4) NULL,     "Bonus" BOOLEAN NULL,     "AsstDeductAmt" NUMERIC(19,4) NULL,     "BonusPerc" NUMERIC(19,4) NULL);
CREATE TABLE "tblPersonClient" (     "PersonID" SMALLINT NOT NULL,     "ClientID" INT NOT NULL,     "DateBegin" DATE NULL,     "DateEnd" DATE NULL);
CREATE TABLE "tblPersonContractType" (     "CTypeID" SMALLINT NOT NULL,     "CTypeDescr" VARCHAR(10) NULL);
CREATE TABLE "tblPersonLogin" (     "PersonID" SMALLINT NOT NULL,     "Login" VARCHAR(30) NOT NULL,     "DateBegin" DATE NULL,     "DateEnd" DATE NULL);
CREATE TABLE "tblPlaces" (     "PlaceID" INT NOT NULL,     "PlaceDesc" VARCHAR(50) NOT NULL);
CREATE TABLE "tblPubISBN" (     "PubID" NUMERIC(18,0) NOT NULL,     "PubISBN1" CHAR(5) NOT NULL,     "PubISBN2" CHAR(7) NOT NULL);
CREATE TABLE "tblPublishers" (     "PubID" NUMERIC(18,0) NOT NULL,     "PubName" VARCHAR(250) NULL,     "PubAbb" CHAR(20) NULL,     "ParentPubID" NUMERIC(18,0) NULL);
CREATE TABLE "tblPubLocal" (     "PubLocalID" INT NOT NULL,     "AgrID" INT NULL,     "LocalTitle" CHAR(150) NULL,     "PubDate" TIMESTAMP NULL,     "LocalISBN" VARCHAR(13) NULL,     "Printrun" INT NULL,     "LocalEdition" SMALLINT NULL);
CREATE TABLE "tblRepresentation" (     "CustID" INT NOT NULL,     "CountryID" INT NOT NULL);
CREATE TABLE "tblRoyalty" (     "RoyID" INT NOT NULL,     "AgrID" INT NOT NULL,     "AgrRightID" INT NOT NULL,     "RoyNr" INT NOT NULL,     "EnterDate" TIMESTAMP NULL,     "RoyDate" TIMESTAMP NULL,     "Copies" INT NULL,     "Price" NUMERIC(19,4) NULL,     "RoyRate" NUMERIC(19,4) NULL,     "XRate" NUMERIC(19,4) NULL,     "ThisRoy" NUMERIC(19,4) NULL,     "AdvLeft" NUMERIC(19,4) NULL,     "RoyDue" NUMERIC(19,4) NULL,     "Pay" NUMERIC(19,4) NULL,     "AdvID" INT NULL);
CREATE TABLE "tblRoyInventory" (     "AgrID" INT NOT NULL,     "AgrRightID" INT NOT NULL,     "InventoryDate" TIMESTAMP NOT NULL,     "OType" CHAR(1) NULL,     "Copies" INT NULL,     "PubDate" TIMESTAMP NULL,     "ISBN" CHAR(16) NULL,     "LocalPrice" NUMERIC(19,4) NULL,     "AgrPubID" VARCHAR(20) NULL);
CREATE TABLE "tblRoyRates" (     "Step" SMALLINT NOT NULL,     "AgrRightID" INT NOT NULL,     "AgrID" INT NULL,     "CpsMax" INT NULL,     "Rate" NUMERIC(19,4) NULL);
CREATE TABLE "tblSeries" (     "SeriesID" SMALLINT NOT NULL,     "CustID" INT NULL,     "SeriesFullName" CHAR(150) NULL,     "SeriesShortName" CHAR(50) NULL);
CREATE TABLE "tblSubmEvents" (     "SubmEventID" NUMERIC(18,0) NOT NULL,     "SubmID" INT NULL,     "EventCode" INT NULL,     "EventDate" TIMESTAMP NOT NULL,     "NoOfCopies" INT NULL,     "EndDate" TIMESTAMP NULL);
CREATE TABLE "tblSubmissions" (     "SubmID" INT NOT NULL,     "CopyTypeID" SMALLINT NULL,     "SubmSentTypeID" SMALLINT NULL,     "TitleID" INT NULL,     "CustID" INT NULL,     "Exclusive" INT NULL,     "SubmDate" TIMESTAMP NOT NULL,     "SentDate" TIMESTAMP NULL,     "EndDate" TIMESTAMP NULL,     "ReturnDate" TIMESTAMP NULL,     "NoOfCopies" INT NULL,     "TrackingNo" CHAR(30) NULL,     "UserMod" CHAR(30) NOT NULL,     "DateMod" TIMESTAMP NOT NULL,     "Status" CHAR(1) NULL,     "SubmNr" INT NULL,     "Remarks" VARCHAR(1000) NULL,     "ContactID" INT NULL);
CREATE TABLE "tblTaxResidenceCertificate" (     "CertID" INT NOT NULL,     "ClientID" INT NOT NULL,     "ValidDate" DATE NOT NULL,     "RequestDate" DATE NULL,     "ReceiveDate" DATE NULL,     "UpdateDate" DATE NOT NULL,     "HasCert" CHAR(1) NOT NULL,     "CountryID" INT NULL,     "CertFile" BYTEA NULL,     "Remarks" CHAR(300) NULL);
CREATE TABLE "tblTaxResidenceSend" (     "CertID" INT NULL,     "ClientID" INT NULL,     "DateSend" DATE NULL,     "SendOrig" BOOLEAN NULL,     "SendCopy" BOOLEAN NULL);
CREATE TABLE "tblTitAuthors" (     "AuthorID" INT NOT NULL,     "TitleID" INT NOT NULL,     "Main" SMALLINT NULL,     "Lp" INT NOT NULL);
CREATE TABLE "tblTitAux" (     "TitleID" INT NOT NULL,     "CopyrightLine" VARCHAR(200) NULL);
CREATE TABLE "tblTitCopies" (     "CopyTypeID" SMALLINT NULL,     "TitleID" INT NULL,     "NoOfCopies" INT NULL,     "ReceiptDate" TIMESTAMP NULL);
CREATE TABLE "tblTitEvents" (     "TitEventID" NUMERIC(18,0) NOT NULL,     "CopyTypeID" SMALLINT NULL,     "EventCode" INT NULL,     "TitleID" INT NULL,     "EventDate" TIMESTAMP NULL,     "NoOfCopies" INT NULL,     "EndDate" TIMESTAMP NULL);
CREATE TABLE "tblTitles" (     "TitleID" INT NOT NULL,     "CustID" INT NULL,     "PropID" INT NULL,     "Proprietor" CHAR(1) NULL,     "LangAbb" CHAR(3) NULL,     "ClassCode" VARCHAR(10) NULL,     "CoverFormatID" INT NULL,     "Title" VARCHAR(150) NOT NULL,     "ISBN1" CHAR(5) NULL,     "ISBN2" CHAR(7) NULL,     "ISBN3" CHAR(6) NULL,     "ISBN4" CHAR(1) NULL,     "SeriesIID" INT NULL,     "Edition" INT NULL,     "DateOfReceipt" TIMESTAMP NULL,     "NoOfPages" INT NULL,     "CopyrightYear" CHAR(4) NULL,     "CopyrightOwner" CHAR(1) NULL,     "CopyrightOwnerDesc" VARCHAR(150) NULL,     "KeyWords" VARCHAR(250) NULL,     "TitleVolume" INT NULL,     "NoOfTitleVolumes" INT NULL,     "Hit" BOOLEAN NULL,     "Junk" BOOLEAN NULL,     "CD" BOOLEAN NULL,     "Collection" BOOLEAN NULL,     "Remarks" VARCHAR(1000) NULL,     "UserMod" CHAR(30) NOT NULL,     "DateMod" TIMESTAMP NOT NULL,     "ISBN" VARCHAR(20) NULL,     "PubID" INT NULL,     "ProprietorDesc" VARCHAR(200) NULL,     "ISBN0" VARCHAR(3) NULL);
CREATE TABLE "tblTitSubClass" (     "SubClassCode" CHAR(5) NOT NULL,     "TitleID" INT NOT NULL);
CREATE TABLE "tblTitTargetGroups" (     "TitleID" INT NULL,     "TargetGroupID" NUMERIC(18,0) NULL);
CREATE TABLE "tblUserAccess" (     "Login" VARCHAR(30) NOT NULL,     "PlaceID" INT NOT NULL);
CREATE TABLE "tblUserParams" (     "Login" VARCHAR(30) NOT NULL,     "Name" VARCHAR(30) NOT NULL,     "Value" VARCHAR(300) NOT NULL);
CREATE TABLE "tblUsers" (     "Login" VARCHAR(30) NOT NULL,     "FirstName" VARCHAR(50) NOT NULL,     "MiddleName" VARCHAR(50) NULL,     "LastName" VARCHAR(50) NOT NULL,     "CompanyPosition" VARCHAR(50) NULL,     "Birthday" TIMESTAMP NULL,     "Status" CHAR(1) NOT NULL,     "Initials" VARCHAR(10) NULL,     "Phone" VARCHAR(20) NULL,     "MobilePhone" VARCHAR(20) NULL,     "Email" VARCHAR(50) NULL,     "Sex" CHAR(1) NULL,     "Street" VARCHAR(50) NULL,     "ZipCode" VARCHAR(10) NULL,     "City" VARCHAR(30) NULL,     "Country" VARCHAR(20) NULL,     "Remarks" VARCHAR(500) NULL,     "UserMod" CHAR(30) NULL,     "DateMod" TIMESTAMP NULL,     "Nameday" TIMESTAMP NULL,     "PersonID" SMALLINT NULL);
CREATE TABLE "tblVersionInfo" (     "Version" CHAR(10) NOT NULL,     "DateMod" CHAR(10) NOT NULL,     "Description" VARCHAR(4000) NOT NULL,     "Id" INT NOT NULL);
ALTER TABLE "ArAccount" ADD CONSTRAINT "PK_ArAccount" PRIMARY KEY ("AccountID");
ALTER TABLE "ArApply" ADD CONSTRAINT "PK_ArApply" PRIMARY KEY ("ApplyID");
ALTER TABLE "ArDefaultAccount" ADD CONSTRAINT "PK_ArDefaultAccount" PRIMARY KEY ("TransactionType");
ALTER TABLE "dictAdvType" ADD CONSTRAINT "PK_dictAdvType" PRIMARY KEY ("AdvTypeId");
ALTER TABLE "dictAdvWithoutInvExcludeReason" ADD CONSTRAINT "PK_dictAdvWithoutInvExclReason" PRIMARY KEY ("ExcludeReasonID");
ALTER TABLE "dictAgrEvents" ADD CONSTRAINT "PK_dictAgrEvents" PRIMARY KEY ("AgrEventCode");
ALTER TABLE "dictAgrTemplates" ADD CONSTRAINT "PK_dictAgrTemplates" PRIMARY KEY ("Name");
ALTER TABLE "dictArticles" ADD CONSTRAINT "PK_DICTARTICLES" PRIMARY KEY ("Article");
ALTER TABLE "dictCopyType" ADD CONSTRAINT "PK_DICTCOPYTYPE" PRIMARY KEY ("CopyTypeID");
ALTER TABLE "dictCountries" ADD CONSTRAINT "PK_dictCountries_1" PRIMARY KEY ("CountryID");
ALTER TABLE "dictCoverFormat" ADD CONSTRAINT "PK_dictCoverFormat" PRIMARY KEY ("CoverFormatID");
ALTER TABLE "dictCurrencies" ADD CONSTRAINT "PK_DICTCURRENCIES" PRIMARY KEY ("CurrID");
ALTER TABLE "dictCustTypes" ADD CONSTRAINT "PK_dictCustTypes" PRIMARY KEY ("CustTypeID");
ALTER TABLE "dictDistributionType" ADD CONSTRAINT "PK_DICTDISTRIBUTIONTYPE" PRIMARY KEY ("DistID");
ALTER TABLE "dictEvents" ADD CONSTRAINT "PK_DICTEVENTS" PRIMARY KEY ("EventCode");
ALTER TABLE "dictLanguages" ADD CONSTRAINT "PK_DICTLANGUAGES" PRIMARY KEY ("LangAbb");
ALTER TABLE "dictMatType" ADD CONSTRAINT "PK_dictMatType" PRIMARY KEY ("MatTypeID");
ALTER TABLE "dictMissRoyExcludeReason" ADD CONSTRAINT "PK_dictMissRoyReason" PRIMARY KEY ("ExcludeReasonID");
ALTER TABLE "dictPriceType" ADD CONSTRAINT "PK_dictPriceType" PRIMARY KEY ("PriceTypeID");
ALTER TABLE "dictRepModes" ADD CONSTRAINT "PK_DICTREPMODES" PRIMARY KEY ("RepModeID");
ALTER TABLE "dictRightsForm" ADD CONSTRAINT "PK_DICTRIGHTSFORM" PRIMARY KEY ("RightFormID");
ALTER TABLE "dictRoyAccountInterval" ADD CONSTRAINT "PK_DICTROYACCOUNTINTERVAL" PRIMARY KEY ("RoyAccountIntervalID");
ALTER TABLE "dictRoyPriceType" ADD CONSTRAINT "PK_DICTROYPRICETYPE" PRIMARY KEY ("RoyPriceTypeID");
ALTER TABLE "dictRoyType" ADD CONSTRAINT "PK_DICTROYTYPE" PRIMARY KEY ("RoyTypeID");
ALTER TABLE "dictStates" ADD CONSTRAINT "PK_dictStates" PRIMARY KEY ("StateAbb");
ALTER TABLE "dictSubmSentType" ADD CONSTRAINT "PK_DICTSUBMSENTTYPE" PRIMARY KEY ("SubmSentTypeID");
ALTER TABLE "dictTargetGroups" ADD CONSTRAINT "PK_DICTTARGETGROUPS" PRIMARY KEY ("TargetGroupID");
ALTER TABLE "dictTitMainClass" ADD CONSTRAINT "PK_DICTTITMAINCLASS" PRIMARY KEY ("ClassCode");
ALTER TABLE "dictTitSubClass" ADD CONSTRAINT "PK_DICTTITSUBCLASS" PRIMARY KEY ("SubClassCode");
ALTER TABLE "dictXRateExcelNames" ADD CONSTRAINT "PK_dictXRateExcelNames" PRIMARY KEY ("CurrID","Name");
ALTER TABLE "dictXRates" ADD CONSTRAINT "PK_dictXRates1" PRIMARY KEY ("CurrID","CurrDate");
ALTER TABLE "dtproperties" ADD CONSTRAINT "pk_dtproperties" PRIMARY KEY ("id","property");
ALTER TABLE "HelionLocal" ADD CONSTRAINT "PK_HelionLocal" PRIMARY KEY ("ISBNORG","ISBNHELION");
ALTER TABLE "lkpPayType" ADD CONSTRAINT "PK_LKPPAYTYPE" PRIMARY KEY ("PayTypeID");
ALTER TABLE "PearsonAdvAndRoy" ADD CONSTRAINT "PK_PearsonAdvAnd Roy" PRIMARY KEY ("ContractID");
ALTER TABLE "PearsonMaterial" ADD CONSTRAINT "PK_PearsonMaterial" PRIMARY KEY ("MyNumber");
ALTER TABLE "tblAdvance" ADD CONSTRAINT "PK_tblAdvance" PRIMARY KEY ("AdvID");
ALTER TABLE "tblAgreements" ADD CONSTRAINT "PK_TBLAGREEMENTS" PRIMARY KEY ("AgrID");
ALTER TABLE "tblAgrEvents" ADD CONSTRAINT "PK_TBLAGREVENTS" PRIMARY KEY ("AgrEventID");
ALTER TABLE "tblAgrRights" ADD CONSTRAINT "PK_TBLAGRRIGHTS" PRIMARY KEY ("AgrRightID");
ALTER TABLE "tblAuthors" ADD CONSTRAINT "PK_TBLAUTHORS" PRIMARY KEY ("AuthorID");
ALTER TABLE "tblCertPub" ADD CONSTRAINT "PK_tblCertPub" PRIMARY KEY ("ClientID","Year","PubID");
ALTER TABLE "tblClients_obsolete" ADD CONSTRAINT "PK_tblClients" PRIMARY KEY ("CustID");
ALTER TABLE "tblContacts" ADD CONSTRAINT "PK_TBLCONTACTS" PRIMARY KEY ("ContactID");
ALTER TABLE "tblCustBank" ADD CONSTRAINT "PK_tblCustBank" PRIMARY KEY ("CustID");
ALTER TABLE "tblCustContacts" ADD CONSTRAINT "PK_tblCustContacts" PRIMARY KEY ("ContactID","CustID");
ALTER TABLE "tblCustomers" ADD CONSTRAINT "PK_TBLCUSTOMERS" PRIMARY KEY ("CustID");
ALTER TABLE "tblCustTypes" ADD CONSTRAINT "PK_tblCustTypes" PRIMARY KEY ("CustID","CustTypeID");
ALTER TABLE "tblCustUsers" ADD CONSTRAINT "PK_tblCustUsers" PRIMARY KEY ("CustID","Login");
ALTER TABLE "tblFraVAT_New" ADD CONSTRAINT "PK_tblFraVAT_New" PRIMARY KEY ("FVNr","FVDate");
ALTER TABLE "tblInvoice" ADD CONSTRAINT "PK_tblInvoice_1" PRIMARY KEY ("InvNum");
ALTER TABLE "tblInvoiceDetails" ADD CONSTRAINT "PK_tblInvoiceDetails" PRIMARY KEY ("InvNum","InvDetKey");
ALTER TABLE "tblMailingLists" ADD CONSTRAINT "PK_tblMailingLists" PRIMARY KEY ("ClassCode","SubClassCode","CustID");
ALTER TABLE "tblMailingTemplates" ADD CONSTRAINT "PK_tblMailTemplates" PRIMARY KEY ("TempID");
ALTER TABLE "tblMaterial" ADD CONSTRAINT "PK_tblMaterial" PRIMARY KEY ("MatID");
ALTER TABLE "tblPerson" ADD CONSTRAINT "PK_tblPerson" PRIMARY KEY ("PersonID");
ALTER TABLE "tblPersonContractType" ADD CONSTRAINT "PK__tblPerso__E83DD31530AEFB81" PRIMARY KEY ("CTypeID");
ALTER TABLE "tblPersonLogin" ADD CONSTRAINT "PK_tblPersonLogin" PRIMARY KEY ("PersonID","Login");
ALTER TABLE "tblPlaces" ADD CONSTRAINT "PK_tblPlaces" PRIMARY KEY ("PlaceID");
ALTER TABLE "tblPubISBN" ADD CONSTRAINT "PK_tblPubISBN" PRIMARY KEY ("PubID","PubISBN1","PubISBN2");
ALTER TABLE "tblPublishers" ADD CONSTRAINT "PK_TBLPUBLISHERS" PRIMARY KEY ("PubID");
ALTER TABLE "tblPubLocal" ADD CONSTRAINT "PK_TBLPUBLOCAL" PRIMARY KEY ("PubLocalID");
ALTER TABLE "tblRoyalty" ADD CONSTRAINT "PK_tblRoyalty" PRIMARY KEY ("RoyID");
ALTER TABLE "tblRoyRates" ADD CONSTRAINT "PK_TBLROYRATES" PRIMARY KEY ("Step","AgrRightID");
ALTER TABLE "tblSeries" ADD CONSTRAINT "PK_TBLSERIES" PRIMARY KEY ("SeriesID");
ALTER TABLE "tblSubmEvents" ADD CONSTRAINT "PK_TBLSUBMEVENTS" PRIMARY KEY ("SubmEventID");
ALTER TABLE "tblSubmissions" ADD CONSTRAINT "PK_TBLSUBMISSIONS" PRIMARY KEY ("SubmID");
ALTER TABLE "tblTaxResidenceCertificate" ADD CONSTRAINT "PK__tblTaxRe__E5BD38E5590DF54F" PRIMARY KEY ("CertID");
ALTER TABLE "tblTitAuthors" ADD CONSTRAINT "PK_tblTitAuthors" PRIMARY KEY ("AuthorID","TitleID");
ALTER TABLE "tblTitAux" ADD CONSTRAINT "PK_tblTitAux" PRIMARY KEY ("TitleID");
ALTER TABLE "tblTitEvents" ADD CONSTRAINT "PK_TBLTITEVENTS" PRIMARY KEY ("TitEventID");
ALTER TABLE "tblTitles" ADD CONSTRAINT "PK_TBLTITLES" PRIMARY KEY ("TitleID");
ALTER TABLE "tblTitSubClass" ADD CONSTRAINT "PK_tblTitSubClass" PRIMARY KEY ("SubClassCode","TitleID");
ALTER TABLE "tblUserAccess" ADD CONSTRAINT "PK_tblUserAccess" PRIMARY KEY ("Login","PlaceID");
ALTER TABLE "tblUserParams" ADD CONSTRAINT "PK_tblUserParams" PRIMARY KEY ("Login","Name");
ALTER TABLE "tblUsers" ADD CONSTRAINT "PK_tblUsers" PRIMARY KEY ("Login");
ALTER TABLE "ArApply" ADD CONSTRAINT "FK_ArApply_ArTransaction" FOREIGN KEY ("CreditID") REFERENCES "ArTransaction" ("TransactionID");
ALTER TABLE "ArTransactionDetail" ADD CONSTRAINT "FK_ArTransactionDetail_ArTransaction" FOREIGN KEY ("TransactionID") REFERENCES "ArTransaction" ("TransactionID");
ALTER TABLE "ArTransferDetail" ADD CONSTRAINT "FK_ArTransferDetail_ArTransaction" FOREIGN KEY ("TransferID") REFERENCES "ArTransaction" ("TransactionID");
ALTER TABLE "dictArticles" ADD CONSTRAINT "FK_DICTARTI_RELATIONS_DICTLANG" FOREIGN KEY ("LangAbb") REFERENCES "dictLanguages" ("LangAbb");
ALTER TABLE "dictRoyType" ADD CONSTRAINT "FK_DICTROYT_RLSH_45_TBLAGRRI" FOREIGN KEY ("AgrRightID") REFERENCES "tblAgrRights" ("AgrRightID");
ALTER TABLE "dictTitSubClass" ADD CONSTRAINT "FK_DICTTITS_RLSH_19_DICTTITM" FOREIGN KEY ("ClassCode") REFERENCES "dictTitMainClass" ("ClassCode");
ALTER TABLE "tblAdvance" ADD CONSTRAINT "FK_TBLADVAN_RLSH_3_TBLAGREE" FOREIGN KEY ("AgrID") REFERENCES "tblAgreements" ("AgrID");
ALTER TABLE "tblAgreements" ADD CONSTRAINT "FK_TBLAGREE_RLSH_14_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblAgreements" ADD CONSTRAINT "FK_TBLAGREE_RLSH_39_DICTLANG" FOREIGN KEY ("LangAbbr") REFERENCES "dictLanguages" ("LangAbb");
ALTER TABLE "tblAgreements" ADD CONSTRAINT "FK_TBLAGREE_RELATIONS_DICTCURR" FOREIGN KEY ("CurrID") REFERENCES "dictCurrencies" ("CurrID");
ALTER TABLE "tblAgreements" ADD CONSTRAINT "FK_TBLAGREE_RLSH_4_TBLCUSTO" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblAgrEvents" ADD CONSTRAINT "FK_tblAgrEvents_dictAgrEvents" FOREIGN KEY ("AgrEventCode") REFERENCES "dictAgrEvents" ("AgrEventCode");
ALTER TABLE "tblAgrEvents" ADD CONSTRAINT "FK_TBLAGREV_RLSH_51_TBLAGREE" FOREIGN KEY ("AgrID") REFERENCES "tblAgreements" ("AgrID");
ALTER TABLE "tblAgrRights" ADD CONSTRAINT "FK_TBLAGRRI_RLSH_2_TBLAGREE" FOREIGN KEY ("AgrID") REFERENCES "tblAgreements" ("AgrID");
ALTER TABLE "tblAgrRights" ADD CONSTRAINT "FK_tblAgrRights_dictRoyAccountInterval" FOREIGN KEY ("RoyAccountIntervalID") REFERENCES "dictRoyAccountInterval" ("RoyAccountIntervalID");
ALTER TABLE "tblAgrRights" ADD CONSTRAINT "FK_tblAgrRights_dictPriceType" FOREIGN KEY ("PriceTypeID") REFERENCES "dictPriceType" ("PriceTypeID");
ALTER TABLE "tblAgrRights" ADD CONSTRAINT "FK_TBLAGRRI_RLSH_48_DICTROYP" FOREIGN KEY ("RoyPriceTypeID") REFERENCES "dictRoyPriceType" ("RoyPriceTypeID");
ALTER TABLE "tblAgrRights" ADD CONSTRAINT "FK_TBLAGRRI_RLSH_43_DICTDIST" FOREIGN KEY ("DistID") REFERENCES "dictDistributionType" ("DistID");
ALTER TABLE "tblAgrRights" ADD CONSTRAINT "FK_TBLAGRRI_RLSH_44_DICTRIGH" FOREIGN KEY ("RightID") REFERENCES "dictRightsForm" ("RightFormID");
ALTER TABLE "tblClients_obsolete" ADD CONSTRAINT "FK_TBLCLIEN_RLSH_29_TBLCUSTO" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblClients_obsolete" ADD CONSTRAINT "FK_TBLCLIEN_RLSH_36_DICTREPM" FOREIGN KEY ("RepModeID") REFERENCES "dictRepModes" ("RepModeID");
ALTER TABLE "tblCustBank" ADD CONSTRAINT "FK_tblCustBank_tblCustomers" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblCustContacts" ADD CONSTRAINT "FK_TBLCUSTC_RLSH_25_TBLCUSTO" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblCustContacts" ADD CONSTRAINT "FK_TBLCUSTC_RLSH_26_TBLCONTA" FOREIGN KEY ("ContactID") REFERENCES "tblContacts" ("ContactID");
ALTER TABLE "tblCustomers" ADD CONSTRAINT "FK_tblCustomers_dictStates" FOREIGN KEY ("StateAbb") REFERENCES "dictStates" ("StateAbb");
ALTER TABLE "tblCustomers" ADD CONSTRAINT "FK_tblCustomers_dictLanguages" FOREIGN KEY ("LangAbb") REFERENCES "dictLanguages" ("LangAbb");
ALTER TABLE "tblCustTypes" ADD CONSTRAINT "FK_tblCustTypes_dictCustTypes" FOREIGN KEY ("CustTypeID") REFERENCES "dictCustTypes" ("CustTypeID");
ALTER TABLE "tblCustTypes" ADD CONSTRAINT "FK_tblCustTypes_tblCustomers" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblCustUsers" ADD CONSTRAINT "FK_tblCustUsers_tblUsers" FOREIGN KEY ("Login") REFERENCES "tblUsers" ("Login");
ALTER TABLE "tblCustUsers" ADD CONSTRAINT "FK_tblCustUsers_tblCustomers" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblDtgUserColumns" ADD CONSTRAINT "FK_tblDtgUserColumns_tblUsers" FOREIGN KEY ("Login") REFERENCES "tblUsers" ("Login");
ALTER TABLE "tblEvents" ADD CONSTRAINT "FK_TBLEVENT_RELATIONS_DICTEVEN" FOREIGN KEY ("EventCode") REFERENCES "dictEvents" ("EventCode");
ALTER TABLE "tblEvents" ADD CONSTRAINT "FK_TBLEVENT_RELATIONS_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblMailingLists" ADD CONSTRAINT "FK_tblMailingLists_tblCustomers" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblMailingLists" ADD CONSTRAINT "FK_tblMailingLists_dictTitMainClass" FOREIGN KEY ("ClassCode") REFERENCES "dictTitMainClass" ("ClassCode");
ALTER TABLE "tblMailingLists" ADD CONSTRAINT "FK_tblMailingLists_dictTitSubClass" FOREIGN KEY ("SubClassCode") REFERENCES "dictTitSubClass" ("SubClassCode");
ALTER TABLE "tblPubISBN" ADD CONSTRAINT "FK_TBLPUBIS_RELATIONS_TBLPUBLI" FOREIGN KEY ("PubID") REFERENCES "tblPublishers" ("PubID");
ALTER TABLE "tblPubLocal" ADD CONSTRAINT "FK_TBLPUBLO_RLSH_47_TBLAGREE" FOREIGN KEY ("AgrID") REFERENCES "tblAgreements" ("AgrID");
ALTER TABLE "tblRoyalty" ADD CONSTRAINT "FK_TBLROYAL_RLSH_1_TBLAGREE" FOREIGN KEY ("AgrID") REFERENCES "tblAgreements" ("AgrID");
ALTER TABLE "tblRoyRates" ADD CONSTRAINT "FK_TBLROYRA_RLSH_15_TBLAGREE" FOREIGN KEY ("AgrID") REFERENCES "tblAgreements" ("AgrID");
ALTER TABLE "tblRoyRates" ADD CONSTRAINT "FK_TBLROYRA_RLSH_5_TBLAGRRI" FOREIGN KEY ("AgrRightID") REFERENCES "tblAgrRights" ("AgrRightID");
ALTER TABLE "tblSeries" ADD CONSTRAINT "FK_TBLSERIE_RLSH_27_TBLCUSTO" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblSubmEvents" ADD CONSTRAINT "FK_TBLSUBME_RLSH_50_DICTEVEN" FOREIGN KEY ("EventCode") REFERENCES "dictEvents" ("EventCode");
ALTER TABLE "tblSubmEvents" ADD CONSTRAINT "FK_TBLSUBME_RLSH_49_TBLSUBMI" FOREIGN KEY ("SubmID") REFERENCES "tblSubmissions" ("SubmID");
ALTER TABLE "tblSubmissions" ADD CONSTRAINT "FK_TBLSUBMI_RLSH_32_DICTSUBM" FOREIGN KEY ("SubmSentTypeID") REFERENCES "dictSubmSentType" ("SubmSentTypeID");
ALTER TABLE "tblSubmissions" ADD CONSTRAINT "FK_TBLSUBMI_RLSH_13_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblSubmissions" ADD CONSTRAINT "FK_TBLSUBMI_RLSH_31_TBLCUSTO" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblSubmissions" ADD CONSTRAINT "FK_TBLSUBMI_RLSH_33_DICTCOPY" FOREIGN KEY ("CopyTypeID") REFERENCES "dictCopyType" ("CopyTypeID");
ALTER TABLE "tblTitAuthors" ADD CONSTRAINT "FK_TBLTITAU_RLSH_11_TBLAUTHO" FOREIGN KEY ("AuthorID") REFERENCES "tblAuthors" ("AuthorID");
ALTER TABLE "tblTitAuthors" ADD CONSTRAINT "FK_TBLTITAU_RLSH_12_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblTitAux" ADD CONSTRAINT "FK_tblTitAux_tblTitles" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblTitCopies" ADD CONSTRAINT "FK_TBLTITCO_RELATIONS_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblTitCopies" ADD CONSTRAINT "FK_TBLTITCO_RELATIONS_DICTCOPY" FOREIGN KEY ("CopyTypeID") REFERENCES "dictCopyType" ("CopyTypeID");
ALTER TABLE "tblTitEvents" ADD CONSTRAINT "FK_TBLTITEV_RLSH_46_DICTCOPY" FOREIGN KEY ("CopyTypeID") REFERENCES "dictCopyType" ("CopyTypeID");
ALTER TABLE "tblTitEvents" ADD CONSTRAINT "FK_TBLTITEV_RLSH_16_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblTitEvents" ADD CONSTRAINT "FK_TBLTITEV_RLSH_17_DICTEVEN" FOREIGN KEY ("EventCode") REFERENCES "dictEvents" ("EventCode");
ALTER TABLE "tblTitles" ADD CONSTRAINT "FK_TBLTITLE_RELATIONS_TBLCUSTO" FOREIGN KEY ("CustID") REFERENCES "tblCustomers" ("CustID");
ALTER TABLE "tblTitles" ADD CONSTRAINT "FK_tblTitles_dictCoverFormat" FOREIGN KEY ("CoverFormatID") REFERENCES "dictCoverFormat" ("CoverFormatID");
ALTER TABLE "tblTitles" ADD CONSTRAINT "FK_TBLTITLE_RLSH_18_DICTTITM" FOREIGN KEY ("ClassCode") REFERENCES "dictTitMainClass" ("ClassCode");
ALTER TABLE "tblTitles" ADD CONSTRAINT "FK_TBLTITLE_RELATIONS_DICTLANG" FOREIGN KEY ("LangAbb") REFERENCES "dictLanguages" ("LangAbb");
ALTER TABLE "tblTitSubClass" ADD CONSTRAINT "FK_TBLTITSU_RLSH_21_DICTTITS" FOREIGN KEY ("SubClassCode") REFERENCES "dictTitSubClass" ("SubClassCode");
ALTER TABLE "tblTitSubClass" ADD CONSTRAINT "FK_TBLTITSU_RLSH_20_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblTitTargetGroups" ADD CONSTRAINT "FK_TBLTITTA_RLSH_22_TBLTITLE" FOREIGN KEY ("TitleID") REFERENCES "tblTitles" ("TitleID");
ALTER TABLE "tblTitTargetGroups" ADD CONSTRAINT "FK_TBLTITTA_RLSH_23_DICTTARG" FOREIGN KEY ("TargetGroupID") REFERENCES "dictTargetGroups" ("TargetGroupID");
ALTER TABLE "tblUserAccess" ADD CONSTRAINT "FK_tblUserAccess_tblPlaces" FOREIGN KEY ("PlaceID") REFERENCES "tblPlaces" ("PlaceID");
ALTER TABLE "tblUserAccess" ADD CONSTRAINT "FK_tblUserAccess_tblUsers" FOREIGN KEY ("Login") REFERENCES "tblUsers" ("Login");
ALTER TABLE "tblUserParams" ADD CONSTRAINT "FK_tblUserParams_tblUsers" FOREIGN KEY ("Login") REFERENCES "tblUsers" ("Login");
CREATE INDEX "IX_ArTrans" ON "ArTransaction" ("RCustID");
CREATE INDEX "IX_ArTrans_1" ON "ArTransaction" ("TransactionType");
CREATE INDEX "IX_ArTrans_2" ON "ArTransaction" ("TransactionDate");
CREATE INDEX "IX_ArTrans_3" ON "ArTransaction" ("Currency");
CREATE INDEX "IX_ArTrans_4" ON "ArTransaction" ("PCustID");
CREATE INDEX "IX_ArTransaction" ON "ArTransaction" ("InvNr");
CREATE INDEX "IX_ArTransDetail" ON "ArTransactionDetail" ("TransactionID");
CREATE INDEX "Relationship_60_FK" ON "dictArticles" ("LangAbb");
CREATE INDEX "Rlsh_45_FK" ON "dictRoyType" ("AgrRightID");
CREATE INDEX "Rlsh_37_FK" ON "dictStates" ("CountryID");
CREATE INDEX "Rlsh_19_FK" ON "dictTitSubClass" ("ClassCode");
CREATE INDEX "IX_dictXRateExcelNames" ON "dictXRateExcelNames" ("CurrID");
CREATE INDEX "IX_PearsonAdvAnd Roy" ON "PearsonAdvAndRoy" ("ISBN");
CREATE INDEX "IX_PearsonMaterial" ON "PearsonMaterial" ("InvoiceNumber");
CREATE INDEX "RLSH_3_FK" ON "tblAdvance" ("AgrID");
CREATE INDEX "RLSH_4_FK" ON "tblAgreements" ("CustID");
CREATE INDEX "RLSH_14_FK" ON "tblAgreements" ("TitleID");
CREATE INDEX "Rlsh_41_FK" ON "tblAgreements" ("CountryID");
CREATE INDEX "Rlsh_39_FK" ON "tblAgreements" ("LangAbbr");
CREATE INDEX "Relationship_61_FK" ON "tblAgreements" ("CurrID");
CREATE INDEX "indAgrCustID" ON "tblAgreements" ("CustID");
CREATE INDEX "Rlsh_51_FK" ON "tblAgrEvents" ("AgrID");
CREATE INDEX "Rlsh_52_FK" ON "tblAgrEvents" ("AgrEventCode");
CREATE INDEX "RLSH_2_FK" ON "tblAgrRights" ("AgrID");
CREATE INDEX "Rlsh_44_FK" ON "tblAgrRights" ("RightID");
CREATE INDEX "Rlsh_43_FK" ON "tblAgrRights" ("DistID");
CREATE INDEX "Rlsh_48_FK" ON "tblAgrRights" ("RoyPriceTypeID");
CREATE INDEX "Rlsh_29_FK" ON "tblClients_obsolete" ("CustID");
CREATE INDEX "Rlsh_36_FK" ON "tblClients_obsolete" ("RepModeID");
CREATE INDEX "Rlsh_28_FK" ON "tblCustBank" ("CustID");
CREATE INDEX "Rlsh_25_FK" ON "tblCustContacts" ("CustID");
CREATE INDEX "Rlsh_26_FK" ON "tblCustContacts" ("ContactID");
CREATE INDEX "Rlsh_35_FK" ON "tblCustomers" ("CountryID");
CREATE INDEX "Rlsh_38_FK" ON "tblCustomers" ("StateAbb");
CREATE UNIQUE INDEX "IX_tblCustomers" ON "tblCustomers" ("CustAbb");
CREATE INDEX "Relationship_57_FK" ON "tblEvents" ("TitleID");
CREATE INDEX "Relationship_58_FK" ON "tblEvents" ("EventCode");
CREATE INDEX "InvDetNonClustIndex" ON "tblInvoiceDetails" ("InvDetKey");
CREATE UNIQUE INDEX "IX_tblPlaces" ON "tblPlaces" ("PlaceDesc");
CREATE INDEX "Relationship_55_FK" ON "tblPubISBN" ("PubID");
CREATE UNIQUE INDEX "Index_2" ON "tblPublishers" ("PubAbb");
CREATE INDEX "Rlsh_47_FK" ON "tblPubLocal" ("AgrID");
CREATE UNIQUE INDEX "IX_tblRoyalty" ON "tblRoyalty" ("AgrID","AgrRightID","RoyNr");
CREATE INDEX "RLSH_5_FK" ON "tblRoyRates" ("AgrRightID");
CREATE INDEX "RLSH_15_FK" ON "tblRoyRates" ("AgrID");
CREATE INDEX "Rlsh_27_FK" ON "tblSeries" ("CustID");
CREATE INDEX "Rlsh_49_FK" ON "tblSubmEvents" ("SubmID");
CREATE INDEX "Rlsh_50_FK" ON "tblSubmEvents" ("EventCode");
CREATE INDEX "RLSH_13_FK" ON "tblSubmissions" ("TitleID");
CREATE INDEX "Rlsh_31_FK" ON "tblSubmissions" ("CustID");
CREATE INDEX "Rlsh_32_FK" ON "tblSubmissions" ("SubmSentTypeID");
CREATE INDEX "Rlsh_33_FK" ON "tblSubmissions" ("CopyTypeID");
CREATE INDEX "RLSH_11_FK" ON "tblTitAuthors" ("AuthorID");
CREATE INDEX "RLSH_12_FK" ON "tblTitAuthors" ("TitleID");
CREATE INDEX "Relationship_56_FK" ON "tblTitCopies" ("TitleID");
CREATE INDEX "Relationship_59_FK" ON "tblTitCopies" ("CopyTypeID");
CREATE INDEX "Rlsh_16_FK" ON "tblTitEvents" ("TitleID");
CREATE INDEX "Rlsh_17_FK" ON "tblTitEvents" ("EventCode");
CREATE INDEX "Rlsh_46_FK" ON "tblTitEvents" ("CopyTypeID");
CREATE INDEX "Rlsh_18_FK" ON "tblTitles" ("ClassCode");
CREATE INDEX "Relationship_53_FK" ON "tblTitles" ("LangAbb");
CREATE INDEX "Relationship_54_FK" ON "tblTitles" ("CustID");
CREATE INDEX "Rlsh_20_FK" ON "tblTitSubClass" ("TitleID");
CREATE INDEX "Rlsh_21_FK" ON "tblTitSubClass" ("SubClassCode");
CREATE INDEX "Rlsh_22_FK" ON "tblTitTargetGroups" ("TitleID");
CREATE INDEX "Rlsh_23_FK" ON "tblTitTargetGroups" ("TargetGroupID");
CREATE INDEX "IX_tblUserParams" ON "tblUserParams" ("Login");